create table public.contracts_managers (
  id bigint generated by default as identity not null,
  contract_id bigint null,
  manager_id bigint null,
  is_deleted boolean null default false,
  version_mode character varying null default 'live'::character varying,
  created_user_id bigint null,
  created_at timestamp without time zone null,
  deleted_user_id bigint null,
  deleted_at timestamp without time zone null,
  constraint contractsmanagers_pkey primary key (id),
  constraint contracts_managers_contract_id_fkey foreign KEY (contract_id) references contracts (id) on update CASCADE on delete set null
) TABLESPACE pg_default;
