-- Create Departments Table (cfg_departments)
CREATE TABLE public.cfg_departments (
    id bigint generated by default as identity not null,
    company_id bigint not null,
    code character varying null,
    description character varying null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    version character varying null default 'live'::character varying,
    parent_id bigint null,
    constraint departments_pkey primary key (id),
    constraint departments_company_fkey foreign key (company_id) references public.cfg_companies(id) on delete cascade,
    constraint departments_parent_fkey foreign key (parent_id) references public.cfg_departments(id) on delete set null
);

-- Enable RLS
ALTER TABLE public.cfg_departments ENABLE ROW LEVEL SECURITY;

-- Policies for cfg_departments
CREATE POLICY "Public departments are viewable by everyone" 
ON public.cfg_departments FOR SELECT 
USING (true);

CREATE POLICY "Public departments are insertable by everyone" 
ON public.cfg_departments FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Public departments are updatable by everyone" 
ON public.cfg_departments FOR UPDATE 
USING (true);

CREATE POLICY "Public departments are deletable by everyone" 
ON public.cfg_departments FOR DELETE 
USING (true);
