-- PATCH: Create cfg_services table
-- Run this in your Supabase SQL Editor for the environment: https://services-supabase-siges.2unk5k.easypanel.host

CREATE TABLE IF NOT EXISTS public.cfg_services (
    id bigint generated by default as identity not null,
    description text null,
    unit character varying null,
    is_available boolean null default true,
    is_deleted boolean null default false,
    version_mode character varying null default 'live'::character varying,
    code character varying null,
    finger_print character varying null,
    company_id bigint null,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    constraint cfg_services_pkey primary key (id),
    constraint cfg_services_company_fkey foreign key (company_id) references public.cfg_companies(id) on delete set null
) TABLESPACE pg_default;

-- Notify Schema Reload
NOTIFY pgrst, 'reload schema';
