-- 1. Motivos de Cancelamento de Ordens
create table public.cfg_orders_cancel_reasons (
  id bigint generated by default as identity not null,
  department_id bigint null,
  description character varying null,
  is_available boolean null default true,
  is_deleted boolean null default false,
  constraint orderscancelreasons_pkey primary key (id),
  constraint orderscancelreasons_department_fkey foreign key (department_id) references public.cfg_departments(id) on delete set null
) TABLESPACE pg_default;

-- 2. Motivos/Causas de Ordens
create table public.cfg_orders_causes_reasons (
  id smallint generated by default as identity not null,
  description character varying null,
  is_available boolean null default true, -- Fixed typo 'is_availabe'
  is_deleted boolean null default false,
  constraint orderscauses_pkey primary key (id)
) TABLESPACE pg_default;

-- 3. Contador de Ordens
create table public.cfg_orders_counter (
  id bigint generated by default as identity not null,
  company_id bigint null,
  year integer null,
  counter bigint null default '0'::bigint,
  is_dev boolean null default false,
  version character varying null default 'live'::character varying,
  constraint orders_counter_pkey primary key (id),
  constraint orders_counter_company_fkey foreign key (company_id) references public.cfg_companies(id) on delete cascade
) TABLESPACE pg_default;

-- Enable RLS (Optional but recommended)
alter table public.cfg_orders_cancel_reasons enable row level security;
alter table public.cfg_orders_causes_reasons enable row level security;
alter table public.cfg_orders_counter enable row level security;

-- Create generic policies (Adjust as needed)
create policy "Public read access" on public.cfg_orders_cancel_reasons for select using (true);
create policy "Public read access" on public.cfg_orders_causes_reasons for select using (true);
create policy "Public read access" on public.cfg_orders_counter for select using (true);

create policy "Authenticated insert" on public.cfg_orders_cancel_reasons for insert with check (auth.role() = 'authenticated');
create policy "Authenticated update" on public.cfg_orders_cancel_reasons for update using (auth.role() = 'authenticated');
create policy "Authenticated delete" on public.cfg_orders_cancel_reasons for delete using (auth.role() = 'authenticated');

create policy "Authenticated insert" on public.cfg_orders_causes_reasons for insert with check (auth.role() = 'authenticated');
create policy "Authenticated update" on public.cfg_orders_causes_reasons for update using (auth.role() = 'authenticated');
create policy "Authenticated delete" on public.cfg_orders_causes_reasons for delete using (auth.role() = 'authenticated');

create policy "Authenticated insert" on public.cfg_orders_counter for insert with check (auth.role() = 'authenticated');
create policy "Authenticated update" on public.cfg_orders_counter for update using (auth.role() = 'authenticated');
create policy "Authenticated delete" on public.cfg_orders_counter for delete using (auth.role() = 'authenticated');
