-- =============================================================================
-- SCHEMA SIGES - ORDEM CORRETA DE DEPENDÊNCIAS
-- =============================================================================
-- Este arquivo deve ser executado em ordem sequencial.
-- As tabelas estão organizadas por níveis de dependência:
-- Nível 0: Tabelas sem dependências
-- Nível 1: Dependem apenas de Nível 0
-- Nível 2: Dependem de Nível 0 e/ou 1
-- E assim por diante...
-- =============================================================================

-- =============================================================================
-- NÍVEL 0: TABELAS SEM DEPENDÊNCIAS (Lookup Tables)
-- =============================================================================

-- 1. STATUS DE USUÁRIOS
CREATE TABLE IF NOT EXISTS public.cfg_users_statuses (
  id bigint generated by default as identity not null,
  code character varying null,
  description character varying null,
  constraint usersstatuses_pkey primary key (id)
);

INSERT INTO public.cfg_users_statuses (id, code, description)
VALUES 
    (1, 'ANA', 'Analise'), 
    (2, 'ATI', 'Ativo'), 
    (3, 'INA', 'Inativo')
ON CONFLICT (id) DO NOTHING;

-- 2. STATUS DE CONTRATOS
CREATE TABLE IF NOT EXISTS public.cfg_contracts_statuses (
    id bigint generated by default as identity not null,
    code character varying null,
    description character varying null,
    color character varying null default '#3b82f6',
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint contracts_statuses_pkey primary key (id)
);

INSERT INTO public.cfg_contracts_statuses (id, code, description, color)
VALUES 
    (1, 'ATI', 'Ativo', '#22c55e'), 
    (2, 'VNC', 'Vencido', '#ef4444'), 
    (3, 'SUS', 'Suspenso', '#f59e0b'),
    (4, 'RASC', 'Rascunho', '#94a3b8')
ON CONFLICT (id) DO NOTHING;

-- 3. STATUS DE UNIDADES
CREATE TABLE IF NOT EXISTS public.cfg_units_statuses (
    id bigint generated by default as identity not null,
    code character varying null,
    description character varying null,
    color character varying null default '#3b82f6',
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint units_statuses_pkey primary key (id)
);

INSERT INTO public.cfg_units_statuses (id, code, description, color)
VALUES 
    (1, 'ATI', 'Ativo', '#22c55e'), 
    (2, 'INA', 'Inativo', '#ef4444'), 
    (3, 'MAN', 'Manutenção', '#f59e0b')
ON CONFLICT (id) DO NOTHING;

-- 4. SISTEMAS (Hierarquia própria)
CREATE TABLE IF NOT EXISTS public.cfg_systems (
    id bigint generated by default as identity not null,
    parent_id bigint null,
    code character varying null,
    description character varying null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint systems_pkey primary key (id),
    constraint systems_parent_fkey foreign key (parent_id) references public.cfg_systems(id) on delete set null
);

-- 5. TIPOS DE UNIDADES (Hierarquia própria)
CREATE TABLE IF NOT EXISTS public.cfg_units_types (
    id bigint generated by default as identity not null,
    parent_id bigint null,
    code character varying null,
    description character varying null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint units_types_pkey primary key (id),
    constraint units_types_parent_fkey foreign key (parent_id) references public.cfg_units_types(id) on delete set null
);

-- 6. ATIVIDADES
CREATE TABLE IF NOT EXISTS public.cfg_activities (
    id bigint generated by default as identity not null,
    code character varying null,
    description character varying null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint activities_pkey primary key (id)
);

-- 7. PRIORIDADES DE ORDENS
CREATE TABLE IF NOT EXISTS public.cfg_orders_priorities (
    id bigint generated by default as identity not null,
    code character varying not null,
    description character varying not null,
    color character varying not null default '#3b82f6',
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint orders_priorities_pkey primary key (id)
);

-- 8. PLANOS DE ORDENS
CREATE TABLE IF NOT EXISTS public.cfg_orders_plans (
    id bigint generated by default as identity not null,
    code character varying not null,
    description character varying not null,
    color character varying null default '#3b82f6',
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint orders_plans_pkey primary key (id)
);

-- 9. OBJETOS DE ORDENS
CREATE TABLE IF NOT EXISTS public.cfg_orders_objects (
    id bigint generated by default as identity not null,
    code character varying not null,
    description character varying not null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint orders_objects_pkey primary key (id)
);

-- 10. TAGS DE ATIVOS
CREATE TABLE IF NOT EXISTS public.cfg_assets_tags (
    id bigint generated by default as identity not null,
    code character varying not null,
    description character varying not null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint assets_tags_pkey primary key (id)
);

-- 11. TIPOS DE ATIVOS
CREATE TABLE IF NOT EXISTS public.cfg_assets_types (
    id bigint generated by default as identity not null,
    code character varying not null,
    description character varying not null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint assets_types_pkey primary key (id)
);

-- 12. STATUS DE ATIVOS
CREATE TABLE IF NOT EXISTS public.cfg_assets_statuses (
    id bigint generated by default as identity not null,
    code character varying not null,
    description character varying not null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint assets_statuses_pkey primary key (id)
);

-- 13. PRIORIDADES DE ATIVOS
CREATE TABLE IF NOT EXISTS public.cfg_assets_priorities (
    id bigint generated by default as identity not null,
    code character varying not null,
    description character varying not null,
    color character varying not null default '#3b82f6',
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint assets_priorities_pkey primary key (id)
);

-- 14. TIPOS DE ORDENS (Hierarquia própria)
CREATE TABLE IF NOT EXISTS public.cfg_orders_types (
    id bigint generated by default as identity not null,
    parent_id bigint null,
    code character varying null,
    description character varying null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint orders_types_pkey primary key (id),
    constraint orders_types_parent_fkey foreign key (parent_id) references public.cfg_orders_types(id) on delete set null
);

-- =============================================================================
-- NÍVEL 1: DEPENDEM DE NÍVEL 0
-- =============================================================================

-- 15. EMPRESAS (Hierarquia própria - sem dependências externas)
CREATE TABLE IF NOT EXISTS public.cfg_companies (
    id bigint generated by default as identity not null,
    code character varying null,
    description character varying null,
    img_file_path character varying null,
    img_file_name character varying null,
    is_available boolean null default true,
    email_sufix character varying null,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    version character varying null default 'live'::character varying,
    parent_id bigint null,
    constraint companies_pkey primary key (id)
);

-- 16. CLIENTES
CREATE TABLE IF NOT EXISTS public.clients (
    id bigint generated by default as identity not null,
    name character varying not null,
    code character varying not null,
    email character varying null,
    mobile character varying null,
    address character varying null,
    img_file_path character varying null,
    img_file_name character varying null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone not null default now(),
    updated_at timestamp without time zone null,
    updated_user_id bigint null,
    deleted_at timestamp without time zone null,
    deleted_user_id bigint null,
    is_deleted boolean null default false,
    constraint clients_pkey primary key (id)
);

-- 17. SUB-TAGS DE ATIVOS (Depende de cfg_assets_tags)
CREATE TABLE IF NOT EXISTS public.cfg_assets_tags_subs (
    id bigint generated by default as identity not null,
    parent_id bigint null references public.cfg_assets_tags(id) on delete cascade,
    code character varying not null,
    description character varying not null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint assets_tags_subs_pkey primary key (id)
);

-- 18. SUB-TIPOS DE ORDENS (Depende de cfg_orders_types)
CREATE TABLE IF NOT EXISTS public.cfg_orders_types_subs (
    id bigint generated by default as identity not null,
    order_type_id bigint null references public.cfg_orders_types(id) on delete cascade,
    parent_id bigint null references public.cfg_orders_types(id) on delete cascade,
    code character varying null,
    description character varying null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint orders_types_subs_pkey primary key (id)
);

-- 18.1. ATRIBUTOS DE ATIVOS (Depende de cfg_assets_types)
CREATE TABLE IF NOT EXISTS public.cfg_assets_attributes (
    id bigint generated by default as identity not null,
    asset_type_id bigint null references public.cfg_assets_types(id) on delete cascade,
    field_key character varying not null,
    label character varying not null,
    data_type character varying not null default 'text', -- text, number, date, boolean, select
    unit character varying null,
    decimals integer null default 0,
    is_required boolean not null default false,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint assets_attributes_pkey primary key (id),
    constraint assets_attributes_type_field_key_unique unique (asset_type_id, field_key)
);

-- =============================================================================
-- NÍVEL 2: DEPENDEM DE NÍVEL 0 E 1
-- =============================================================================

-- 19. DEPARTAMENTOS (Depende de cfg_companies)
CREATE TABLE IF NOT EXISTS public.cfg_departments (
    id bigint generated by default as identity not null,
    company_id bigint not null,
    code character varying null,
    description character varying null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    version character varying null default 'live'::character varying,
    parent_id bigint null,
    constraint departments_pkey primary key (id),
    constraint departments_company_fkey foreign key (company_id) references public.cfg_companies(id) on delete cascade,
    constraint departments_parent_fkey foreign key (parent_id) references public.cfg_departments(id) on delete set null
);

-- 20. VEÍCULOS (Depende de cfg_companies)
CREATE TABLE IF NOT EXISTS public.vehicles (
    id bigint generated by default as identity not null,
    company_id bigint not null,
    description character varying not null,
    plates character varying null,
    model character varying null,
    brand character varying null,
    color character varying null,
    year character varying null,
    is_available boolean null default true,
    created_at timestamp without time zone default now(),
    updated_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint vehicles_pkey primary key (id),
    constraint vehicles_company_fkey foreign key (company_id) references public.cfg_companies(id) on delete cascade
);

-- 21. RELACIONAMENTO TIPOS DE ORDENS <-> ATIVIDADES
CREATE TABLE IF NOT EXISTS public.cfg_orders_types_activities (
    id bigint generated by default as identity not null,
    order_type_id bigint not null references public.cfg_orders_types(id) on delete cascade,
    activity_id bigint not null references public.cfg_activities(id) on delete cascade,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint orders_types_activities_pkey primary key (id)
);

-- 22. RELACIONAMENTO SUB-TIPOS DE ORDENS <-> ATIVIDADES
CREATE TABLE IF NOT EXISTS public.cfg_orders_types_subs_activities (
    id bigint generated by default as identity not null,
    order_type_sub_id bigint not null references public.cfg_orders_types_subs(id) on delete cascade,
    activity_id bigint not null references public.cfg_activities(id) on delete cascade,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint orders_types_subs_activities_pkey primary key (id)
);

-- =============================================================================
-- NÍVEL 3: DEPENDEM DE NÍVEL 0, 1 E 2
-- =============================================================================

-- 23. PERFIS (Depende de cfg_departments)
CREATE TABLE IF NOT EXISTS public.cfg_profiles (
    id bigint generated by default as identity not null,
    description character varying null,
    department_id bigint null,
    version character varying null default 'live'::character varying,
    constraint usersprofiles_pkey primary key (id),
    constraint public_usersprofiles_departmentid_fkey foreign KEY (department_id) references cfg_departments (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

-- 24. PERMISSÕES DE PERFIS (Depende de cfg_profiles)
CREATE TABLE IF NOT EXISTS public.cfg_profiles_permissions (
    id bigint generated by default as identity not null,
    profile_id bigint not null,
    resource character varying not null,
    can_view boolean not null default false,
    can_create boolean not null default false,
    can_edit boolean not null default false,
    can_delete boolean not null default false,
    created_at timestamp without time zone default now(),
    constraint profiles_permissions_pkey primary key (id),
    constraint profiles_permissions_profile_fkey foreign key (profile_id) references public.cfg_profiles(id) on delete cascade
);

-- 25. EQUIPES (Depende de cfg_departments)
CREATE TABLE IF NOT EXISTS public.cfg_teams (
    id bigint generated by default as identity not null,
    parent_id bigint null,
    code character varying not null,
    description character varying not null,
    department_id bigint not null,
    is_available boolean not null default true,
    img_url character varying null,
    users_total bigint not null default '0'::bigint,
    company_id bigint not null,
    created_user_id bigint null,
    created_at timestamp without time zone null,
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    version character varying null default 'live'::character varying,
    constraint teams_pkey primary key (id),
    constraint teams_department_fkey foreign key (department_id) references public.cfg_departments(id) on delete cascade
);

-- =============================================================================
-- NÍVEL 4: DEPENDEM DE MÚLTIPLOS NÍVEIS ANTERIORES
-- =============================================================================

-- 26. USUÁRIOS (Depende de: cfg_users_statuses, cfg_teams, cfg_companies, cfg_profiles)
CREATE TABLE IF NOT EXISTS public.users (
  id bigint generated by default as identity not null,
  email character varying not null,
  name_full character varying null,
  name_short character varying null,
  mobile character varying null,
  phone character varying null,
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone null,
  updated_user_id bigint null,
  team_id bigint null,
  is_team_leader boolean null default false,
  img_file_path character varying null default 'settings/images'::character varying,
  company_id bigint null,
  department_id bigint null,
  token_fcm character varying null,
  uuid uuid not null unique default auth.uid(),
  status_id smallint null,
  is_admin boolean null default false,
  is_admin_super boolean null default false,
  code character varying null,
  version_app character varying null,
  img_file_name character varying null default 'noImageUser.png'::character varying,
  team_id_previous bigint null,
  ov_in_progress_leader_id bigint null,
  profile_id bigint null,
  vehicle_id bigint null,
  is_available boolean null default true,
  is_ov_in_progress boolean null default false,
  team_amount smallint null default '1'::smallint,
  version_offline_user character varying null,
  version_offline_app character varying null,
  o_contract_id_in_progress bigint null,
  o_type_id_in_progress bigint null,
  o_type_sub_id_in_progress bigint null,
  o_plan_id_in_progress bigint null,
  o_asset_tag_id_in_progress bigint null,
  o_unit_id_in_progress bigint null,
  o_system_id_in_progress bigint null,
  o_system_parent_id_in_progress bigint null,
  o_unit_type_id_in_progress bigint null,
  o_unit_type_parent_id_in_progress bigint null,
  o_object_id_in_progress bigint null,
  ov_id_in_progress bigint null,
  o_id_in_progress bigint null,
  op_id_in_progress bigint null,
  notifications_amount integer null default 0,
  mobile_full text null,
  mobile_mask text null,
  mobile_whatsapp text null,
  migrated_at timestamp without time zone null,
  latitude double precision null,
  longitude double precision null,
  tracker_at timestamp without time zone null,
  ov_id_in_progress_mask character varying null,
  
  constraint users_pkey primary key (id),
  constraint users_status_id_fkey foreign KEY (status_id) references cfg_users_statuses (id) on delete CASCADE,
  constraint users_team_id_fkey foreign KEY (team_id) references cfg_teams (id) on update CASCADE on delete CASCADE,
  constraint users_company_id_fkey foreign KEY (company_id) references cfg_companies (id) on delete SET NULL,
  constraint users_profile_id_fkey foreign KEY (profile_id) references cfg_profiles (id) on delete SET NULL
);

-- 27. CONTRATOS (Depende de: cfg_companies, cfg_departments, clients, cfg_contracts_statuses)
CREATE TABLE IF NOT EXISTS public.contracts (
  id bigint generated by default as identity not null,
  client_company_id bigint null,
  client_department_id bigint null,
  provider_company_id bigint null,
  provider_department_id bigint null,
  description text null,
  is_available boolean null default true,
  is_deleted boolean null default false,
  code character varying null,
  status_id bigint null default 1,
  created_user_id bigint null,
  created_date timestamp without time zone null default now(),
  updated_user_id bigint null,
  updated_date timestamp without time zone null,
  deleted_user_id bigint null,
  deleted_date timestamp without time zone null,
  is_dev boolean null default false,
  version character varying null default 'live'::character varying,
  default_ov_asset_id bigint null,
  default_activity_id bigint null,
  date_start timestamp without time zone null,
  date_end timestamp without time zone null,
  total_value double precision null,
  client_id bigint null,
  constraint contracts_pkey primary key (id),
  constraint contracts_client_company_fkey foreign key (client_company_id) references public.cfg_companies(id) on delete set null,
  constraint contracts_client_department_fkey foreign key (client_department_id) references public.cfg_departments(id) on delete set null,
  constraint contracts_provider_company_fkey foreign key (provider_company_id) references public.cfg_companies(id) on delete set null,
  constraint contracts_provider_department_fkey foreign key (provider_department_id) references public.cfg_departments(id) on delete set null,
  constraint contracts_unit_client_fkey foreign key (client_id) references public.clients(id) on delete set null,
  constraint contracts_status_fkey foreign key (status_id) references public.cfg_contracts_statuses(id) on delete set null
) TABLESPACE pg_default;

-- 28. GERENTES DE CONTRATOS (Depende de: contracts, users)
CREATE TABLE IF NOT EXISTS public.contracts_managers (
  id bigint generated by default as identity not null,
  contract_id bigint not null,
  manager_id bigint not null,
  created_user_id bigint null,
  created_at timestamp without time zone null default now(),
  constraint contracts_managers_pkey primary key (id),
  constraint contracts_managers_contract_fkey foreign key (contract_id) references public.contracts(id) on delete cascade,
  constraint contracts_managers_manager_fkey foreign key (manager_id) references public.users(id) on delete cascade,
  constraint contracts_managers_unique unique (contract_id, manager_id)
);

-- 29. UNIDADES (Depende de: clients, cfg_companies, cfg_systems, cfg_units_types, cfg_units_statuses)
CREATE TABLE IF NOT EXISTS public.units (
  id bigint generated by default as identity not null,
  client_id bigint null,
  code character varying null,
  company_id bigint null,
  system_parent_id bigint null,
  system_id bigint null,
  unit_type_parent_id bigint null,
  unit_type_id bigint null,
  status_id bigint null,
  description character varying null,
  description_full character varying null,
  street_name character varying null,
  street_number bigint null,
  street_complement character varying null,
  address_full character varying null,
  latitude double precision null,
  longitude double precision null,
  version_mode character varying null default 'live'::character varying,
  created_at timestamp without time zone not null default now(),
  created_user_id bigint null,
  updated_at timestamp without time zone null,
  updated_user_id bigint null,
  deleted_at timestamp without time zone null,
  deleted_user_id bigint null,
  is_available boolean null default true,
  provider_company_id bigint null,
  code_sufix character varying null,
  is_deleted boolean null default false,
  coordinates character varying null,
  installation_code_power_supply character varying null,
  img_file_path text null,
  img_file_name text null,
  constraint units_pkey primary key (id),
  constraint units_client_fkey foreign key (client_id) references public.clients(id) on delete cascade,
  constraint units_company_fkey foreign key (company_id) references public.cfg_companies(id) on delete set null,
  constraint units_provider_company_fkey foreign key (provider_company_id) references public.cfg_companies(id) on delete set null,
  constraint units_system_fkey foreign key (system_parent_id) references public.cfg_systems(id) on delete set null,
  constraint units_sub_system_fkey foreign key (system_id) references public.cfg_systems(id) on delete set null,
  constraint units_type_fkey foreign key (unit_type_parent_id) references public.cfg_units_types(id) on delete set null,
  constraint units_sub_type_fkey foreign key (unit_type_id) references public.cfg_units_types(id) on update cascade on delete set null,
  constraint units_status_fkey foreign key (status_id) references public.cfg_units_statuses(id) on delete set null
) TABLESPACE pg_default;

-- =============================================================================
-- NÍVEL 5: DEPENDEM DE NÍVEL 4
-- =============================================================================

-- 31. ATIVOS (Depende de: units, cfg_assets_types, cfg_companies)
CREATE TABLE IF NOT EXISTS public.assets (
  id bigint generated by default as identity not null,
  company_id bigint null,
  unit_id bigint null,
  code character varying null,
  description text null,
  status_id bigint null,
  tag_id bigint null,
  tag_sub_id bigint null,
  status_at timestamp without time zone null,
  type_id bigint null,
  searchable text null,
  comments text null,
  brand character varying null,
  model character varying null,
  serial character varying null,
  power numeric null,
  power_unit character varying null,
  voltage character varying null,
  amperage character varying null,
  poles smallint null,
  voltage_unit character varying null,
  amperage_unit character varying null,
  poles_unit character varying null,
  rotation integer null,
  rotation_unit character varying null,
  service_factor numeric null default '1'::numeric,
  pressure_max numeric null,
  pressure_min numeric null,
  pressure_operation numeric null,
  pressure_unit character varying null,
  flow_rate_max numeric null,
  flow_rate_min numeric null,
  flow_rate_operation numeric null,
  flow_rate_unit character varying null,
  rotor_diameter numeric null,
  rotor_diameter_unit character varying null,
  priority_id smallint null default '3'::smallint,
  material_id bigint null,
  material_code character varying null,
  acquisition_at timestamp without time zone null,
  location character varying null,
  weight numeric null,
  weight_unit character varying null,
  created_user_id bigint not null default '1'::bigint,
  created_at timestamp without time zone null default now(),
  updated_user_id bigint null,
  updated_at timestamp without time zone null,
  is_deleted boolean null default false,
  deleted_user_id bigint null,
  deleted_at timestamp without time zone null,
  coupling_model_id smallint null,
  acquisition_value numeric null default '0'::numeric,
  version_mode character varying null default 'live'::character varying,
  img_file_path character varying null,
  img_file_name character varying null,
  unit_asset_tag_id bigint null,
  company_owner_id bigint null default '1'::bigint,
  img_file_name_thumb character varying null,
  client_id bigint null,
  constraint assets_pkey primary key (id),
  constraint assets_unit_id_fkey foreign KEY (unit_id) references units (id) on delete set null,
  constraint assets_type_id_fkey foreign KEY (type_id) references cfg_assets_types (id) on delete set null,
  constraint assets_company_owner_id_fkey foreign KEY (company_owner_id) references cfg_companies (id) on delete set null,
  constraint assets_company_id_fkey foreign KEY (company_id) references cfg_companies (id) on update CASCADE on delete set null,
  constraint assets_client_id_fkey foreign KEY (client_id) references clients (id) on delete set null
) TABLESPACE pg_default;

-- 32. VALORES DE ATRIBUTOS DE ATIVOS (Depende de: assets, cfg_assets_attributes)
CREATE TABLE IF NOT EXISTS public.assets_attributes_values (
    id bigint generated by default as identity not null,
    asset_id bigint not null references public.assets(id) on delete cascade,
    attribute_id bigint not null references public.cfg_assets_attributes(id) on delete cascade,
    value text null,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    constraint assets_attributes_values_pkey primary key (id),
    constraint assets_attributes_values_unique unique (asset_id, attribute_id)
);

-- 33. NOTIFICAÇÕES DE USUÁRIOS (Depende de: users)
CREATE TABLE IF NOT EXISTS public.users_notifications (
  id bigint generated always as identity primary key,
  user_id_to bigint references public.users(id) on delete cascade not null,
  user_id_from bigint references public.users(id) on delete set null,
  title text not null,
  body text not null,
  type text not null,
  is_read boolean default false,
  created_at timestamp with time zone default now() not null,
  read_at timestamp with time zone,
  unit_id bigint,
  img_url text,
  o_id bigint,
  v_id bigint,
  activity_id bigint,
  company_id bigint,
  token_fcm text,
  img_file_path text,
  img_file_name text,
  user_from_name_short text,
  page_target text,
  version_mode text,
  user_to_whatsapp text
);

-- =============================================================================
-- STORAGE (Bucket siges)
-- =============================================================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('siges', 'siges', true)
ON CONFLICT (id) DO NOTHING;

-- =============================================================================
-- FUNCTIONS & TRIGGERS
-- =============================================================================

CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Update Triggers
DO $$ 
DECLARE
    t text;
BEGIN
    FOR t IN 
        SELECT table_name 
        FROM information_schema.columns 
        WHERE column_name = 'updated_at' 
        AND table_schema = 'public'
    LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS on_%I_updated ON public.%I', t, t);
        EXECUTE format('CREATE TRIGGER on_%I_updated BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at()', t, t);
    END LOOP;
END $$;

-- Auth Sync
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (uuid, email, name_full, status_id, created_at)
  VALUES (
    NEW.id, 
    NEW.email, 
    NEW.raw_user_meta_data->>'name',
    2, 
    now()
  )
  ON CONFLICT (uuid) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Notifications Count
CREATE OR REPLACE FUNCTION public.handle_notifications_count()
RETURNS trigger AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    IF (NEW.is_read = false) THEN
      UPDATE public.users SET notifications_amount = COALESCE(notifications_amount, 0) + 1 WHERE id = NEW.user_id_to;
    END IF;
  ELSIF (TG_OP = 'UPDATE') THEN
    IF (OLD.is_read = false AND NEW.is_read = true) THEN
      UPDATE public.users SET notifications_amount = GREATEST(COALESCE(notifications_amount, 0) - 1, 0) WHERE id = NEW.user_id_to;
    ELSIF (OLD.is_read = true AND NEW.is_read = false) THEN
      UPDATE public.users SET notifications_amount = COALESCE(notifications_amount, 0) + 1 WHERE id = NEW.user_id_to;
    END IF;
  ELSIF (TG_OP = 'DELETE') THEN
    IF (OLD.is_read = false) THEN
      UPDATE public.users SET notifications_amount = GREATEST(COALESCE(notifications_amount, 0) - 1, 0) WHERE id = OLD.user_id_to;
    END IF;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_notifications_count ON public.users_notifications;
CREATE TRIGGER on_notifications_count
  AFTER INSERT OR UPDATE OR DELETE ON public.users_notifications
  FOR EACH ROW EXECUTE PROCEDURE public.handle_notifications_count();

-- Profile Photo Notification
CREATE OR REPLACE FUNCTION public.handle_profile_photo_change_notification()
RETURNS trigger AS $$
BEGIN
  IF (OLD.img_file_name IS DISTINCT FROM NEW.img_file_name) AND (NEW.img_file_name IS NOT NULL) THEN
    INSERT INTO public.users_notifications (user_id_to, user_id_from, title, body, type)
    SELECT u.id, NEW.id, 'Foto de perfil atualizada', 'Usuário ' || COALESCE(NEW.name_full, 'Desconhecido') || ' atualizou a foto de perfil', 'profile_photo_change'
    FROM public.users u WHERE u.is_admin_super = true;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_profile_photo_change ON public.users;
CREATE TRIGGER on_profile_photo_change
  AFTER UPDATE OF img_file_name ON public.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_profile_photo_change_notification();

-- Unit Description Full Autocomplete
CREATE OR REPLACE FUNCTION public.handle_unit_description_full()
RETURNS TRIGGER AS $$
DECLARE
    subtype_code text := '';
BEGIN
    -- Search for subtype code if unit_type_id exists
    IF NEW.unit_type_id IS NOT NULL THEN
        SELECT code INTO subtype_code 
        FROM public.cfg_units_types 
        WHERE id = NEW.unit_type_id;
    END IF;

    -- Format: "CODE - SUBTYPE_CODE DESCRIPTION"
    NEW.description_full := 
        COALESCE(NEW.code, '') || 
        CASE WHEN length(NEW.code) > 0 THEN ' - ' ELSE '' END ||
        CASE WHEN length(subtype_code) > 0 THEN subtype_code || ' ' ELSE '' END ||
        COALESCE(NEW.description, '');
        
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_unit_description_update ON public.units;
CREATE TRIGGER on_unit_description_update
  BEFORE INSERT OR UPDATE OF code, description, unit_type_id ON public.units
  FOR EACH ROW EXECUTE PROCEDURE public.handle_unit_description_full();


-- 34. ROTAS DO SISTEMA
CREATE TABLE IF NOT EXISTS public.cfg_routes (
    id bigint generated by default as identity not null,
    route_key character varying not null unique,
    route_path character varying not null,
    description character varying not null,
    icon character varying null,
    parent_id bigint null,
    order_index integer null default 0,
    is_available boolean null default true,
    created_at timestamp without time zone null default now(),
    updated_at timestamp without time zone null,
    constraint routes_pkey primary key (id),
    constraint routes_parent_fkey foreign key (parent_id) 
        references public.cfg_routes(id) on delete set null
);

CREATE INDEX IF NOT EXISTS idx_routes_route_key ON public.cfg_routes(route_key);

-- Seed Rows
INSERT INTO public.cfg_routes (route_key, route_path, description, icon, order_index)
VALUES 
    ('dashboard', '/dashboard', 'Dashboard', 'dashboard', 1),
    ('orders', '/orders', 'Ordens de Serviço', 'assignment', 2),
    ('visits', '/visits', 'Visitas', 'event', 3),
    ('users', '/users', 'Usuários', 'people', 4),
    ('settings', '/settings', 'Configurações', 'settings', 5),
    ('contracts', '/contracts', 'Contratos', 'description', 6),
    ('assets', '/assets', 'Ativos', 'inventory_2', 7),
    ('units', '/units', 'Unidades', 'location_on', 8),
    ('clients', '/clients', 'Clientes', 'business', 9),
    ('teams', '/teams', 'Equipes', 'groups', 10),
    ('departments', '/departments', 'Departamentos', 'corporate_fare', 11),
    ('notifications', '/notifications', 'Notificações', 'notifications', 12),
    ('materials', '/materials', 'Materiais', 'inventory', 13),
    ('vehicles', '/vehicles', 'Veículos', 'directions_car', 14),
    ('order-requests', '/order-requests', 'Solicitações de Ordem', 'request_quote', 15),
    ('reports', '/reports', 'Relatórios', 'assessment', 16)
ON CONFLICT (route_key) DO NOTHING;

-- 35. ACESSOS DE PERFIS (Matriz Permissões)
CREATE TABLE IF NOT EXISTS public.cfg_profiles_access (
    id bigint generated by default as identity not null,
    profile_id bigint not null,
    route_id bigint not null,
    can_view boolean not null default false,
    can_create boolean not null default false,
    can_edit boolean not null default false,
    can_delete boolean not null default false,
    created_at timestamp without time zone default now(),
    updated_at timestamp without time zone null,
    created_user_id bigint null,
    updated_user_id bigint null,
    constraint profiles_access_pkey primary key (id),
    constraint profiles_access_profile_fkey foreign key (profile_id) references public.cfg_profiles(id) on delete cascade,
    constraint profiles_access_route_fkey foreign key (route_id) references public.cfg_routes(id) on delete cascade,
    constraint profiles_access_unique unique (profile_id, route_id)
);

CREATE INDEX IF NOT EXISTS idx_profiles_access_profile_id ON public.cfg_profiles_access(profile_id);

-- 36. FUNÇÕES DE PERMISSÃO (RPC) - Atualizado 2026-01-25

CREATE OR REPLACE FUNCTION public.fc_get_user_permissions(p_user_id bigint)
RETURNS TABLE (
    route_id bigint,
    route_key varchar,
    route_path varchar,
    route_description varchar,
    route_icon varchar,
    can_view boolean,
    can_create boolean,
    can_edit boolean,
    can_delete boolean
) 
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        r.id as route_id,
        r.route_key,
        r.route_path,
        r.description as route_description,
        r.icon as route_icon,
        pa.can_view,
        pa.can_create,
        pa.can_edit,
        pa.can_delete
    FROM public.users u
    INNER JOIN public.cfg_profiles p ON u.profile_id = p.id
    INNER JOIN public.cfg_profiles_access pa ON p.id = pa.profile_id
    INNER JOIN public.cfg_routes r ON pa.route_id = r.id
    WHERE u.id = p_user_id
      AND r.is_available = true
    ORDER BY r.order_index;
END;
$$;

CREATE OR REPLACE FUNCTION public.fc_get_profile_permissions(p_profile_id bigint)
RETURNS TABLE (
    permission_id bigint,
    route_id bigint,
    route_key varchar,
    route_path varchar,
    route_description varchar,
    can_view boolean,
    can_create boolean,
    can_edit boolean,
    can_delete boolean
) 
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        pa.id as permission_id,
        r.id as route_id,
        r.route_key,
        r.route_path,
        r.description as route_description,
        pa.can_view,
        pa.can_create,
        pa.can_edit,
        pa.can_delete
    FROM public.cfg_profiles_access pa
    INNER JOIN public.cfg_routes r ON pa.route_id = r.id
    WHERE pa.profile_id = p_profile_id
      AND r.is_available = true
    ORDER BY r.order_index;
END;
$$;

CREATE OR REPLACE FUNCTION public.fc_update_profile_routes(
    p_profile_id bigint,
    p_routes jsonb -- [{ route_id, can_view, can_create, can_edit, can_delete }]
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- Delete existing permissions for this profile
    DELETE FROM public.cfg_profiles_access 
    WHERE profile_id = p_profile_id;
    
    -- Insert new permissions
    INSERT INTO public.cfg_profiles_access (
        profile_id, route_id, can_view, can_create, can_edit, can_delete
    )
    SELECT 
        p_profile_id,
        (route->>'route_id')::bigint,
        COALESCE((route->>'can_view')::boolean, false),
        COALESCE((route->>'can_create')::boolean, false),
        COALESCE((route->>'can_edit')::boolean, false),
        COALESCE((route->>'can_delete')::boolean, false)
    FROM jsonb_array_elements(p_routes) AS route
    WHERE (route->>'route_id') IS NOT NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.fc_check_user_permission(
    p_user_id bigint,
    p_route_key varchar,
    p_action varchar DEFAULT 'view' -- 'view', 'create', 'edit', 'delete'
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_has_permission boolean := false;
BEGIN
    -- Check if user is super admin (bypass permission check)
    SELECT is_admin_super INTO v_has_permission
    FROM public.users
    WHERE id = p_user_id;
    
    IF v_has_permission = true THEN
        RETURN true;
    END IF;
    
    -- Check specific permission
    SELECT 
        CASE p_action
            WHEN 'view' THEN pa.can_view
            WHEN 'create' THEN pa.can_create
            WHEN 'edit' THEN pa.can_edit
            WHEN 'delete' THEN pa.can_delete
            ELSE false
        END INTO v_has_permission
    FROM public.users u
    INNER JOIN public.cfg_profiles p ON u.profile_id = p.id
    INNER JOIN public.cfg_profiles_access pa ON p.id = pa.profile_id
    INNER JOIN public.cfg_routes r ON pa.route_id = r.id
    WHERE u.id = p_user_id
      AND r.route_key = p_route_key
      AND r.is_available = true
    LIMIT 1;
    
    RETURN COALESCE(v_has_permission, false);
END;
$$;

GRANT EXECUTE ON FUNCTION public.fc_get_user_permissions(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fc_get_profile_permissions(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fc_update_profile_routes(bigint, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fc_check_user_permission(bigint, varchar, varchar) TO authenticated;

-- =============================================================================
-- RLS POLICIES (Permissive for VPS)
-- =============================================================================

DO $$ 
DECLARE 
    t text;
BEGIN
    FOR t IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('DROP POLICY IF EXISTS "Permissive" ON public.%I', t);
        EXECUTE format('CREATE POLICY "Permissive" ON public.%I FOR ALL USING (true)', t);
    END LOOP;
END $$;

-- Storage Policies
DROP POLICY IF EXISTS "Siges Public Access" ON storage.objects;
CREATE POLICY "Siges Public Access" ON storage.objects FOR ALL USING (bucket_id = 'siges');

-- =============================================================================
-- REALTIME & RELOAD
-- =============================================================================

ALTER PUBLICATION supabase_realtime ADD TABLE public.users_notifications;
NOTIFY pgrst, 'reload schema';
