
-- =============================================================================
-- 25. ASSET TAGS (cfg_assets_tags) - Setores
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.cfg_assets_tags (
    id bigint generated by default as identity not null,
    code character varying not null,
    description character varying not null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint assets_tags_pkey primary key (id)
);

-- RLS Policies for cfg_assets_tags
ALTER TABLE public.cfg_assets_tags ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Asset tags viewable by everyone" ON public.cfg_assets_tags;
CREATE POLICY "Asset tags viewable by everyone" ON public.cfg_assets_tags FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Asset tags insertable by everyone" ON public.cfg_assets_tags;
CREATE POLICY "Asset tags insertable by everyone" ON public.cfg_assets_tags FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Asset tags updatable by everyone" ON public.cfg_assets_tags;
CREATE POLICY "Asset tags updatable by everyone" ON public.cfg_assets_tags FOR UPDATE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Asset tags deletable by everyone" ON public.cfg_assets_tags;
CREATE POLICY "Asset tags deletable by everyone" ON public.cfg_assets_tags FOR DELETE TO anon, authenticated USING (true);

-- Surgical fix: ensure necessary columns exist if table was created incorrectly
DO $$ 
BEGIN 
    -- Fix updated_at (Critical for the trigger)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='cfg_assets_tags' AND column_name='updated_at') THEN
        ALTER TABLE public.cfg_assets_tags ADD COLUMN updated_at timestamp without time zone;
    END IF;

    -- Fix created_at
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='cfg_assets_tags' AND column_name='created_at') THEN
        ALTER TABLE public.cfg_assets_tags ADD COLUMN created_at timestamp without time zone DEFAULT now();
    END IF;

    -- Fix code
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='cfg_assets_tags' AND column_name='code') THEN
        ALTER TABLE public.cfg_assets_tags ADD COLUMN code character varying;
    END IF;
END $$;

-- Trigger for updated_at
DROP TRIGGER IF EXISTS on_asset_tag_updated ON public.cfg_assets_tags;
DROP TRIGGER IF EXISTS on_unit_tag_updated ON public.cfg_assets_tags;
CREATE TRIGGER on_asset_tag_updated
  BEFORE UPDATE ON public.cfg_assets_tags
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- =============================================================================
-- 26. ASSET TAG SUBS (cfg_assets_tags_subs) - Posições
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.cfg_assets_tags_subs (
    id bigint generated by default as identity not null,
    parent_id bigint not null,
    code character varying not null,
    description character varying not null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint assets_tags_subs_pkey primary key (id),
    constraint assets_tags_subs_parent_fkey foreign key (parent_id) references public.cfg_assets_tags(id) on delete cascade
);

-- Surgical fix: ensure necessary columns exist if table was created incorrectly
DO $$ 
BEGIN 
    -- Fix parent_id
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='cfg_assets_tags_subs' AND column_name='parent_id') THEN
        ALTER TABLE public.cfg_assets_tags_subs ADD COLUMN parent_id bigint;
    END IF;
    
    -- Fix updated_at (Critical for the trigger)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='cfg_assets_tags_subs' AND column_name='updated_at') THEN
        ALTER TABLE public.cfg_assets_tags_subs ADD COLUMN updated_at timestamp without time zone;
    END IF;

    -- Fix created_at
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='cfg_assets_tags_subs' AND column_name='created_at') THEN
        ALTER TABLE public.cfg_assets_tags_subs ADD COLUMN created_at timestamp without time zone DEFAULT now();
    END IF;

    -- Fix code
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='cfg_assets_tags_subs' AND column_name='code') THEN
        ALTER TABLE public.cfg_assets_tags_subs ADD COLUMN code character varying;
    END IF;

    -- Ensure the constraint exists
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE table_name='cfg_assets_tags_subs' AND (constraint_name='assets_tags_subs_parent_fkey' OR constraint_name='units_tags_subs_parent_fkey')) THEN
        ALTER TABLE public.cfg_assets_tags_subs ADD CONSTRAINT assets_tags_subs_parent_fkey foreign key (parent_id) references public.cfg_assets_tags(id) on delete cascade;
    END IF;
END $$;

-- RLS Policies for cfg_assets_tags_subs
ALTER TABLE public.cfg_assets_tags_subs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Asset tag subs viewable by everyone" ON public.cfg_assets_tags_subs;
CREATE POLICY "Asset tag subs viewable by everyone" ON public.cfg_assets_tags_subs FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Asset tag subs insertable by everyone" ON public.cfg_assets_tags_subs;
CREATE POLICY "Asset tag subs insertable by everyone" ON public.cfg_assets_tags_subs FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Asset tag subs updatable by everyone" ON public.cfg_assets_tags_subs;
CREATE POLICY "Asset tag subs updatable by everyone" ON public.cfg_assets_tags_subs FOR UPDATE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Asset tag subs deletable by everyone" ON public.cfg_assets_tags_subs;
CREATE POLICY "Asset tag subs deletable by everyone" ON public.cfg_assets_tags_subs FOR DELETE TO anon, authenticated USING (true);

-- Trigger for updated_at
DROP TRIGGER IF EXISTS on_asset_tag_sub_updated ON public.cfg_assets_tags_subs;
DROP TRIGGER IF EXISTS on_unit_tag_sub_updated ON public.cfg_assets_tags_subs;
CREATE TRIGGER on_asset_tag_sub_updated
  BEFORE UPDATE ON public.cfg_assets_tags_subs
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- Reload PostgREST schema cache
NOTIFY pgrst, 'reload schema';
