
-- =============================================================================
-- 1. COMPANIES (cfg_companies)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.cfg_companies (
    id bigint generated by default as identity not null,
    code character varying null,
    description character varying null,
    img_file_path character varying null,
    img_file_name character varying null,
    is_available boolean null default true,
    email_sufix character varying null,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    version character varying null default 'live'::character varying,
    parent_id bigint null,
    constraint companies_pkey primary key (id)
);

-- =============================================================================
-- 2. DEPARTMENTS (cfg_departments)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.cfg_departments (
    id bigint generated by default as identity not null,
    company_id bigint not null,
    code character varying null,
    description character varying null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    version character varying null default 'live'::character varying,
    parent_id bigint null,
    constraint departments_pkey primary key (id),
    constraint departments_company_fkey foreign key (company_id) references public.cfg_companies(id) on delete cascade,
    constraint departments_parent_fkey foreign key (parent_id) references public.cfg_departments(id) on delete set null
);

-- =============================================================================
-- 3. TEAMS (cfg_teams)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.cfg_teams (
    id bigint generated by default as identity not null,
    parent_id bigint null,
    code character varying not null,
    description character varying not null,
    department_id bigint not null,
    is_available boolean not null default true,
    img_url character varying null,
    users_total bigint not null default '0'::bigint,
    company_id bigint not null,
    created_user_id bigint null,
    created_at timestamp without time zone null,
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    version character varying null default 'live'::character varying,
    constraint teams_pkey primary key (id),
    constraint teams_department_fkey foreign key (department_id) references public.cfg_departments(id) on delete cascade
);

-- =============================================================================
-- 4. USER STATUSES (cfg_users_statuses)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.cfg_users_statuses (
  id bigint generated by default as identity not null,
  code character varying null,
  description character varying null,
  constraint usersstatuses_pkey primary key (id)
);

INSERT INTO public.cfg_users_statuses (id, code, description)
VALUES 
    (1, 'ANA', 'Analise'), 
    (2, 'ATI', 'Ativo'), 
    (3, 'INA', 'Inativo')
ON CONFLICT (id) DO NOTHING;

-- =============================================================================
-- 5. PROFILES (cfg_profiles)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.cfg_profiles (
    id bigint generated by default as identity not null,
    description character varying null,
    department_id bigint null,
    version character varying null default 'live'::character varying,
    constraint usersprofiles_pkey primary key (id),
    constraint public_usersprofiles_departmentid_fkey foreign KEY (department_id) references cfg_departments (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

-- =============================================================================
-- 6. PERMISSIONS (cfg_profiles_permissions)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.cfg_profiles_permissions (
    id bigint generated by default as identity not null,
    profile_id bigint not null,
    resource character varying not null,
    can_view boolean not null default false,
    can_create boolean not null default false,
    can_edit boolean not null default false,
    can_delete boolean not null default false,
    created_at timestamp without time zone default now(),
    constraint profiles_permissions_pkey primary key (id),
    constraint profiles_permissions_profile_fkey foreign key (profile_id) references public.cfg_profiles(id) on delete cascade
);

-- =============================================================================
-- 7. USERS (users)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.users (
  id bigint generated by default as identity not null,
  email character varying not null,
  name_full character varying null,
  name_short character varying null,
  mobile character varying null,
  phone character varying null,
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone null,
  updated_user_id bigint null,
  team_id bigint null,
  is_team_leader boolean null default false,
  img_file_path character varying null default 'settings/images'::character varying,
  company_id bigint null,
  department_id bigint null,
  token_fcm character varying null,
  uuid uuid not null unique default auth.uid(),
  status_id smallint null,
  is_admin boolean null default false,
  is_admin_super boolean null default false,
  code character varying null,
  version_app character varying null,
  img_file_name character varying null default 'noImageUser.png'::character varying,
  team_id_previous bigint null,
  ov_in_progress_leader_id bigint null,
  profile_id bigint null,
  vehicle_id bigint null,
  is_available boolean null default true,
  is_ov_in_progress boolean null default false,
  team_amount smallint null default '1'::smallint,
  version_offline_user character varying null,
  version_offline_app character varying null,
  o_contract_id_in_progress bigint null,
  o_type_id_in_progress bigint null,
  o_type_sub_id_in_progress bigint null,
  o_plan_id_in_progress bigint null,
  o_asset_tag_id_in_progress bigint null,
  o_unit_id_in_progress bigint null,
  o_system_id_in_progress bigint null,
  o_system_parent_id_in_progress bigint null,
  o_unit_type_id_in_progress bigint null,
  o_unit_type_parent_id_in_progress bigint null,
  o_object_id_in_progress bigint null,
  ov_id_in_progress bigint null,
  o_id_in_progress bigint null,
  op_id_in_progress bigint null,
  notifications_amount integer null default 0,
  mobile_full text null,
  mobile_mask text null,
  mobile_whatsapp text null,
  migrated_at timestamp without time zone null,
  latitude double precision null,
  longitude double precision null,
  tracker_at timestamp without time zone null,
  ov_id_in_progress_mask character varying null,
  
  constraint users_pkey primary key (id),
  constraint users_status_id_fkey foreign KEY (status_id) references cfg_users_statuses (id) on delete CASCADE,
  constraint users_team_id_fkey foreign KEY (team_id) references cfg_teams (id) on update CASCADE on delete CASCADE,
  constraint users_company_id_fkey foreign KEY (company_id) references cfg_companies (id) on delete SET NULL,
  constraint users_profile_id_fkey foreign KEY (profile_id) references cfg_profiles (id) on delete SET NULL
);

-- =============================================================================
-- 8. CONTRACT STATUSES (cfg_contracts_statuses)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.cfg_contracts_statuses (
    id bigint generated by default as identity not null,
    code character varying null,
    description character varying null,
    color character varying null default '#3b82f6',
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint contracts_statuses_pkey primary key (id)
);

INSERT INTO public.cfg_contracts_statuses (id, code, description, color)
VALUES 
    (1, 'ATI', 'Ativo', '#22c55e'), 
    (2, 'VNC', 'Vencido', '#ef4444'), 
    (3, 'SUS', 'Suspenso', '#f59e0b'),
    (4, 'RASC', 'Rascunho', '#94a3b8')
ON CONFLICT (id) DO NOTHING;

-- =============================================================================
-- 9. CONTRACTS (contracts)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.contracts (
  id bigint generated by default as identity not null,
  client_company_id bigint null,
  client_department_id bigint null,
  provider_company_id bigint null,
  provider_department_id bigint null,
  description text null,
  is_available boolean null default true,
  is_deleted boolean null default false,
  code character varying null,
  status_id bigint null default 1,
  created_user_id bigint null,
  created_date timestamp without time zone null default now(),
  updated_user_id bigint null,
  updated_date timestamp without time zone null,
  deleted_user_id bigint null,
  deleted_date timestamp without time zone null,
  is_dev boolean null default false,
  version character varying null default 'live'::character varying,
  default_ov_asset_id bigint null,
  default_activity_id bigint null,
  date_start timestamp without time zone null,
  date_end timestamp without time zone null,
  total_value double precision null,
  client_id bigint null,
  constraint contracts_pkey primary key (id),
  constraint contracts_client_company_fkey foreign key (client_company_id) references public.cfg_companies(id) on delete set null,
  constraint contracts_client_department_fkey foreign key (client_department_id) references public.cfg_departments(id) on delete set null,
  constraint contracts_provider_company_fkey foreign key (provider_company_id) references public.cfg_companies(id) on delete set null,
  constraint contracts_provider_department_fkey foreign key (provider_department_id) references public.cfg_departments(id) on delete set null,
  constraint contracts_unit_client_fkey foreign key (client_id) references public.clients(id) on delete set null,
  constraint contracts_status_fkey foreign key (status_id) references public.cfg_contracts_statuses(id) on delete set null
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.contracts_managers (
  id bigint generated by default as identity not null,
  contract_id bigint not null,
  manager_id bigint not null,
  created_user_id bigint null,
  created_at timestamp without time zone null default now(),
  constraint contracts_managers_pkey primary key (id),
  constraint contracts_managers_contract_fkey foreign key (contract_id) references public.contracts(id) on delete cascade,
  constraint contracts_managers_manager_fkey foreign key (manager_id) references public.users(id) on delete cascade,
  constraint contracts_managers_unique unique (contract_id, manager_id)
);

-- =============================================================================
-- 9. CLIENTS (clients)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.clients (
    id bigint generated by default as identity not null,
    name character varying not null,
    code character varying not null,
    email character varying null,
    mobile character varying null,
    address character varying null,
    img_file_path character varying null,
    img_file_name character varying null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone not null default now(),
    updated_at timestamp without time zone null,
    updated_user_id bigint null,
    deleted_at timestamp without time zone null,
    deleted_user_id bigint null,
    is_deleted boolean null default false,
    constraint clients_pkey primary key (id)
);

-- =============================================================================
-- 10. LOCAL HIERARCHY (Systems, Unit Types, Units, Tags)
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.cfg_systems (
    id bigint generated by default as identity not null,
    parent_id bigint null,
    code character varying null,
    description character varying null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint systems_pkey primary key (id),
    constraint systems_parent_fkey foreign key (parent_id) references public.cfg_systems(id) on delete set null
);

CREATE TABLE IF NOT EXISTS public.cfg_units_types (
    id bigint generated by default as identity not null,
    parent_id bigint null,
    code character varying null,
    description character varying null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint units_types_pkey primary key (id),
    constraint units_types_parent_fkey foreign key (parent_id) references public.cfg_units_types(id) on delete set null
);

CREATE TABLE IF NOT EXISTS public.cfg_units_statuses (
    id bigint generated by default as identity not null,
    code character varying null,
    description character varying null,
    color character varying null default '#3b82f6',
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint units_statuses_pkey primary key (id)
);

INSERT INTO public.cfg_units_statuses (id, code, description, color)
VALUES 
    (1, 'ATI', 'Ativo', '#22c55e'), 
    (2, 'INA', 'Inativo', '#ef4444'), 
    (3, 'MAN', 'Manutenção', '#f59e0b')
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.units (
  id bigint generated by default as identity not null,
  client_id bigint null,
  code character varying null,
  company_id bigint null,
  system_parent_id bigint null,
  system_id bigint null,
  unit_type_parent_id bigint null,
  unit_type_id bigint null,
  status_id bigint null,
  description character varying null,
  description_full character varying null,
  street_name character varying null,
  street_number bigint null,
  street_complement character varying null,
  address_full character varying null,
  latitude double precision null,
  longitude double precision null,
  version_mode character varying null default 'live'::character varying,
  created_at timestamp without time zone not null default now(),
  created_user_id bigint null,
  updated_at timestamp without time zone null,
  updated_user_id bigint null,
  deleted_at timestamp without time zone null,
  deleted_user_id bigint null,
  is_available boolean null default true,
  provider_company_id bigint null,
  code_sufix character varying null,
  is_deleted boolean null default false,
  coordinates character varying null,
  installation_code_power_supply character varying null,
  img_file_path text null,
  img_file_name text null,
  constraint units_pkey primary key (id),
  constraint units_client_fkey foreign key (client_id) references public.clients(id) on delete cascade,
  constraint units_company_fkey foreign key (company_id) references public.cfg_companies(id) on delete set null,
  constraint units_provider_company_fkey foreign key (provider_company_id) references public.cfg_companies(id) on delete set null,
  constraint units_system_fkey foreign key (system_parent_id) references public.cfg_systems(id) on delete set null,
  constraint units_sub_system_fkey foreign key (system_id) references public.cfg_systems(id) on delete set null,
  constraint units_type_fkey foreign key (unit_type_parent_id) references public.cfg_units_types(id) on delete set null,
  constraint units_sub_type_fkey foreign key (unit_type_id) references public.cfg_units_types(id) on update cascade on delete set null,
  constraint units_status_fkey foreign key (status_id) references public.cfg_units_statuses(id) on delete set null
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.cfg_assets_tags (
    id bigint generated by default as identity not null,
    code character varying not null,
    description character varying not null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint assets_tags_pkey primary key (id)
);

CREATE TABLE IF NOT EXISTS public.cfg_assets_tags_subs (
    id bigint generated by default as identity not null,
    parent_id bigint null references public.cfg_assets_tags(id) on delete cascade,
    code character varying not null,
    description character varying not null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint assets_tags_subs_pkey primary key (id)
);

-- =============================================================================
-- 11. VEHICLES (vehicles)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.vehicles (
    id bigint generated by default as identity not null,
    company_id bigint not null,
    description character varying not null,
    plates character varying null,
    model character varying null,
    brand character varying null,
    color character varying null,
    year character varying null,
    is_available boolean null default true,
    created_at timestamp without time zone default now(),
    updated_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint vehicles_pkey primary key (id),
    constraint vehicles_company_fkey foreign key (company_id) references public.cfg_companies(id) on delete cascade
);

-- =============================================================================
-- 12. ACTIVITIES AND ORDER TYPES
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.cfg_activities (
    id bigint generated by default as identity not null,
    code character varying null,
    description character varying null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint activities_pkey primary key (id)
);

CREATE TABLE IF NOT EXISTS public.cfg_orders_priorities (
    id bigint generated by default as identity not null,
    code character varying not null,
    description character varying not null,
    color character varying not null default '#3b82f6',
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint orders_priorities_pkey primary key (id)
);

CREATE TABLE IF NOT EXISTS public.cfg_orders_types (
    id bigint generated by default as identity not null,
    parent_id bigint null,
    code character varying null,
    description character varying null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint orders_types_pkey primary key (id),
    constraint orders_types_parent_fkey foreign key (parent_id) references public.cfg_orders_types(id) on delete set null
);

CREATE TABLE IF NOT EXISTS public.cfg_orders_types_subs (
    id bigint generated by default as identity not null,
    order_type_id bigint null references public.cfg_orders_types(id) on delete cascade,
    parent_id bigint null references public.cfg_orders_types(id) on delete cascade,
    code character varying null,
    description character varying null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint orders_types_subs_pkey primary key (id)
);

CREATE TABLE IF NOT EXISTS public.cfg_orders_plans (
    id bigint generated by default as identity not null,
    code character varying not null,
    description character varying not null,
    color character varying null default '#3b82f6',
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint orders_plans_pkey primary key (id)
);

CREATE TABLE IF NOT EXISTS public.cfg_orders_objects (
    id bigint generated by default as identity not null,
    code character varying not null,
    description character varying not null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint orders_objects_pkey primary key (id)
);

CREATE TABLE IF NOT EXISTS public.cfg_orders_types_activities (
    id bigint generated by default as identity not null,
    order_type_id bigint not null references public.cfg_orders_types(id) on delete cascade,
    activity_id bigint not null references public.cfg_activities(id) on delete cascade,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint orders_types_activities_pkey primary key (id)
);

CREATE TABLE IF NOT EXISTS public.cfg_orders_types_subs_activities (
    id bigint generated by default as identity not null,
    order_type_sub_id bigint not null references public.cfg_orders_types_subs(id) on delete cascade,
    activity_id bigint not null references public.cfg_activities(id) on delete cascade,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint orders_types_subs_activities_pkey primary key (id)
);

-- =============================================================================
-- 13. ASSET MANAGEMENT
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.cfg_assets_types (
    id bigint generated by default as identity not null,
    code character varying not null,
    description character varying not null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint assets_types_pkey primary key (id)
);

CREATE TABLE IF NOT EXISTS public.cfg_assets_statuses (
    id bigint generated by default as identity not null,
    code character varying not null,
    description character varying not null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint assets_statuses_pkey primary key (id)
);

CREATE TABLE IF NOT EXISTS public.cfg_assets_priorities (
    id bigint generated by default as identity not null,
    code character varying not null,
    description character varying not null,
    color character varying not null default '#3b82f6',
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint assets_priorities_pkey primary key (id)
);

-- =============================================================================
-- 14. NOTIFICATIONS (users_notifications)
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.users_notifications (
  id bigint generated always as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null,
  title varchar(255) not null,
  message text not null,
  type varchar(50) not null,
  related_user_id bigint references public.users(id) on delete set null,
  is_read boolean default false,
  created_at timestamp with time zone default now() not null,
  read_at timestamp with time zone
);

-- =============================================================================
-- 15. STORAGE (siges bucket)
-- =============================================================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('siges', 'siges', true)
ON CONFLICT (id) DO NOTHING;

-- =============================================================================
-- 16. FUNCTIONS & TRIGGERS
-- =============================================================================

CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Update Triggers
DO $$ 
DECLARE
    t text;
BEGIN
    FOR t IN 
        SELECT table_name 
        FROM information_schema.columns 
        WHERE column_name = 'updated_at' 
        AND table_schema = 'public'
    LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS on_%I_updated ON public.%I', t, t);
        EXECUTE format('CREATE TRIGGER on_%I_updated BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at()', t, t);
    END LOOP;
END $$;

-- Auth Sync
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (uuid, email, name_full, status_id, created_at)
  VALUES (
    NEW.id, 
    NEW.email, 
    NEW.raw_user_meta_data->>'name',
    2, 
    now()
  )
  ON CONFLICT (uuid) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Notifications Count
CREATE OR REPLACE FUNCTION public.handle_notifications_count()
RETURNS trigger AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    IF (NEW.is_read = false) THEN
      UPDATE public.users SET notifications_amount = COALESCE(notifications_amount, 0) + 1 WHERE id = NEW.user_id;
    END IF;
  ELSIF (TG_OP = 'UPDATE') THEN
    IF (OLD.is_read = false AND NEW.is_read = true) THEN
      UPDATE public.users SET notifications_amount = GREATEST(COALESCE(notifications_amount, 0) - 1, 0) WHERE id = NEW.user_id;
    ELSIF (OLD.is_read = true AND NEW.is_read = false) THEN
      UPDATE public.users SET notifications_amount = COALESCE(notifications_amount, 0) + 1 WHERE id = NEW.user_id;
    END IF;
  ELSIF (TG_OP = 'DELETE') THEN
    IF (OLD.is_read = false) THEN
      UPDATE public.users SET notifications_amount = GREATEST(COALESCE(notifications_amount, 0) - 1, 0) WHERE id = OLD.user_id;
    END IF;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_notifications_count ON public.users_notifications;
CREATE TRIGGER on_notifications_count
  AFTER INSERT OR UPDATE OR DELETE ON public.users_notifications
  FOR EACH ROW EXECUTE PROCEDURE public.handle_notifications_count();

-- Profile Photo Notification
CREATE OR REPLACE FUNCTION public.handle_profile_photo_change_notification()
RETURNS trigger AS $$
BEGIN
  IF (OLD.img_file_name IS DISTINCT FROM NEW.img_file_name) AND (NEW.img_file_name IS NOT NULL) THEN
    INSERT INTO public.users_notifications (user_id, related_user_id, title, message, type)
    SELECT u.id, NEW.id, 'Foto de perfil atualizada', 'Usuário ' || COALESCE(NEW.name_full, 'Desconhecido') || ' atualizou a foto de perfil', 'profile_photo_change'
    FROM public.users u WHERE u.is_admin_super = true;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_profile_photo_change ON public.users;
CREATE TRIGGER on_profile_photo_change
  AFTER UPDATE OF img_file_name ON public.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_profile_photo_change_notification();

-- =============================================================================
-- 17. RLS POLICIES (Permissive for VPS)
-- =============================================================================

DO $$ 
DECLARE 
    t text;
BEGIN
    FOR t IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('DROP POLICY IF EXISTS "Permissive" ON public.%I', t);
        EXECUTE format('CREATE POLICY "Permissive" ON public.%I FOR ALL USING (true)', t);
    END LOOP;
END $$;

-- Storage Policies
DROP POLICY IF EXISTS "Siges Public Access" ON storage.objects;
CREATE POLICY "Siges Public Access" ON storage.objects FOR ALL USING (bucket_id = 'siges');

-- =============================================================================
-- 18. REALTIME & RELOAD
-- =============================================================================

ALTER PUBLICATION supabase_realtime ADD TABLE public.users_notifications;
NOTIFY pgrst, 'reload schema';
