-- Create Teams Table (cfg_teams)
CREATE TABLE public.cfg_teams (
    id bigint generated by default as identity not null,
    parent_id bigint null,
    code character varying not null,
    description character varying not null,
    department_id bigint not null,
    is_available boolean not null default true,
    img_url character varying null,
    users_total bigint not null default '0'::bigint,
    company_id bigint not null,
    created_user_id bigint null,
    created_at timestamp without time zone null,
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    version character varying null default 'live'::character varying,
    constraint teams_pkey primary key (id),
    constraint teams_department_fkey foreign key (department_id) references public.cfg_departments(id) on delete cascade,
    constraint teams_company_fkey foreign key (company_id) references public.cfg_companies(id) on delete cascade
);

-- Enable RLS
ALTER TABLE public.cfg_teams ENABLE ROW LEVEL SECURITY;

-- Policies for cfg_teams
CREATE POLICY "Public teams are viewable by everyone" 
ON public.cfg_teams FOR SELECT 
USING (true);

CREATE POLICY "Public teams are insertable by everyone" 
ON public.cfg_teams FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Public teams are updatable by everyone" 
ON public.cfg_teams FOR UPDATE 
USING (true);

CREATE POLICY "Public teams are deletable by everyone" 
ON public.cfg_teams FOR DELETE 
USING (true);
