-- =============================================================================
-- Table: v_assets_types
-- Exported: 2026-03-05T17:29:36.417Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.v_assets_types CASCADE;

CREATE TABLE IF NOT EXISTS public.v_assets_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company_id integer,
    code character varying(255),
    description character varying(255),
    is_available boolean DEFAULT false,
    PRIMARY KEY (id)
);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_v_assets_types_created_at ON public.v_assets_types(created_at);
-- CREATE INDEX idx_v_assets_types_user_id ON public.v_assets_types(user_id);

