-- =============================================================================
-- Table: orders
-- Exported: 2026-03-05T17:29:35.188Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.orders CASCADE;

CREATE TABLE IF NOT EXISTS public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp DEFAULT now()

);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_orders_created_at ON public.orders(created_at);
-- CREATE INDEX idx_orders_user_id ON public.orders(user_id);

