-- =============================================================================
-- Table: cfg_assets_tags_subs
-- Exported: 2026-03-05T17:29:34.605Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.cfg_assets_tags_subs CASCADE;

CREATE TABLE IF NOT EXISTS public.cfg_assets_tags_subs (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company_id integer,
    code character varying(255),
    description character varying(255),
    is_available boolean DEFAULT false,
    is_deleted boolean DEFAULT false,
    PRIMARY KEY (id)
);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_cfg_assets_tags_subs_created_at ON public.cfg_assets_tags_subs(created_at);
-- CREATE INDEX idx_cfg_assets_tags_subs_user_id ON public.cfg_assets_tags_subs(user_id);

