-- =============================================================================
-- Table: v_assets
-- Exported: 2026-03-05T17:29:35.917Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.v_assets CASCADE;

CREATE TABLE IF NOT EXISTS public.v_assets (
    company_id integer,
    company_description character varying(255),
    company_owner_description character varying(255),
    company_owner_id integer,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code character varying(255),
    description character varying(255),
    searchable character varying(255),
    tag_id integer,
    tag_description character varying(255),
    tag_sub_id integer,
    tag_sub_description character varying(255),
    unit_asset_tag_id integer,
    location character varying(255),
    unit_id integer,
    unit_code character varying(255),
    unit_description character varying(255),
    status_id integer,
    status_description character varying(255),
    status_code character varying(255),
    status_at timestamp without time zone DEFAULT now(),
    type_id integer,
    type_description character varying(255),
    priority_id integer,
    priority_code character varying(255),
    priority_description character varying(255),
    brand character varying(255),
    model character varying(255),
    serial character varying(255),
    power integer,
    power_unit character varying(255),
    voltage character varying(255),
    voltage_unit character varying(255),
    amperage character varying(255),
    amperage_unit character varying(255),
    poles integer,
    poles_unit character varying(255),
    rotation integer,
    rotation_unit character varying(255),
    service_factor integer,
    pressure_max text,
    pressure_min text,
    pressure_operation text,
    pressure_unit text,
    flow_rate_max text,
    flow_rate_min text,
    flow_rate_operation text,
    flow_rate_unit text,
    rotor_diameter text,
    rotor_diameter_unit text,
    weight integer,
    weight_unit character varying(255),
    coupling_model_id text,
    coupling_model_description text,
    comments character varying(255),
    acquisition_at timestamp without time zone DEFAULT now(),
    acquisition_value integer,
    img_file_path text,
    img_file_name text,
    img_file_name_thumb text,
    version_mode character varying(255),
    status_color character varying(255),
    PRIMARY KEY (id)
);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_v_assets_created_at ON public.v_assets(created_at);
-- CREATE INDEX idx_v_assets_user_id ON public.v_assets(user_id);

