-- =============================================================================
-- Table: assets
-- Exported: 2026-03-05T17:29:33.745Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.assets CASCADE;

CREATE TABLE IF NOT EXISTS public.assets (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp DEFAULT now()

);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_assets_created_at ON public.assets(created_at);
-- CREATE INDEX idx_assets_user_id ON public.assets(user_id);

