-- =============================================================================
-- Table: orders_visits
-- Exported: 2026-03-05T17:12:18.405Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.orders_visits CASCADE;

CREATE TABLE IF NOT EXISTS public.orders_visits (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp DEFAULT now()

);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_orders_visits_created_at ON public.orders_visits(created_at);
-- CREATE INDEX idx_orders_visits_user_id ON public.orders_visits(user_id);

