create table if not exists public.cfg_assets_tags_subs (
  id bigint generated by default as identity not null,
  parent_id bigint null,
  code character varying not null,
  description character varying not null,
  is_available boolean null default true,
  created_user_id bigint null,
  created_at timestamp without time zone null default now(),
  updated_user_id bigint null,
  updated_at timestamp without time zone null,
  deleted_user_id bigint null,
  deleted_at timestamp without time zone null,
  is_deleted boolean null default false,
  company_id bigint null,
  constraint assets_tags_subs_pkey primary key (id),
  constraint cfg_assets_tags_subs_parent_id_fkey foreign KEY (parent_id) references public.cfg_assets_tags (id) on delete CASCADE,
  constraint assets_tags_subs_company_id_fkey foreign key (company_id) references public.cfg_companies(id) on delete set null
) TABLESPACE pg_default;

-- Enable RLS
alter table public.cfg_assets_tags_subs enable row level security;

-- Policies
create policy "Public read access" on public.cfg_assets_tags_subs for select using (true);
create policy "Authenticated insert" on public.cfg_assets_tags_subs for insert with check (auth.role() = 'authenticated');
create policy "Authenticated update" on public.cfg_assets_tags_subs for update using (auth.role() = 'authenticated');
create policy "Authenticated delete" on public.cfg_assets_tags_subs for delete using (auth.role() = 'authenticated');
