-- Migration: Refactor Asset Attributes to Many-to-Many (FIXED DEDUPLICATION)
-- This script safely reorganizes the attributes structure.

-- 1. Create the junction table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.cfg_assets_types_attributes (
    id bigint generated by default as identity not null,
    asset_type_id bigint not null references public.cfg_assets_types(id) on delete cascade,
    attribute_id bigint not null references public.cfg_assets_attributes(id) on delete cascade,
    is_required boolean not null default false,
    order_index integer not null default 0,
    is_available boolean not null default true,
    created_at timestamp without time zone null default now(),
    constraint assets_types_attributes_pkey primary key (id),
    constraint assets_types_attributes_unique unique (asset_type_id, attribute_id)
);

-- 2. Migrate existing links to the junction table (before deduplication)
-- We use ON CONFLICT DO NOTHING in case this script is run multiple times
INSERT INTO public.cfg_assets_types_attributes (asset_type_id, attribute_id, is_required, order_index, is_available)
SELECT asset_type_id, id, is_required, order_index, is_available
FROM public.cfg_assets_attributes
WHERE asset_type_id IS NOT NULL
ON CONFLICT (asset_type_id, attribute_id) DO NOTHING;

-- 3. Deduplication Logic:
-- If we have multiple entries for the same field_key, we need to point the 
-- junction table to only ONE of them and delete the others.

DO $$
DECLARE
    attr_record RECORD;
    target_id bigint;
BEGIN
    -- For each field_key that has more than one occurrence
    FOR attr_record IN (
        SELECT field_key, MIN(id) as first_id
        FROM public.cfg_assets_attributes
        GROUP BY field_key
        HAVING COUNT(*) > 1
    ) LOOP
        -- Update all junction table references to point to the first_id
        UPDATE public.cfg_assets_types_attributes
        SET attribute_id = attr_record.first_id
        WHERE attribute_id IN (
            SELECT id FROM public.cfg_assets_attributes WHERE field_key = attr_record.field_key AND id != attr_record.first_id
        )
        ON CONFLICT (asset_type_id, attribute_id) DO NOTHING;

        -- Also update attribute values (very important!)
        UPDATE public.assets_attributes_values
        SET attribute_id = attr_record.first_id
        WHERE attribute_id IN (
            SELECT id FROM public.cfg_assets_attributes WHERE field_key = attr_record.field_key AND id != attr_record.first_id
        );

        -- Delete the duplicates from the base table
        DELETE FROM public.cfg_assets_attributes
        WHERE field_key = attr_record.field_key AND id != attr_record.first_id;
    END LOOP;
END $$;

-- 4. Clean up columns and add constraint
ALTER TABLE public.cfg_assets_attributes DROP CONSTRAINT IF EXISTS assets_attributes_type_field_key_unique;
ALTER TABLE public.cfg_assets_attributes DROP COLUMN IF EXISTS asset_type_id CASCADE;
ALTER TABLE public.cfg_assets_attributes DROP COLUMN IF EXISTS is_required CASCADE;
ALTER TABLE public.cfg_assets_attributes DROP COLUMN IF EXISTS order_index CASCADE;

-- Ensure no orphans in junction table (if any deletions happened above)
DELETE FROM public.cfg_assets_types_attributes WHERE attribute_id NOT IN (SELECT id FROM public.cfg_assets_attributes);

-- Add the unique constraint finally!
ALTER TABLE public.cfg_assets_attributes ADD CONSTRAINT assets_attributes_field_key_unique UNIQUE (field_key);

-- 5. Enable RLS and Grant permissions for the junction table
ALTER TABLE public.cfg_assets_types_attributes ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'cfg_assets_types_attributes' AND policyname = 'permissive'
    ) THEN
        CREATE POLICY permissive ON public.cfg_assets_types_attributes FOR ALL USING (true);
    END IF;
END $$;

GRANT ALL ON public.cfg_assets_types_attributes TO anon, authenticated, postgres, service_role;

NOTIFY pgrst, 'reload schema';
