
-- =============================================================================
-- 22. ASSET TYPES (cfg_assets_types)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.cfg_assets_types (
    id bigint generated by default as identity not null,
    code character varying not null,
    description character varying not null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint assets_types_pkey primary key (id)
);

-- RLS Policies for cfg_assets_types
ALTER TABLE public.cfg_assets_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Asset types viewable by everyone" ON public.cfg_assets_types FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Asset types insertable by everyone" ON public.cfg_assets_types FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Asset types updatable by everyone" ON public.cfg_assets_types FOR UPDATE TO anon, authenticated USING (true);
CREATE POLICY "Asset types deletable by everyone" ON public.cfg_assets_types FOR DELETE TO anon, authenticated USING (true);


-- =============================================================================
-- 23. ASSET STATUSES (cfg_assets_statuses)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.cfg_assets_statuses (
    id bigint generated by default as identity not null,
    code character varying not null,
    description character varying not null,
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint assets_statuses_pkey primary key (id)
);

-- RLS Policies for cfg_assets_statuses
ALTER TABLE public.cfg_assets_statuses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Asset statuses viewable by everyone" ON public.cfg_assets_statuses FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Asset statuses insertable by everyone" ON public.cfg_assets_statuses FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Asset statuses updatable by everyone" ON public.cfg_assets_statuses FOR UPDATE TO anon, authenticated USING (true);
CREATE POLICY "Asset statuses deletable by everyone" ON public.cfg_assets_statuses FOR DELETE TO anon, authenticated USING (true);

-- =============================================================================
-- 24. ASSET PRIORITIES (cfg_assets_priorities)
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.cfg_assets_priorities (
    id bigint generated by default as identity not null,
    code character varying not null,
    description character varying not null,
    color character varying not null default '#3b82f6',
    is_available boolean null default true,
    created_user_id bigint null,
    created_at timestamp without time zone null default now(),
    updated_user_id bigint null,
    updated_at timestamp without time zone null,
    deleted_user_id bigint null,
    deleted_at timestamp without time zone null,
    is_deleted boolean null default false,
    constraint assets_priorities_pkey primary key (id)
);

-- RLS Policies for cfg_assets_priorities
ALTER TABLE public.cfg_assets_priorities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Asset priorities viewable by everyone" ON public.cfg_assets_priorities FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Asset priorities insertable by everyone" ON public.cfg_assets_priorities FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Asset priorities updatable by everyone" ON public.cfg_assets_priorities FOR UPDATE TO anon, authenticated USING (true);
CREATE POLICY "Asset priorities deletable by everyone" ON public.cfg_assets_priorities FOR DELETE TO anon, authenticated USING (true);
