-- Create USERS STATUSES table
CREATE TABLE IF NOT EXISTS public.cfg_users_statuses (
  id bigint generated by default as identity not null,
  code character varying null,
  description character varying null,
  constraint usersstatuses_pkey primary key (id)
);

-- Insert default statuses
-- Insert default statuses
INSERT INTO public.cfg_users_statuses (id, code, description)
OVERRIDING SYSTEM VALUE
VALUES 
    (1,'ANA','Analise'), 
    (2,'ATI','Ativo'), 
    (3,'INA','Inativo')
ON CONFLICT DO NOTHING;

-- Create USERS table
-- 'id' is the internal application reference
-- 'auth_user_id' links to Supabase Auth
CREATE TABLE IF NOT EXISTS public.users (
  id bigint generated by default as identity not null,
  email character varying not null,
  name_full character varying null,
  name_short character varying null,
  mobile character varying null,
  phone character varying null,
  created_at timestamp without time zone not null,
  updated_at timestamp without time zone null,
  updated_user_id bigint null,
  team_id bigint null,
  is_team_leader boolean null default false,
  img_file_path character varying null default 'settings/images'::character varying,
  company_id bigint null,
  department_id bigint null,
  token_fcm character varying null,
  uuid uuid not null default auth.uid (),
  status_id smallint null,
  is_admin boolean null default false,
  is_admin_super boolean null default false,
  code character varying null,
  version_app character varying null,
  img_file_name character varying null default 'noImageUser.png'::character varying,
  team_id_previous bigint null,
  ov_in_progress_leader_id bigint null,
  profile_id bigint null,
  vehicle_id bigint null,
  is_available boolean null default true,
  is_ov_in_progress boolean null default false,
  team_amount smallint null default '1'::smallint,
  version_offline_user character varying null,
  version_offline_app character varying null,
  o_contract_id_in_progress bigint null,
  o_type_id_in_progress bigint null,
  o_type_sub_id_in_progress bigint null,
  o_plan_id_in_progress bigint null,
  o_asset_tag_id_in_progress bigint null,
  o_unit_id_in_progress bigint null,
  o_system_id_in_progress bigint null,
  o_system_parent_id_in_progress bigint null,
  o_unit_type_id_in_progress bigint null,
  o_unit_type_parent_id_in_progress bigint null,
  o_object_id_in_progress bigint null,
  ov_id_in_progress bigint null,
  o_id_in_progress bigint null,
  op_id_in_progress bigint null,
  notifications_amount integer null default 0,
  mobile_full text null,
  mobile_mask text null,
  mobile_whatsapp text null,
  migrated_at timestamp without time zone null,
  latitude double precision null,
  longitude double precision null,
  tracker_heartbeat_at timestamp without time zone null,
  tracker_accuracy double precision null,
  ov_id_in_progress_mask character varying null,
  constraint users_pkey primary key (id),
  constraint users_status_id_fkey foreign KEY (status_id) references cfg_users_statuses (id) on delete CASCADE,
  constraint users_team_id_fkey foreign KEY (team_id) references cfg_teams (id) on update CASCADE on delete CASCADE,
  constraint users_profile_id_fkey foreign KEY (profile_id) references cfg_profiles (id) on update CASCADE on delete SET NULL
);

-- Enable Row Level Security
ALTER TABLE public.cfg_users_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Policies for cfg_users_statuses
CREATE POLICY "Statuses are viewable by authenticated users" 
ON public.cfg_users_statuses FOR SELECT 
TO authenticated 
USING (true);

-- Policies for users
CREATE POLICY "Users are viewable by authenticated users" 
ON public.users FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "Users can update their own profile" 
ON public.users FOR UPDATE 
TO authenticated 
USING (auth.uid() = uuid);

-- Trigger to handle updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_user_updated
  BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- Trigger to automatically create a public user entry when a new auth user is created
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (uuid, email, name_full, status_id, created_at)
  VALUES (
    NEW.id, 
    NEW.email, 
    NEW.raw_user_meta_data->>'name',
    2, -- Default to Ativo
    now()
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger only if not exists (to avoid error on re-run)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
