-- =============================================================================
-- Table: materials
-- Exported: 2026-03-05T17:29:31.755Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.materials CASCADE;

CREATE TABLE IF NOT EXISTS public.materials (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp DEFAULT now()

);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_materials_created_at ON public.materials(created_at);
-- CREATE INDEX idx_materials_user_id ON public.materials(user_id);

