-- =============================================================================
-- Table: cfg_app
-- Description: Application version configuration table
-- =============================================================================

DROP TABLE IF EXISTS public.cfg_app CASCADE;

CREATE TABLE IF NOT EXISTS public.cfg_app (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    apk_url character varying NOT NULL,
    version_app character varying NOT NULL,
    logo_url character varying,
    version_app_offline character varying DEFAULT '1'::character varying,
    n8n_available_last_at timestamp without time zone,
    version_app_mask character varying,
    PRIMARY KEY (id)
);
