-- =============================================================================
-- Table: cfg_services
-- Exported: 2026-03-05T17:29:28.268Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.cfg_services CASCADE;

CREATE TABLE IF NOT EXISTS public.cfg_services (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp DEFAULT now()

);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_cfg_services_created_at ON public.cfg_services(created_at);
-- CREATE INDEX idx_cfg_services_user_id ON public.cfg_services(user_id);

