-- =============================================================================
-- Table: cfg_units_types
-- Exported: 2026-03-05T17:29:29.194Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.cfg_units_types CASCADE;

CREATE TABLE IF NOT EXISTS public.cfg_units_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp DEFAULT now()

);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_cfg_units_types_created_at ON public.cfg_units_types(created_at);
-- CREATE INDEX idx_cfg_units_types_user_id ON public.cfg_units_types(user_id);

