-- =============================================================================
-- Table: cfg_users_statuses
-- Exported: 2026-03-05T17:29:29.476Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.cfg_users_statuses CASCADE;

CREATE TABLE IF NOT EXISTS public.cfg_users_statuses (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp DEFAULT now()

);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_cfg_users_statuses_created_at ON public.cfg_users_statuses(created_at);
-- CREATE INDEX idx_cfg_users_statuses_user_id ON public.cfg_users_statuses(user_id);

