-- =============================================================================
-- Table: cfg_systems
-- Exported: 2026-03-05T17:29:28.557Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.cfg_systems CASCADE;

CREATE TABLE IF NOT EXISTS public.cfg_systems (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company_id integer,
    parent_id integer,
    code character varying(255),
    description character varying(255),
    is_available boolean DEFAULT false,
    is_deleted boolean DEFAULT false,
    created_user_id text,
    created_date timestamp without time zone DEFAULT now(),
    updated_user_id text,
    updated_date text,
    deleted_user_id text,
    deleted_date text,
    PRIMARY KEY (id)
);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_cfg_systems_created_at ON public.cfg_systems(created_at);
-- CREATE INDEX idx_cfg_systems_user_id ON public.cfg_systems(user_id);

