-- =============================================================================
-- Table: vehicles
-- Exported: 2026-03-05T17:29:33.364Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.vehicles CASCADE;

CREATE TABLE IF NOT EXISTS public.vehicles (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp DEFAULT now()

);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_vehicles_created_at ON public.vehicles(created_at);
-- CREATE INDEX idx_vehicles_user_id ON public.vehicles(user_id);

