-- =============================================================================
-- Table: cfg_activities
-- Exported: 2026-03-05T17:29:27.277Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.cfg_activities CASCADE;

CREATE TABLE IF NOT EXISTS public.cfg_activities (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company_id integer,
    department_id integer,
    description character varying(255),
    is_available boolean DEFAULT false,
    is_deleted boolean DEFAULT false,
    code text,
    PRIMARY KEY (id)
);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_cfg_activities_created_at ON public.cfg_activities(created_at);
-- CREATE INDEX idx_cfg_activities_user_id ON public.cfg_activities(user_id);

