-- =============================================================================
-- Table: cfg_departments
-- Exported: 2026-03-05T17:29:27.901Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.cfg_departments CASCADE;

CREATE TABLE IF NOT EXISTS public.cfg_departments (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code character varying(255),
    description character varying(255),
    parent_id text,
    company_id integer,
    is_available boolean DEFAULT false,
    created_user_id text,
    created_at timestamp without time zone DEFAULT now(),
    updated_user_id text,
    updated_at text,
    deleted_user_id text,
    deleted_at text,
    is_deleted boolean DEFAULT false,
    version character varying(255),
    PRIMARY KEY (id)
);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_cfg_departments_created_at ON public.cfg_departments(created_at);
-- CREATE INDEX idx_cfg_departments_user_id ON public.cfg_departments(user_id);

