-- =============================================================================
-- Table: documents
-- Exported: 2026-03-05T17:29:31.133Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.documents CASCADE;

CREATE TABLE IF NOT EXISTS public.documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp DEFAULT now()

);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_documents_created_at ON public.documents(created_at);
-- CREATE INDEX idx_documents_user_id ON public.documents(user_id);

