-- =============================================================================
-- Table: contracts_managers
-- Exported: 2026-03-05T17:29:30.795Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.contracts_managers CASCADE;

CREATE TABLE IF NOT EXISTS public.contracts_managers (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contract_id integer,
    manager_id integer,
    is_deleted boolean DEFAULT false,
    version_mode character varying(255),
    created_user_id text,
    created_at text,
    deleted_user_id text,
    deleted_at text,
    role character varying(255),
    PRIMARY KEY (id)
);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_contracts_managers_created_at ON public.contracts_managers(created_at);
-- CREATE INDEX idx_contracts_managers_user_id ON public.contracts_managers(user_id);

