-- =============================================================================
-- Table: cfg_assets_tags
-- Exported: 2026-03-05T17:29:34.300Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.cfg_assets_tags CASCADE;

CREATE TABLE IF NOT EXISTS public.cfg_assets_tags (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp DEFAULT now()

);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_cfg_assets_tags_created_at ON public.cfg_assets_tags(created_at);
-- CREATE INDEX idx_cfg_assets_tags_user_id ON public.cfg_assets_tags(user_id);

