-- =============================================================================
-- Table: v_orders_types
-- Exported: 2026-03-05T17:29:37.514Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.v_orders_types CASCADE;

CREATE TABLE IF NOT EXISTS public.v_orders_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    department_id integer,
    code character varying(255),
    description character varying(255),
    is_deleted boolean DEFAULT false,
    is_available boolean DEFAULT false,
    PRIMARY KEY (id)
);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_v_orders_types_created_at ON public.v_orders_types(created_at);
-- CREATE INDEX idx_v_orders_types_user_id ON public.v_orders_types(user_id);

