import dotenv from 'dotenv';
import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { Client } from 'pg';

// Carrega .env.local e .env (se existir)
dotenv.config({ path: '.env.local' });
dotenv.config();

function pickDbUrl() {
  const candidates = ['SUPABASE_DB_URL', 'POSTGRES_URL', 'DATABASE_URL'];
  for (const key of candidates) {
    const value = process.env[key];
    if (value && typeof value === 'string' && value.trim().length > 0) {
      return { key, url: value.trim() };
    }
  }
  return null;
}

function qIdent(name) {
  return `"${String(name).replaceAll('"', '""')}"`;
}

function section(title) {
  return `\n-- =============================================================================\n-- ${title}\n-- =============================================================================\n`;
}

const picked = pickDbUrl();
if (!picked) {
  console.error('❌ URL do Postgres não encontrada.');
  console.error('   Defina uma destas variáveis (ex.: no `.env.local`): SUPABASE_DB_URL, POSTGRES_URL, DATABASE_URL');
  process.exit(1);
}

const outPath = resolve('supabase/migration_20260302_2300/schema.sql');

function safeParsePgUrl(url) {
  try {
    // Node URL suporta `postgresql://...`
    const u = new URL(url);
    return {
      protocol: u.protocol,
      host: u.hostname,
      port: u.port,
      database: u.pathname?.replace(/^\//, '') || '',
      user: u.username || '',
    };
  } catch {
    return null;
  }
}

const client = new Client({
  connectionString: picked.url,
  statement_timeout: 120_000,
});

const SCHEMAS = (process.env.MIGRATION_SCHEMAS || 'public')
  .split(',')
  .map((s) => s.trim())
  .filter(Boolean);

async function main() {
  const parsed = safeParsePgUrl(picked.url);
  if (parsed?.host === 'supabase_db') {
    console.warn('⚠️  O host `supabase_db` é interno do Docker e NÃO resolve no seu Windows.');
    console.warn('   Opções: (1) rodar este script no VPS, (2) usar SSH tunnel para o Postgres, ou (3) exportar via `docker exec ... pg_dump` no VPS.');
  }

  try {
    await client.connect();
  } catch (err) {
    const code = err?.code || '';
    if (code === 'ENOTFOUND') {
      console.error(`❌ Falha DNS ao conectar no Postgres (host não encontrado).`);
      if (parsed?.host) console.error(`   Host: ${parsed.host}`);
      console.error(`   Dica: 'supabase_db' só existe dentro da rede Docker. Use túnel SSH ou rode no VPS.`);
      throw err;
    }
    throw err;
  }

  const parts = [];
  parts.push(`-- Generated by migration_20260302_2300/export_schema.mjs`);
  parts.push(`-- Source env: ${picked.key}`);
  parts.push(`-- Schemas: ${SCHEMAS.join(', ')}`);
  parts.push(`-- Generated at: ${new Date().toISOString()}\n`);

  // EXTENSIONS
  parts.push(section('EXTENSIONS'));
  {
    const { rows } = await client.query(
      `
      select extname
      from pg_extension
      where extname not in ('plpgsql')
      order by extname;
      `
    );
    for (const r of rows) {
      parts.push(`CREATE EXTENSION IF NOT EXISTS ${qIdent(r.extname)};`);
    }
    if (rows.length === 0) parts.push(`-- (no non-default extensions detected)`);
  }

  // TABLES
  parts.push(section('TABLES (DDL)'));
  const tables = (
    await client.query(
      `
      select c.oid, n.nspname as schema, c.relname as name
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = any($1)
        and c.relkind = 'r'
      order by c.relname;
      `,
      [SCHEMAS]
    )
  ).rows;

  for (const t of tables) {
    parts.push(`\n-- Table: ${t.schema}.${t.name}`);

    const cols = (
      await client.query(
        `
        select
          a.attnum,
          a.attname as name,
          pg_catalog.format_type(a.atttypid, a.atttypmod) as data_type,
          a.attnotnull as not_null,
          pg_get_expr(ad.adbin, ad.adrelid) as default_expr,
          a.attidentity as identity
        from pg_attribute a
        left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
        where a.attrelid = $1
          and a.attnum > 0
          and not a.attisdropped
        order by a.attnum;
        `,
        [t.oid]
      )
    ).rows;

    const constraints = (
      await client.query(
        `
        select conname, contype, pg_get_constraintdef(oid, true) as def
        from pg_constraint
        where conrelid = $1
        order by
          case contype
            when 'p' then 1
            when 'u' then 2
            when 'f' then 3
            when 'c' then 4
            else 9
          end,
          conname;
        `,
        [t.oid]
      )
    ).rows;

    const lines = [];
    for (const c of cols) {
      let line = `${qIdent(c.name)} ${c.data_type}`;
      if (c.identity && c.identity !== '') {
        line += c.identity === 'a' ? ' GENERATED ALWAYS AS IDENTITY' : ' GENERATED BY DEFAULT AS IDENTITY';
      } else if (c.default_expr) {
        line += ` DEFAULT ${c.default_expr}`;
      }
      if (c.not_null) line += ' NOT NULL';
      lines.push(line);
    }

    for (const con of constraints) {
      lines.push(`CONSTRAINT ${qIdent(con.conname)} ${con.def}`);
    }

    parts.push(`CREATE TABLE IF NOT EXISTS ${qIdent(t.schema)}.${qIdent(t.name)} (\n  ${lines.join(',\n  ')}\n);`);
  }

  // INDEXES
  parts.push(section('INDEXES'));
  {
    const { rows } = await client.query(
      `
      select
        schemaname,
        tablename,
        indexname,
        indexdef
      from pg_indexes
      where schemaname = any($1)
      order by tablename, indexname;
      `,
      [SCHEMAS]
    );

    for (const r of rows) {
      const idx = String(r.indexdef)
        .replace(/^CREATE\s+UNIQUE\s+INDEX\s+/i, 'CREATE UNIQUE INDEX IF NOT EXISTS ')
        .replace(/^CREATE\s+INDEX\s+/i, 'CREATE INDEX IF NOT EXISTS ');
      parts.push(`\n-- ${r.schemaname}.${r.indexname} on ${r.tablename}`);
      parts.push(`${idx};`.replace(/;;$/, ';'));
    }
    if (rows.length === 0) parts.push(`-- (no indexes detected)`);
  }

  // VIEWS
  parts.push(section('VIEWS'));
  {
    const { rows } = await client.query(
      `
      select c.oid, n.nspname as schema, c.relname as name
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = any($1)
        and c.relkind in ('v','m')
      order by c.relname;
      `,
      [SCHEMAS]
    );

    for (const v of rows) {
      const { rows: defRows } = await client.query(`select pg_get_viewdef($1, true) as def;`, [v.oid]);
      const def = defRows[0]?.def;
      if (!def) continue;
      parts.push(`\n-- View: ${v.schema}.${v.name}`);
      parts.push(`CREATE OR REPLACE VIEW ${qIdent(v.schema)}.${qIdent(v.name)} AS\n${def.trim().replace(/;\s*$/, '')};`);
    }
    if (rows.length === 0) parts.push(`-- (no views detected)`);
  }

  // FUNCTIONS
  parts.push(section('FUNCTIONS'));
  {
    const { rows } = await client.query(
      `
      select p.oid, n.nspname as schema, p.proname as name
      from pg_proc p
      join pg_namespace n on n.oid = p.pronamespace
      where n.nspname = any($1)
      order by p.proname, p.oid;
      `,
      [SCHEMAS]
    );

    for (const f of rows) {
      const { rows: defRows } = await client.query(`select pg_get_functiondef($1) as def;`, [f.oid]);
      const def = defRows[0]?.def;
      if (!def) continue;
      parts.push(`\n-- Function: ${f.schema}.${f.name}`);
      parts.push(def.trim().replace(/\s*$/, '') + '\n');
    }
    if (rows.length === 0) parts.push(`-- (no functions detected)`);
  }

  // TRIGGERS
  parts.push(section('TRIGGERS'));
  {
    const { rows } = await client.query(
      `
      select
        t.oid,
        n.nspname as schema,
        c.relname as table_name,
        t.tgname as trigger_name
      from pg_trigger t
      join pg_class c on c.oid = t.tgrelid
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = any($1)
        and not t.tgisinternal
      order by c.relname, t.tgname;
      `,
      [SCHEMAS]
    );

    for (const tr of rows) {
      const { rows: defRows } = await client.query(`select pg_get_triggerdef($1, true) as def;`, [tr.oid]);
      const def = defRows[0]?.def;
      if (!def) continue;
      parts.push(`\n-- Trigger: ${tr.schema}.${tr.table_name}.${tr.trigger_name}`);
      parts.push(
        `DROP TRIGGER IF EXISTS ${qIdent(tr.trigger_name)} ON ${qIdent(tr.schema)}.${qIdent(tr.table_name)};`
      );
      parts.push(def.trim().replace(/;\s*$/, '') + ';');
    }
    if (rows.length === 0) parts.push(`-- (no triggers detected)`);
  }

  // RLS & POLICIES
  parts.push(section('RLS & POLICIES'));
  {
    const { rows: policyTables } = await client.query(
      `
      select distinct schemaname as schema, tablename as table
      from pg_policies
      where schemaname = any($1)
      order by tablename;
      `,
      [SCHEMAS]
    );
    for (const pt of policyTables) {
      parts.push(`ALTER TABLE ${qIdent(pt.schema)}.${qIdent(pt.table)} ENABLE ROW LEVEL SECURITY;`);
    }

    const { rows } = await client.query(
      `
      select
        schemaname,
        tablename,
        policyname,
        permissive,
        roles,
        cmd,
        qual,
        with_check
      from pg_policies
      where schemaname = any($1)
      order by tablename, policyname;
      `,
      [SCHEMAS]
    );

    for (const p of rows) {
      const roles = Array.isArray(p.roles) && p.roles.length > 0 ? p.roles.map(qIdent).join(', ') : 'PUBLIC';
      const asPerm = p.permissive ? 'PERMISSIVE' : 'RESTRICTIVE';
      const cmd = String(p.cmd || 'ALL').toUpperCase();
      const using = p.qual ? ` USING (${p.qual})` : '';
      const check = p.with_check ? ` WITH CHECK (${p.with_check})` : '';
      parts.push(`\n-- Policy: ${p.schemaname}.${p.tablename}.${p.policyname}`);
      parts.push(`DROP POLICY IF EXISTS ${qIdent(p.policyname)} ON ${qIdent(p.schemaname)}.${qIdent(p.tablename)};`);
      parts.push(
        `CREATE POLICY ${qIdent(p.policyname)} ON ${qIdent(p.schemaname)}.${qIdent(p.tablename)} ` +
          `AS ${asPerm} FOR ${cmd} TO ${roles}${using}${check};`
      );
    }
    if (rows.length === 0) parts.push(`-- (no RLS policies detected)`);
  }

  // GRANTS (best-effort)
  parts.push(section('GRANTS (best-effort)'));
  {
    const { rows } = await client.query(
      `
      select
        table_schema,
        table_name,
        grantee,
        privilege_type
      from information_schema.role_table_grants
      where table_schema = any($1)
      order by table_name, grantee, privilege_type;
      `,
      [SCHEMAS]
    );

    const map = new Map();
    for (const r of rows) {
      const key = `${r.table_schema}.${r.table_name}::${r.grantee}`;
      const set = map.get(key) ?? new Set();
      set.add(r.privilege_type);
      map.set(key, set);
    }

    for (const [k, v] of map) {
      const [table, grantee] = k.split('::');
      const [schema, name] = table.split('.');
      const privs = [...v].sort().join(', ');
      parts.push(`GRANT ${privs} ON TABLE ${qIdent(schema)}.${qIdent(name)} TO ${qIdent(grantee)};`);
    }
    if (map.size === 0) parts.push(`-- (no table grants detected via information_schema)`);
  }

  parts.push(section('FINAL'));
  parts.push(`NOTIFY pgrst, 'reload schema';`);

  await writeFile(outPath, parts.join('\n') + '\n', 'utf8');
  console.log(`✅ Estrutura exportada para: ${outPath}`);
}

main()
  .catch((err) => {
    console.error('❌ Falha ao exportar estrutura:', err?.message || err);
    process.exitCode = 1;
  })
  .finally(async () => {
    try {
      await client.end();
    } catch {
      // ignore
    }
  });

