-- Tabela de junção para vincular OSs com Alertas (N:N)
CREATE TABLE IF NOT EXISTS public.orders_alerts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL,
    alert_id bigint NOT NULL,
    created_at timestamp DEFAULT now(),
    created_user_id bigint,
    CONSTRAINT fk_orders_alerts_order
        FOREIGN KEY (order_id)
        REFERENCES public.orders(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_orders_alerts_alert
        FOREIGN KEY (alert_id)
        REFERENCES public.assets_alerts(id)
        ON DELETE CASCADE,
    CONSTRAINT uq_orders_alerts_order_alert
        UNIQUE (order_id, alert_id)
);

CREATE INDEX IF NOT EXISTS idx_orders_alerts_order_id
    ON public.orders_alerts(order_id);

CREATE INDEX IF NOT EXISTS idx_orders_alerts_alert_id
    ON public.orders_alerts(alert_id);
