-- ============================================================
-- Migration: Rateio de Aluguel Veicular (Fase 1)
-- Date: 2026-10-08
-- Description:
--   Apropria o custo mensal de aluguel de veículos às visitas
--   técnicas proporcionalmente ao Km rodado (ver
--   docs/PLANO_RATEIO_ALUGUEL_VEICULAR.md).
--
--   Conteúdo:
--     1. cfg_vehicles_costs_types      (tipos de custo variável + seed)
--     2. cfg_vehicles_rentals_contracts(contrato mensal por veículo)
--     3. orders_visits_vehicles.cost_type + trigger BEFORE com guard
--     4. vehicle_rental_periods      (competência mensal)
--     5. vehicles_rentals_allocations  (rateio por visita)
--     6. RLS + grants
--     7. Triggers de imutabilidade (competência fechada/alocada)
--     8. RPCs de apuração (contract/summary/detail/calculate/
--        allocate/close/reopen/revert)
--     9. v_orders_visits_vehicles com cost_type (aditivo)
--    10. fc_financial_orders_visits_vehicles_sum com cost_type
--    11. cfg_routes (transport_rental_apportionment,
--        settings_vehicle_cost_types)
--
--   Aplicação MANUAL no SQL Editor do Supabase (regra do AGENTS.md).
--   Idempotente: pode ser re-executada com segurança ATÉ a Fase 2
--   (20261009). Depois da Fase 2 este arquivo aborta no 1º comando
--   (ver guarda logo abaixo) — para restaurar algo alterado por uma
--   re-execução parcial, re-aplique a 20261009 (idempotente).
--   Nenhum DROP ... CASCADE nesta migration (regra do AGENTS.md).
--
--   Âncora de competência: orders_visits_vehicles.created_at
--   (fallback: orders_visits.ov_created_at) — mês em que o veículo
--   foi vinculado à visita.
-- ============================================================

-- ------------------------------------------------------------
-- 0. GUARD: aborta se a Fase 2 (20261009) já foi aplicada.
--     Re-executar a Fase 1 depois da Fase 2 regrava o CHECK de
--     cost_type (perde 'rate'), o before_save (perde o ramo de
--     conversão) e o rateio_guard (perde 'rate') ANTES de falhar
--     no retorno de fc_vehicle_rental_summary — danificando o
--     banco. O DROP da Fase 2 de summary/detail impediria o
--     CREATE OR REPLACE aqui (42P13), mas só depois desses
--     clobbers. Falhar cedo e ruidoso é o comportamento desejado.
-- ------------------------------------------------------------
DO $$
BEGIN
    IF to_regclass('public.vehicle_monthly_expenses') IS NOT NULL THEN
        RAISE EXCEPTION USING
            MESSAGE = 'Fase 1 (20261008) não pode ser re-executada depois da Fase 2 (20261009): vehicle_monthly_expenses já existe. Se uma re-execução parcial alterou before_save/rateio_guard/CHECK de cost_type, re-aplique dev/supabase/migrations/20261009_add_vehicle_monthly_expenses.sql (idempotente) para restaurar.',
            HINT = 'Nunca re-execute 20261008 após 20261009. Ordem obrigatória: 20261008 -> 20261009.';
    END IF;
END $$;


-- ------------------------------------------------------------
-- 1. Tipos de custo variável veicular (parametrizáveis)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cfg_vehicles_costs_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    code character varying(30) NOT NULL,
    description character varying(100) NOT NULL,
    color character varying(20),
    is_available boolean DEFAULT true NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone,
    CONSTRAINT cfg_vehicles_costs_types_pkey PRIMARY KEY (id),
    CONSTRAINT cfg_vehicles_costs_types_code_key UNIQUE (code)
);

COMMENT ON TABLE public.cfg_vehicles_costs_types IS
    'Tipos parametrizáveis de custo variável veicular. No MVP é preenchida pelo seed e editada em Configurações; consumida pela Fase 2 (despesas reais do rateio).';

INSERT INTO public.cfg_vehicles_costs_types (id, code, description, color, is_available) VALUES
    (1, 'FUEL',         'Combustível', '#F97316', true),
    (2, 'TOLL',         'Pedágio',     '#0EA5E9', true),
    (3, 'MAINTENANCE',  'Manutenção',  '#22C55E', true),
    (4, 'INSURANCE_TAX','Seguro/IPVA', '#A855F7', true),
    (5, 'OTHER',        'Outros',      '#64748B', true)
ON CONFLICT DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('public.cfg_vehicles_costs_types', 'id'),
    GREATEST(
        (SELECT COALESCE(MAX(id), 1) FROM public.cfg_vehicles_costs_types),
        (SELECT last_value FROM public.cfg_vehicles_costs_types_id_seq)
    )
);

ALTER TABLE public.cfg_vehicles_costs_types ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Universal Access" ON public.cfg_vehicles_costs_types;
CREATE POLICY "Universal Access" ON public.cfg_vehicles_costs_types
    USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public.cfg_vehicles_costs_types TO authenticated, service_role;
REVOKE ALL ON TABLE public.cfg_vehicles_costs_types FROM anon;
GRANT USAGE ON SEQUENCE public.cfg_vehicles_costs_types_id_seq TO authenticated, service_role;

-- ------------------------------------------------------------
-- 2. Contrato de aluguel mensal por veículo
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cfg_vehicles_rentals_contracts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    vehicle_id bigint NOT NULL,
    monthly_value numeric(14,2) NOT NULL,
    start_date date NOT NULL,
    end_date date,
    active boolean DEFAULT true NOT NULL,
    description text,
    is_deleted boolean DEFAULT false NOT NULL,
    created_user_id bigint,
    created_at timestamp without time zone DEFAULT now(),
    updated_user_id bigint,
    updated_at timestamp without time zone,
    CONSTRAINT cfg_vehicles_rentals_contracts_pkey PRIMARY KEY (id),
    CONSTRAINT cfg_vehicles_rentals_contracts_value_ck CHECK (monthly_value >= 0),
    CONSTRAINT cfg_vehicles_rentals_contracts_dates_ck CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT cfg_vehicles_rentals_contracts_vehicle_fk
        FOREIGN KEY (vehicle_id) REFERENCES public.vehicles (id) ON DELETE CASCADE
);

COMMENT ON TABLE public.cfg_vehicles_rentals_contracts IS
    'Contrato(s) de aluguel mensal de veículo. Vigências sobrepostas para o mesmo veículo/mês são permitidas na tabela; a apuração escolhe a mais recente e sinaliza has_conflict.';

CREATE INDEX IF NOT EXISTS idx_cfg_vehicles_rentals_contracts_vehicle
    ON public.cfg_vehicles_rentals_contracts (vehicle_id)
    WHERE active AND NOT is_deleted;

ALTER TABLE public.cfg_vehicles_rentals_contracts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Universal Access" ON public.cfg_vehicles_rentals_contracts;
CREATE POLICY "Universal Access" ON public.cfg_vehicles_rentals_contracts
    USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public.cfg_vehicles_rentals_contracts TO authenticated, service_role;
REVOKE ALL ON TABLE public.cfg_vehicles_rentals_contracts FROM anon;
GRANT USAGE ON SEQUENCE public.cfg_vehicles_rentals_contracts_id_seq TO authenticated, service_role;

-- ------------------------------------------------------------
-- 3. cost_type em orders_visits_vehicles + trigger BEFORE com guard
--    'odometer' (padrão, comportamento atual intacto)
--    'rental'   (linha gerada pela apuração de aluguel)
--    'variable' (reservado para despesas reais — Fase 2)
-- ------------------------------------------------------------
ALTER TABLE public.orders_visits_vehicles
    ADD COLUMN IF NOT EXISTS cost_type character varying(20) NOT NULL DEFAULT 'odometer';

ALTER TABLE public.orders_visits_vehicles
    DROP CONSTRAINT IF EXISTS orders_visits_vehicles_cost_type_ck;

ALTER TABLE public.orders_visits_vehicles
    ADD CONSTRAINT orders_visits_vehicles_cost_type_ck
    CHECK (cost_type IN ('odometer', 'rental', 'variable'));

CREATE INDEX IF NOT EXISTS idx_orders_visits_vehicles_cost_type
    ON public.orders_visits_vehicles (cost_type)
    WHERE NOT is_deleted;

-- Recria o trigger BEFORE preservando o comportamento original para
-- 'odometer' e aceitando linhas de rateio/despesa (valores informados
-- pelo chamador, sem odômetro). Assinatura idêntica => CREATE OR REPLACE.
CREATE OR REPLACE FUNCTION public.fc_orders_visits_vehicles_before_save() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'public'
    AS $$
DECLARE
    v_price numeric;
BEGIN

    -- Linhas de rateio/despesa não têm odômetro: preserva amount/value_unit
    -- informados e recalcula apenas value_total.
    IF NEW.cost_type IN ('rental', 'variable') THEN
        NEW.recorder_start := NULL;
        NEW.recorder_end   := NULL;
        NEW.value_unit     := COALESCE(NEW.value_unit, 0);
        NEW.amount         := COALESCE(NEW.amount, 0);
        NEW.value_total    := ROUND(
            NEW.amount * NEW.value_unit * COALESCE(NEW.discount, 1), 2
        );
        RETURN NEW;
    END IF;

    SELECT value_unit
    INTO v_price
    FROM public.vehicles
    WHERE id = NEW.vehicle_id;

    NEW.value_unit := COALESCE(v_price,0);

    NEW.amount :=
        GREATEST(
            COALESCE(NEW.recorder_end,0)
            - COALESCE(NEW.recorder_start,0),
            0
        );

    NEW.value_total :=
        NEW.amount
        * NEW.value_unit
        * COALESCE(NEW.discount,1);

    RETURN NEW;

END;
$$;

-- ------------------------------------------------------------
-- 4. Competência mensal de aluguel por veículo
--    reference_month = primeiro dia do mês (normalizado pelas RPCs)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.vehicle_rental_periods (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    vehicle_id bigint NOT NULL,
    reference_month date NOT NULL,
    contract_id bigint,
    contract_value numeric(14,2) NOT NULL DEFAULT 0,
    total_km bigint NOT NULL DEFAULT 0,
    cost_per_km numeric(14,6),
    variable_value numeric(14,2) NOT NULL DEFAULT 0,
    variable_per_km numeric(14,6),
    allocated_value numeric(14,2) NOT NULL DEFAULT 0,
    idle_value numeric(14,2) NOT NULL DEFAULT 0,
    has_conflict boolean NOT NULL DEFAULT false,
    status character varying(20) NOT NULL DEFAULT 'OPEN',
    created_user_id bigint,
    created_at timestamp without time zone DEFAULT now(),
    updated_user_id bigint,
    updated_at timestamp without time zone,
    CONSTRAINT vehicle_rental_periods_pkey PRIMARY KEY (id),
    CONSTRAINT vehicle_rental_periods_month_uq UNIQUE (vehicle_id, reference_month),
    CONSTRAINT vehicle_rental_periods_status_ck
        CHECK (status IN ('OPEN', 'CALCULATED', 'ALLOCATED', 'CLOSED')),
    CONSTRAINT vehicle_rental_periods_month_ck
        CHECK (reference_month = date_trunc('month', reference_month)::date),
    CONSTRAINT vehicle_rental_periods_value_ck CHECK (contract_value >= 0),
    CONSTRAINT vehicle_rental_periods_vehicle_fk
        FOREIGN KEY (vehicle_id) REFERENCES public.vehicles (id) ON DELETE CASCADE,
    CONSTRAINT vehicle_rental_periods_contract_fk
        FOREIGN KEY (contract_id) REFERENCES public.cfg_vehicles_rentals_contracts (id) ON DELETE SET NULL
);

COMMENT ON TABLE public.vehicle_rental_periods IS
    'Competência (mês) de apuração do aluguel de um veículo. status: OPEN -> CALCULATED -> ALLOCATED -> CLOSED. Fechada é imutável (trigger de guarda).';
COMMENT ON COLUMN public.vehicle_rental_periods.variable_per_km IS
    'Reservado para a Fase 2 (custos variáveis reais por Km).';

CREATE INDEX IF NOT EXISTS idx_vehicle_rental_periods_reference_month
    ON public.vehicle_rental_periods (reference_month);

-- ------------------------------------------------------------
-- 5. Rateio por visita (uma linha por visita de origem e componente)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.vehicles_rentals_allocations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    period_id bigint NOT NULL,
    ov_id bigint NOT NULL,
    ovv_id bigint NOT NULL,
    rental_ovv_id bigint,
    km bigint NOT NULL DEFAULT 0,
    rate numeric(14,6) NOT NULL DEFAULT 0,
    value numeric(14,2) NOT NULL DEFAULT 0,
    cost_component character varying(20) NOT NULL DEFAULT 'RENTAL',
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT vehicles_rentals_allocations_pkey PRIMARY KEY (id),
    -- Idempotência: re-executar allocate não duplica rateio
    CONSTRAINT vehicles_rentals_allocations_uq UNIQUE (period_id, ovv_id, cost_component),
    CONSTRAINT vehicles_rentals_allocations_component_ck
        CHECK (cost_component IN ('RENTAL', 'VARIABLE')),
    CONSTRAINT vehicles_rentals_allocations_period_fk
        FOREIGN KEY (period_id) REFERENCES public.vehicle_rental_periods (id) ON DELETE CASCADE,
    CONSTRAINT vehicles_rentals_allocations_ov_fk
        FOREIGN KEY (ov_id) REFERENCES public.orders_visits (id) ON DELETE CASCADE,
    CONSTRAINT vehicles_rentals_allocations_ovv_fk
        FOREIGN KEY (ovv_id) REFERENCES public.orders_visits_vehicles (id) ON DELETE CASCADE,
    CONSTRAINT vehicles_rentals_allocations_rental_ovv_fk
        FOREIGN KEY (rental_ovv_id) REFERENCES public.orders_visits_vehicles (id) ON DELETE CASCADE
);

COMMENT ON TABLE public.vehicles_rentals_allocations IS
    'Rateio de aluguel aplicado a uma visita: km da linha de odômetro (ovv_id), valor proporcional e ponte para a linha rental gerada (rental_ovv_id).';

CREATE INDEX IF NOT EXISTS idx_vehicles_rentals_allocations_period
    ON public.vehicles_rentals_allocations (period_id);
CREATE INDEX IF NOT EXISTS idx_vehicles_rentals_allocations_ov
    ON public.vehicles_rentals_allocations (ov_id);

-- ------------------------------------------------------------
-- 6. RLS + grants
--    periods/allocations: somente LEITURA direta (escrita só via RPC
--    SECURITY DEFINER, que roda como dono das tabelas).
-- ------------------------------------------------------------
ALTER TABLE public.vehicle_rental_periods ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Select only" ON public.vehicle_rental_periods;
CREATE POLICY "Select only" ON public.vehicle_rental_periods
    FOR SELECT TO authenticated USING (true);
GRANT SELECT ON TABLE public.vehicle_rental_periods TO authenticated, service_role;
REVOKE ALL ON TABLE public.vehicle_rental_periods FROM anon;
GRANT USAGE ON SEQUENCE public.vehicle_rental_periods_id_seq TO authenticated, service_role;

ALTER TABLE public.vehicles_rentals_allocations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Select only" ON public.vehicles_rentals_allocations;
CREATE POLICY "Select only" ON public.vehicles_rentals_allocations
    FOR SELECT TO authenticated USING (true);
GRANT SELECT ON TABLE public.vehicles_rentals_allocations TO authenticated, service_role;
REVOKE ALL ON TABLE public.vehicles_rentals_allocations FROM anon;
GRANT USAGE ON SEQUENCE public.vehicles_rentals_allocations_id_seq TO authenticated, service_role;

-- ------------------------------------------------------------
-- 7. Triggers de imutabilidade
--    Flag de sessão 'app.vehicle_rental_write' = caminho das RPCs.
--    Escrita direta (PostgREST/UI) nunca seta a flag, então:
--      - períodos: bloqueados (só RPC gerencia)
--      - allocations: bloqueadas; DELETE só se a competência não
--        estiver fechada (ex.: exclusão em cascata de visita)
--      - linhas rental: imutáveis; linhas de odômetro já rateadas
--        ficam congeladas enquanto ALLOCATED/CLOSED
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fc_vehicle_rental_period_guard() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
BEGIN
    IF coalesce(current_setting('app.vehicle_rental_write', true), '') = '1' THEN
        RETURN COALESCE(NEW, OLD);
    END IF;

    IF TG_OP = 'DELETE' THEN
        IF OLD.status IN ('ALLOCATED', 'CLOSED') THEN
            RAISE EXCEPTION 'Competência % do veículo % não pode ser excluída: rateio já alocado/fechado. Use a apuração (fc_vehicle_rental_revert).',
                OLD.reference_month, OLD.vehicle_id;
        END IF;
        RETURN OLD;
    END IF;

    RAISE EXCEPTION 'Período de rateio de aluguel é gerenciado exclusivamente pelas RPCs de apuração (fc_vehicle_rental_*).';
END;
$$;

CREATE OR REPLACE FUNCTION public.fc_vehicle_rental_allocation_guard() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_status character varying;
BEGIN
    IF coalesce(current_setting('app.vehicle_rental_write', true), '') = '1' THEN
        RETURN COALESCE(NEW, OLD);
    END IF;

    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'Rateio de aluguel é gerado pela apuração mensal e não pode ser editado diretamente.';
    END IF;

    -- DELETE: permitido apenas enquanto a competência não estiver fechada
    -- (ex.: visita apagada em cascata antes do fechamento)
    SELECT p.status INTO v_status
    FROM public.vehicle_rental_periods p
    WHERE p.id = OLD.period_id;

    IF v_status = 'CLOSED' THEN
        RAISE EXCEPTION 'Competência fechada: o rateio é imutável (reabra a competência para alterar).';
    END IF;

    RETURN OLD;
END;
$$;

CREATE OR REPLACE FUNCTION public.fc_orders_visits_vehicles_rateio_guard() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_flag boolean := coalesce(current_setting('app.vehicle_rental_write', true), '') = '1';
    v_status character varying;
    v_period_id bigint;
BEGIN
    IF TG_OP = 'INSERT' THEN
        -- Linhas de rateio/despesa só nascem na apuração (RPC)
        IF v_flag THEN
            RETURN NEW;
        END IF;
        IF NEW.cost_type <> 'odometer' THEN
            RAISE EXCEPTION 'Linha de rateio/despesa só pode ser criada pela apuração mensal (fc_vehicle_rental_*).';
        END IF;
        RETURN NEW;
    END IF;

    IF TG_OP = 'UPDATE' THEN
        -- Atualizações que não tocam em Km/valores são sempre permitidas
        -- (ex.: fc_sync_ov_costs_status espelha ov_costs_status da visita
        -- em todas as linhas filhas — incluindo linhas rental/rateadas)
        IF NEW.ov_id IS NOT DISTINCT FROM OLD.ov_id
           AND NEW.vehicle_id IS NOT DISTINCT FROM OLD.vehicle_id
           AND NEW.recorder_start IS NOT DISTINCT FROM OLD.recorder_start
           AND NEW.recorder_end IS NOT DISTINCT FROM OLD.recorder_end
           AND NEW.amount IS NOT DISTINCT FROM OLD.amount
           AND NEW.discount IS NOT DISTINCT FROM OLD.discount
           AND NEW.cost_type IS NOT DISTINCT FROM OLD.cost_type
           AND NEW.is_deleted IS NOT DISTINCT FROM OLD.is_deleted THEN
            RETURN NEW;
        END IF;

        -- Linha de rateio: nunca editável fora da RPC
        IF NEW.cost_type = 'rental' THEN
            IF v_flag THEN
                RETURN NEW;
            END IF;
            RAISE EXCEPTION 'Linha de rateio de aluguel é gerada pela apuração mensal e não pode ser editada.';
        END IF;

        -- Linha de odômetro já rateada: congelada até o estorno
        SELECT p.status, p.id INTO v_status, v_period_id
        FROM public.vehicles_rentals_allocations a
        JOIN public.vehicle_rental_periods p ON p.id = a.period_id
        WHERE a.ovv_id = NEW.id
        LIMIT 1;

        IF v_status IS NOT NULL AND NOT v_flag THEN
            RAISE EXCEPTION 'Km já rateado na competência % — faça o estorno (fc_vehicle_rental_revert) antes de alterar a leitura do odômetro.',
                v_period_id;
        END IF;

        RETURN NEW;
    END IF;

    -- DELETE ------------------------------------------------------------------
    IF OLD.cost_type = 'rental' THEN
        IF v_flag THEN
            RETURN OLD;
        END IF;

        SELECT p.status INTO v_status
        FROM public.vehicles_rentals_allocations a
        JOIN public.vehicle_rental_periods p ON p.id = a.period_id
        WHERE a.rental_ovv_id = OLD.id
        LIMIT 1;

        IF v_status = 'CLOSED' THEN
            RAISE EXCEPTION 'Competência fechada: o rateio de aluguel é imutável (reabra a competência para alterar).';
        END IF;

        RETURN OLD;
    END IF;

    -- Linha de odômetro já rateada: bloqueia exclusão fora da RPC
    SELECT p.status INTO v_status
    FROM public.vehicles_rentals_allocations a
    JOIN public.vehicle_rental_periods p ON p.id = a.period_id
    WHERE a.ovv_id = OLD.id
    LIMIT 1;

    IF v_status IS NOT NULL AND NOT v_flag THEN
        RAISE EXCEPTION 'Km já rateado — faça o estorno (fc_vehicle_rental_revert) antes de remover a linha do veículo.';
    END IF;

    RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS trg_vehicle_rental_period_guard ON public.vehicle_rental_periods;
CREATE TRIGGER trg_vehicle_rental_period_guard
    BEFORE UPDATE OR DELETE ON public.vehicle_rental_periods
    FOR EACH ROW EXECUTE FUNCTION public.fc_vehicle_rental_period_guard();

DROP TRIGGER IF EXISTS trg_vehicle_rental_allocation_guard ON public.vehicles_rentals_allocations;
CREATE TRIGGER trg_vehicle_rental_allocation_guard
    BEFORE UPDATE OR DELETE ON public.vehicles_rentals_allocations
    FOR EACH ROW EXECUTE FUNCTION public.fc_vehicle_rental_allocation_guard();

DROP TRIGGER IF EXISTS trg_orders_visits_vehicles_rateio_guard ON public.orders_visits_vehicles;
CREATE TRIGGER trg_orders_visits_vehicles_rateio_guard
    BEFORE INSERT OR UPDATE OR DELETE ON public.orders_visits_vehicles
    FOR EACH ROW EXECUTE FUNCTION public.fc_orders_visits_vehicles_rateio_guard();

-- ------------------------------------------------------------
-- 8. RPCs de apuração
--    Todas: SECURITY DEFINER + search_path público + flag de sessão
--    'app.vehicle_rental_write' (libera os triggers de guarda).
-- ------------------------------------------------------------
-- 8.1 Contrato vigente do veículo na competência
CREATE OR REPLACE FUNCTION public.fc_vehicle_rental_contract(
    p_vehicle_id bigint,
    p_reference_month date
) RETURNS TABLE (
    contract_id bigint,
    monthly_value numeric,
    has_conflict boolean
)
    LANGUAGE plpgsql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_month date := (date_trunc('month', p_reference_month::timestamp))::date;
    v_month_end date := (date_trunc('month', p_reference_month::timestamp) + interval '1 month - 1 day')::date;
BEGIN
    -- Mais de um contrato vigente no mês => o mais recente vence e o
    -- conflito é sinalizado ao usuário.
    RETURN QUERY
    SELECT c.id,
           c.monthly_value,
           (count(*) OVER ()) > 1
    FROM public.cfg_vehicles_rentals_contracts c
    WHERE c.vehicle_id = p_vehicle_id
      AND c.active
      AND NOT c.is_deleted
      AND c.start_date <= v_month_end
      AND (c.end_date IS NULL OR c.end_date >= v_month)
    ORDER BY c.start_date DESC, c.id DESC
    LIMIT 1;
END;
$$;

-- 8.2 Resumo da competência (tabela da tela de Apuração).
--     Sem período calculado: valores "ao vivo" (SIMULAR).
--     Com período calculado: valores gravados (fonte do allocate).
CREATE OR REPLACE FUNCTION public.fc_vehicle_rental_summary(p_reference_month date)
RETURNS TABLE (
    period_id bigint,
    period_status character varying,
    vehicle_id bigint,
    vehicle_description text,
    vehicle_plates text,
    contract_id bigint,
    contract_value numeric,
    has_conflict boolean,
    total_km bigint,
    cost_per_km numeric,
    allocated_value numeric,
    idle_value numeric,
    utilization numeric
)
    LANGUAGE plpgsql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_month date := (date_trunc('month', p_reference_month::timestamp))::date;
    v_month_end date := (date_trunc('month', p_reference_month::timestamp) + interval '1 month - 1 day')::date;
    v_row record;
    v_period public.vehicle_rental_periods%ROWTYPE;
    v_km bigint;
    v_rate numeric;
    v_alloc numeric;
    v_value numeric;
BEGIN
    FOR v_row IN
        WITH contract_info AS (
            SELECT c.vehicle_id,
                   count(*) AS n_contracts,
                   (array_agg(c.id ORDER BY c.start_date DESC, c.id DESC))[1] AS best_id,
                   (array_agg(c.monthly_value ORDER BY c.start_date DESC, c.id DESC))[1] AS best_value
            FROM public.cfg_vehicles_rentals_contracts c
            WHERE c.active AND NOT c.is_deleted
              AND c.start_date <= v_month_end
              AND (c.end_date IS NULL OR c.end_date >= v_month)
            GROUP BY c.vehicle_id
        ),
        base AS (
            SELECT u.vvehicle, u.vcid, u.vvalue, u.prio
            FROM (
                SELECT p.vehicle_id AS vvehicle, p.contract_id AS vcid,
                       p.contract_value AS vvalue, 0 AS prio
                FROM public.vehicle_rental_periods p
                WHERE p.reference_month = v_month
                UNION ALL
                SELECT ci.vehicle_id, ci.best_id, ci.best_value, 1
                FROM contract_info ci
            ) u
        )
        SELECT DISTINCT ON (b.vvehicle)
               b.vvehicle, b.vcid, b.vvalue,
               COALESCE(ci.n_contracts, 0) > 1 AS vconflict,
               ve.description AS vd, ve.plates AS vp
        FROM base b
        LEFT JOIN contract_info ci ON ci.vehicle_id = b.vvehicle
        JOIN public.vehicles ve ON ve.id = b.vvehicle AND NOT ve.is_deleted
        ORDER BY b.vvehicle, b.prio, ve.description
    LOOP
        SELECT p.* INTO v_period
        FROM public.vehicle_rental_periods p
        WHERE p.vehicle_id = v_row.vvehicle
          AND p.reference_month = v_month;

        -- Km total do mês (âncora: created_at da linha, fallback da visita)
        SELECT COALESCE(sum(ovv.amount), 0)::bigint
        INTO v_km
        FROM public.orders_visits_vehicles ovv
        JOIN public.orders_visits ovs ON ovs.id = ovv.ov_id
        WHERE ovv.vehicle_id = v_row.vvehicle
          AND NOT ovv.is_deleted
          AND ovv.cost_type = 'odometer'
          AND ovv.amount > 0
          AND COALESCE(ovv.created_at, ovs.ov_created_at) >= v_month
          AND COALESCE(ovv.created_at, ovs.ov_created_at) < v_month + interval '1 month';

        v_value := COALESCE(v_period.contract_value, v_row.vvalue, 0);

        IF v_period.id IS NOT NULL THEN
            period_id := v_period.id;
            period_status := v_period.status;
            total_km := v_period.total_km;
            v_rate := v_period.cost_per_km;
            v_alloc := v_period.allocated_value;
        ELSE
            period_id := NULL;
            period_status := 'OPEN';
            total_km := v_km;
            v_rate := CASE WHEN v_km > 0 THEN v_value / v_km::numeric ELSE NULL END;
            -- Prévia: soma dos valores rateados com o custo/km previsto
            SELECT COALESCE(sum(round(ovv.amount * v_rate, 2)), 0)
            INTO v_alloc
            FROM public.orders_visits_vehicles ovv
            JOIN public.orders_visits ovs ON ovs.id = ovv.ov_id
            WHERE ovv.vehicle_id = v_row.vvehicle
              AND NOT ovv.is_deleted
              AND ovv.cost_type = 'odometer'
              AND ovv.amount > 0
              AND COALESCE(ovv.created_at, ovs.ov_created_at) >= v_month
              AND COALESCE(ovv.created_at, ovs.ov_created_at) < v_month + interval '1 month';
        END IF;

        vehicle_id := v_row.vvehicle;
        vehicle_description := v_row.vd;
        vehicle_plates := v_row.vp;
        contract_id := v_row.vcid;
        contract_value := v_value;
        has_conflict := v_row.vconflict;
        cost_per_km := v_rate;
        allocated_value := v_alloc;
        idle_value := v_value - v_alloc;
        utilization := CASE WHEN v_value > 0 THEN round(v_alloc / v_value, 4) ELSE NULL END;

        RETURN NEXT;
    END LOOP;
END;
$$;

-- 8.3 Detalhe visita a visita (tabela da SIMULAR)
CREATE OR REPLACE FUNCTION public.fc_vehicle_rental_detail(
    p_vehicle_id bigint,
    p_reference_month date
) RETURNS TABLE (
    period_id bigint,
    period_status character varying,
    ov_id bigint,
    ovv_id bigint,
    visit_mask character varying,
    km bigint,
    rate numeric,
    value numeric,
    rental_ovv_id bigint
)
    LANGUAGE plpgsql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_month date := (date_trunc('month', p_reference_month::timestamp))::date;
    v_period public.vehicle_rental_periods%ROWTYPE;
    v_rate numeric;
    v_value numeric;
    v_total bigint;
BEGIN
    SELECT p.* INTO v_period
    FROM public.vehicle_rental_periods p
    WHERE p.vehicle_id = p_vehicle_id
      AND p.reference_month = v_month;

    SELECT COALESCE(sum(ovv.amount), 0)::bigint
    INTO v_total
    FROM public.orders_visits_vehicles ovv
    JOIN public.orders_visits ovs ON ovs.id = ovv.ov_id
    WHERE ovv.vehicle_id = p_vehicle_id
      AND NOT ovv.is_deleted
      AND ovv.cost_type = 'odometer'
      AND ovv.amount > 0
      AND COALESCE(ovv.created_at, ovs.ov_created_at) >= v_month
      AND COALESCE(ovv.created_at, ovs.ov_created_at) < v_month + interval '1 month';

    v_value := COALESCE(v_period.contract_value, 0);
    IF v_period.cost_per_km IS NOT NULL THEN
        v_rate := v_period.cost_per_km;
    ELSIF v_period.id IS NULL THEN
        -- Sem cálculo: usa o contrato vigente para a prévia
        SELECT c.monthly_value INTO v_value
        FROM public.fc_vehicle_rental_contract(p_vehicle_id, v_month) c;
        v_rate := CASE WHEN v_total > 0 THEN v_value / v_total::numeric ELSE NULL END;
    ELSE
        v_rate := NULL;
    END IF;

    RETURN QUERY
    SELECT
        v_period.id,
        COALESCE(v_period.status, 'OPEN')::character varying,
        ovv.ov_id,
        ovv.id,
        ovs.ov_mask,
        ovv.amount,
        v_rate,
        round(ovv.amount * v_rate, 2),
        a.rental_ovv_id
    FROM public.orders_visits_vehicles ovv
    JOIN public.orders_visits ovs ON ovs.id = ovv.ov_id
    LEFT JOIN public.vehicles_rentals_allocations a
           ON a.ovv_id = ovv.id
          AND a.period_id IS NOT DISTINCT FROM v_period.id
          AND a.cost_component = 'RENTAL'
    WHERE ovv.vehicle_id = p_vehicle_id
      AND NOT ovv.is_deleted
      AND ovv.cost_type = 'odometer'
      AND ovv.amount > 0
      AND COALESCE(ovv.created_at, ovs.ov_created_at) >= v_month
      AND COALESCE(ovv.created_at, ovs.ov_created_at) < v_month + interval '1 month'
    ORDER BY COALESCE(ovv.created_at, ovs.ov_created_at), ovv.id;
END;
$$;

-- 8.4 Calcula a competência: contrato vigente + Km do mês + custo/km
CREATE OR REPLACE FUNCTION public.fc_vehicle_rental_calculate(
    p_vehicle_id bigint,
    p_reference_month date,
    p_user_id bigint DEFAULT NULL
) RETURNS SETOF public.vehicle_rental_periods
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_month date := (date_trunc('month', p_reference_month::timestamp))::date;
    v_period public.vehicle_rental_periods%ROWTYPE;
    v_contract_id bigint;
    v_contract_value numeric;
    v_has_conflict boolean;
    v_total_km bigint;
    v_rate numeric;
    v_alloc numeric;
BEGIN
    PERFORM set_config('app.vehicle_rental_write', '1', true);

    SELECT p.* INTO v_period
    FROM public.vehicle_rental_periods p
    WHERE p.vehicle_id = p_vehicle_id
      AND p.reference_month = v_month
    FOR UPDATE;

    IF v_period.id IS NOT NULL AND v_period.status IN ('ALLOCATED', 'CLOSED') THEN
        RAISE EXCEPTION 'Competência % do veículo % já alocada/fechada: faça o estorno antes de recalcular.',
            v_month, p_vehicle_id;
    END IF;

    SELECT c.contract_id, c.monthly_value, c.has_conflict
    INTO v_contract_id, v_contract_value, v_has_conflict
    FROM public.fc_vehicle_rental_contract(p_vehicle_id, v_month) c;

    IF v_contract_id IS NULL THEN
        RAISE EXCEPTION 'Nenhum contrato de aluguel ativo para o veículo % na competência %.',
            p_vehicle_id, v_month;
    END IF;

    -- Km total do mês (âncora: created_at da linha, fallback da visita)
    SELECT COALESCE(sum(ovv.amount), 0)::bigint
    INTO v_total_km
    FROM public.orders_visits_vehicles ovv
    JOIN public.orders_visits ovs ON ovs.id = ovv.ov_id
    WHERE ovv.vehicle_id = p_vehicle_id
      AND NOT ovv.is_deleted
      AND ovv.cost_type = 'odometer'
      AND ovv.amount > 0
      AND COALESCE(ovv.created_at, ovs.ov_created_at) >= v_month
      AND COALESCE(ovv.created_at, ovs.ov_created_at) < v_month + interval '1 month';

    -- custo/km = aluguel / total_km  (total_km = 0 => NULL, tudo ociosidade)
    v_rate := CASE
        WHEN v_total_km > 0 THEN round(v_contract_value / v_total_km::numeric, 6)
        ELSE NULL
    END;

    -- Prévia do apropriado: soma dos valores já arredondados por visita
    SELECT COALESCE(sum(round(ovv.amount * v_rate, 2)), 0)
    INTO v_alloc
    FROM public.orders_visits_vehicles ovv
    JOIN public.orders_visits ovs ON ovs.id = ovv.ov_id
    WHERE ovv.vehicle_id = p_vehicle_id
      AND NOT ovv.is_deleted
      AND ovv.cost_type = 'odometer'
      AND ovv.amount > 0
      AND COALESCE(ovv.created_at, ovs.ov_created_at) >= v_month
      AND COALESCE(ovv.created_at, ovs.ov_created_at) < v_month + interval '1 month';

    INSERT INTO public.vehicle_rental_periods (
        vehicle_id, reference_month, contract_id, contract_value, total_km,
        cost_per_km, allocated_value, idle_value, has_conflict, status,
        created_user_id, created_at, updated_user_id, updated_at
    ) VALUES (
        p_vehicle_id, v_month, v_contract_id, v_contract_value, v_total_km,
        v_rate, v_alloc, v_contract_value - v_alloc, v_has_conflict, 'CALCULATED',
        p_user_id, now(), p_user_id, now()
    )
    ON CONFLICT (vehicle_id, reference_month) DO UPDATE SET
        contract_id = EXCLUDED.contract_id,
        contract_value = EXCLUDED.contract_value,
        total_km = EXCLUDED.total_km,
        cost_per_km = EXCLUDED.cost_per_km,
        allocated_value = EXCLUDED.allocated_value,
        idle_value = EXCLUDED.idle_value,
        has_conflict = EXCLUDED.has_conflict,
        status = 'CALCULATED',
        updated_user_id = EXCLUDED.updated_user_id,
        updated_at = now();

    RETURN QUERY
    SELECT p.* FROM public.vehicle_rental_periods p
    WHERE p.vehicle_id = p_vehicle_id
      AND p.reference_month = v_month;
END;
$$;

-- 8.5 Aloca o rateio: para cada linha de odômetro do mês cria uma linha
--     'rental' na visita (rollup atualiza ov_vehicles_value) e a allocation.
--     NÃO altera ov_costs_status da visita (visitas aprovadas mantêm status).
--     Idempotente: re-executar não duplica (unique index).
CREATE OR REPLACE FUNCTION public.fc_vehicle_rental_allocate(
    p_vehicle_id bigint,
    p_reference_month date,
    p_user_id bigint DEFAULT NULL
) RETURNS SETOF public.vehicle_rental_periods
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_month date := (date_trunc('month', p_reference_month::timestamp))::date;
    v_period public.vehicle_rental_periods%ROWTYPE;
    v_line record;
    v_rental_id bigint;
    v_value numeric;
    v_alloc_total numeric;
BEGIN
    PERFORM set_config('app.vehicle_rental_write', '1', true);

    SELECT p.* INTO v_period
    FROM public.vehicle_rental_periods p
    WHERE p.vehicle_id = p_vehicle_id
      AND p.reference_month = v_month
    FOR UPDATE;

    IF v_period.id IS NULL THEN
        RAISE EXCEPTION 'Competência % do veículo % não foi calculada: execute o cálculo antes da alocação.',
            v_month, p_vehicle_id;
    END IF;

    IF v_period.status NOT IN ('CALCULATED', 'ALLOCATED') THEN
        RAISE EXCEPTION 'Competência % está %: reabra antes de alocar.',
            v_month, v_period.status;
    END IF;

    IF v_period.cost_per_km IS NULL THEN
        RAISE EXCEPTION 'Competência % sem Km rodado: nada a alocar (o valor do aluguel fica integralmente em ociosidade).',
            v_month;
    END IF;

    FOR v_line IN
        SELECT ovv.id AS ovv_id,
               ovv.ov_id,
               ovv.amount AS km,
               ovs.ov_costs_status AS visit_status
        FROM public.orders_visits_vehicles ovv
        JOIN public.orders_visits ovs ON ovs.id = ovv.ov_id
        WHERE ovv.vehicle_id = p_vehicle_id
          AND NOT ovv.is_deleted
          AND ovv.cost_type = 'odometer'
          AND ovv.amount > 0
          AND COALESCE(ovv.created_at, ovs.ov_created_at) >= v_month
          AND COALESCE(ovv.created_at, ovs.ov_created_at) < v_month + interval '1 month'
        ORDER BY ovv.id
    LOOP
        -- Idempotência de re-execução
        IF EXISTS (
            SELECT 1
            FROM public.vehicles_rentals_allocations a
            WHERE a.period_id = v_period.id
              AND a.ovv_id = v_line.ovv_id
              AND a.cost_component = 'RENTAL'
        ) THEN
            CONTINUE;
        END IF;

        v_value := round(v_line.km * v_period.cost_per_km, 2);

        -- Linha de rateio: amount = km, value_unit = custo/km do período.
        -- ov_costs_status copiado da visita => status aprovado é preservado.
        INSERT INTO public.orders_visits_vehicles (
            ov_id, vehicle_id, amount, value_unit, discount, cost_type,
            ov_costs_status, created_user_id, created_at, is_deleted
        ) VALUES (
            v_line.ov_id, p_vehicle_id, v_line.km, v_period.cost_per_km, 1,
            'rental', COALESCE(v_line.visit_status, 'pending'), p_user_id, now(), false
        )
        RETURNING id INTO v_rental_id;

        INSERT INTO public.vehicles_rentals_allocations (
            period_id, ov_id, ovv_id, rental_ovv_id, km, rate, value,
            cost_component, created_at
        ) VALUES (
            v_period.id, v_line.ov_id, v_line.ovv_id, v_rental_id,
            v_line.km, v_period.cost_per_km, v_value, 'RENTAL', now()
        )
        ON CONFLICT (period_id, ovv_id, cost_component) DO NOTHING;
    END LOOP;

    SELECT COALESCE(sum(a.value), 0)
    INTO v_alloc_total
    FROM public.vehicles_rentals_allocations a
    WHERE a.period_id = v_period.id;

    UPDATE public.vehicle_rental_periods p
    SET allocated_value = v_alloc_total,
        idle_value = p.contract_value - v_alloc_total,
        status = 'ALLOCATED',
        updated_user_id = p_user_id,
        updated_at = now()
    WHERE p.id = v_period.id;

    RETURN QUERY
    SELECT p.* FROM public.vehicle_rental_periods p
    WHERE p.id = v_period.id;
END;
$$;

-- 8.6 Fecha a competência (imutável a partir daqui)
CREATE OR REPLACE FUNCTION public.fc_vehicle_rental_close(
    p_vehicle_id bigint,
    p_reference_month date,
    p_user_id bigint DEFAULT NULL
) RETURNS SETOF public.vehicle_rental_periods
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_month date := (date_trunc('month', p_reference_month::timestamp))::date;
    v_period public.vehicle_rental_periods%ROWTYPE;
BEGIN
    PERFORM set_config('app.vehicle_rental_write', '1', true);

    SELECT p.* INTO v_period
    FROM public.vehicle_rental_periods p
    WHERE p.vehicle_id = p_vehicle_id
      AND p.reference_month = v_month
    FOR UPDATE;

    IF v_period.id IS NULL OR v_period.status = 'OPEN' THEN
        RAISE EXCEPTION 'Competência % do veículo % não foi calculada.', v_month, p_vehicle_id;
    END IF;

    IF v_period.status = 'CLOSED' THEN
        RAISE EXCEPTION 'Competência % do veículo % já está fechada.', v_month, p_vehicle_id;
    END IF;

    IF v_period.status = 'CALCULATED' AND v_period.total_km > 0 THEN
        RAISE EXCEPTION 'Há Km para alocar na competência %: execute a alocação antes de fechar.', v_month;
    END IF;

    UPDATE public.vehicle_rental_periods p
    SET status = 'CLOSED',
        updated_user_id = p_user_id,
        updated_at = now()
    WHERE p.id = v_period.id;

    RETURN QUERY
    SELECT p.* FROM public.vehicle_rental_periods p
    WHERE p.id = v_period.id;
END;
$$;

-- 8.7 Reabre a competência fechada (volta para ALLOCATED/CALCULATED)
CREATE OR REPLACE FUNCTION public.fc_vehicle_rental_reopen(
    p_vehicle_id bigint,
    p_reference_month date,
    p_user_id bigint DEFAULT NULL
) RETURNS SETOF public.vehicle_rental_periods
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_month date := (date_trunc('month', p_reference_month::timestamp))::date;
    v_period public.vehicle_rental_periods%ROWTYPE;
BEGIN
    PERFORM set_config('app.vehicle_rental_write', '1', true);

    SELECT p.* INTO v_period
    FROM public.vehicle_rental_periods p
    WHERE p.vehicle_id = p_vehicle_id
      AND p.reference_month = v_month
    FOR UPDATE;

    IF v_period.id IS NULL THEN
        RAISE EXCEPTION 'Competência % do veículo % não existe.', v_month, p_vehicle_id;
    END IF;

    IF v_period.status <> 'CLOSED' THEN
        RAISE EXCEPTION 'Somente competências fechadas podem ser reabertas (status atual: %).', v_period.status;
    END IF;

    UPDATE public.vehicle_rental_periods p
    SET status = CASE
            WHEN EXISTS (
                SELECT 1 FROM public.vehicles_rentals_allocations a
                WHERE a.period_id = p.id
            ) THEN 'ALLOCATED'
            ELSE 'CALCULATED'
        END,
        updated_user_id = p_user_id,
        updated_at = now()
    WHERE p.id = v_period.id;

    RETURN QUERY
    SELECT p.* FROM public.vehicle_rental_periods p
    WHERE p.id = v_period.id;
END;
$$;

-- 8.8 Estorno: remove as linhas 'rental' e as allocations e volta o
--     período para CALCULATED (recalcula custo/km com o Km vigente).
CREATE OR REPLACE FUNCTION public.fc_vehicle_rental_revert(
    p_vehicle_id bigint,
    p_reference_month date,
    p_user_id bigint DEFAULT NULL
) RETURNS SETOF public.vehicle_rental_periods
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_month date := (date_trunc('month', p_reference_month::timestamp))::date;
    v_period public.vehicle_rental_periods%ROWTYPE;
    v_total_km bigint;
    v_rate numeric;
    v_alloc numeric;
BEGIN
    PERFORM set_config('app.vehicle_rental_write', '1', true);

    SELECT p.* INTO v_period
    FROM public.vehicle_rental_periods p
    WHERE p.vehicle_id = p_vehicle_id
      AND p.reference_month = v_month
    FOR UPDATE;

    IF v_period.id IS NULL THEN
        RAISE EXCEPTION 'Competência % do veículo % não existe.', v_month, p_vehicle_id;
    END IF;

    IF v_period.status = 'CLOSED' THEN
        RAISE EXCEPTION 'Competência % está fechada: reabra antes de estornar.', v_month;
    END IF;

    IF v_period.status <> 'ALLOCATED' THEN
        RAISE EXCEPTION 'Competência % não tem rateio alocado (status: %).', v_month, v_period.status;
    END IF;

    -- Remove as linhas de rateio (o rollup recalcula ov_vehicles_value)
    DELETE FROM public.orders_visits_vehicles ovv
    WHERE ovv.id IN (
        SELECT a.rental_ovv_id
        FROM public.vehicles_rentals_allocations a
        WHERE a.period_id = v_period.id
          AND a.rental_ovv_id IS NOT NULL
    );

    DELETE FROM public.vehicles_rentals_allocations a
    WHERE a.period_id = v_period.id;

    -- Recalcula com o Km vigente (mantém a competência CALCULATED)
    SELECT COALESCE(sum(ovv.amount), 0)::bigint
    INTO v_total_km
    FROM public.orders_visits_vehicles ovv
    JOIN public.orders_visits ovs ON ovs.id = ovv.ov_id
    WHERE ovv.vehicle_id = p_vehicle_id
      AND NOT ovv.is_deleted
      AND ovv.cost_type = 'odometer'
      AND ovv.amount > 0
      AND COALESCE(ovv.created_at, ovs.ov_created_at) >= v_month
      AND COALESCE(ovv.created_at, ovs.ov_created_at) < v_month + interval '1 month';

    v_rate := CASE
        WHEN v_total_km > 0 THEN round(v_period.contract_value / v_total_km::numeric, 6)
        ELSE NULL
    END;

    SELECT COALESCE(sum(round(ovv.amount * v_rate, 2)), 0)
    INTO v_alloc
    FROM public.orders_visits_vehicles ovv
    JOIN public.orders_visits ovs ON ovs.id = ovv.ov_id
    WHERE ovv.vehicle_id = p_vehicle_id
      AND NOT ovv.is_deleted
      AND ovv.cost_type = 'odometer'
      AND ovv.amount > 0
      AND COALESCE(ovv.created_at, ovs.ov_created_at) >= v_month
      AND COALESCE(ovv.created_at, ovs.ov_created_at) < v_month + interval '1 month';

    UPDATE public.vehicle_rental_periods p
    SET total_km = v_total_km,
        cost_per_km = v_rate,
        allocated_value = v_alloc,
        idle_value = p.contract_value - v_alloc,
        status = 'CALCULATED',
        updated_user_id = p_user_id,
        updated_at = now()
    WHERE p.id = v_period.id;

    RETURN QUERY
    SELECT p.* FROM public.vehicle_rental_periods p
    WHERE p.id = v_period.id;
END;
$$;

-- 8.9 Permissões das RPCs (leitura/escrita para usuários autenticados;
--     anon e público sem acesso)
REVOKE ALL ON FUNCTION public.fc_vehicle_rental_contract(bigint, date) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.fc_vehicle_rental_summary(date) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.fc_vehicle_rental_detail(bigint, date) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.fc_vehicle_rental_calculate(bigint, date, bigint) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.fc_vehicle_rental_allocate(bigint, date, bigint) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.fc_vehicle_rental_close(bigint, date, bigint) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.fc_vehicle_rental_reopen(bigint, date, bigint) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.fc_vehicle_rental_revert(bigint, date, bigint) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.fc_vehicle_rental_contract(bigint, date) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.fc_vehicle_rental_summary(date) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.fc_vehicle_rental_detail(bigint, date) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.fc_vehicle_rental_calculate(bigint, date, bigint) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.fc_vehicle_rental_allocate(bigint, date, bigint) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.fc_vehicle_rental_close(bigint, date, bigint) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.fc_vehicle_rental_reopen(bigint, date, bigint) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.fc_vehicle_rental_revert(bigint, date, bigint) TO authenticated, service_role;

-- ------------------------------------------------------------
-- 9. View de veículos da visita: acrescenta cost_type ao final
--    (CREATE OR REPLACE aditivo, sem DROP CASCADE — AGENTS.md;
--     preserva security_invoker e todos os grants existentes)
--    ATENÇÃO: precisa vir ANTES da função da seção 10, que passa
--    a ler cost_type a partir desta view.
-- ------------------------------------------------------------
CREATE OR REPLACE VIEW public.v_orders_visits_vehicles WITH (security_invoker='true') AS
 SELECT ovv.id,
    ovv.ov_id,
    ovv.vehicle_id,
    v.description AS vehicle_description,
    v.plates AS vehicle_plates,
    v.unit,
    ovv.recorder_start,
    ovv.recorder_end,
    ovv.amount,
    ovv.value_unit,
    ovv.value_total,
    ovv.discount,
    ovv.version_mode,
    ovv.cost_type
   FROM (public.orders_visits_vehicles ovv
     JOIN public.vehicles v ON ((v.id = ovv.vehicle_id)))
  WHERE (ovv.is_deleted = false);

GRANT ALL ON TABLE public.v_orders_visits_vehicles TO postgres;
GRANT ALL ON TABLE public.v_orders_visits_vehicles TO anon;
GRANT ALL ON TABLE public.v_orders_visits_vehicles TO authenticated;
GRANT ALL ON TABLE public.v_orders_visits_vehicles TO service_role;

-- ------------------------------------------------------------
-- 10. Resumo financeiro por visita: separa origem (Km x Rateio).
--     DROP sem CASCADE (regra do AGENTS.md): nenhum caller no front-end
--     nem no banco; se houver dependente, a migration falha com erro claro.
-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS public.fc_financial_orders_visits_vehicles_sum(integer[]);

CREATE FUNCTION public.fc_financial_orders_visits_vehicles_sum(ov_ids integer[])
RETURNS TABLE(vehicle_description text, unit text, value_unit numeric, discount numeric, cost_type character varying, amount_total numeric, value_total numeric)
    LANGUAGE sql
    SET search_path TO 'public'
    AS $$
  SELECT
    vos.vehicle_description,
    vos.unit,
    vos.value_unit,
    vos.discount,
    vos.cost_type,
    SUM(vos.amount) AS amount_total,
    SUM(vos.value_total) AS value_total
  FROM public.v_orders_visits_vehicles vos
  WHERE vos.ov_id = ANY(ov_ids)
  GROUP BY
    vos.vehicle_description,
    vos.unit,
    vos.value_unit,
    vos.discount,
    vos.cost_type
  ORDER BY
    vos.vehicle_description,
    vos.cost_type;
$$;

GRANT ALL ON FUNCTION public.fc_financial_orders_visits_vehicles_sum(integer[]) TO postgres;
GRANT ALL ON FUNCTION public.fc_financial_orders_visits_vehicles_sum(integer[]) TO anon;
GRANT ALL ON FUNCTION public.fc_financial_orders_visits_vehicles_sum(integer[]) TO authenticated;
GRANT ALL ON FUNCTION public.fc_financial_orders_visits_vehicles_sum(integer[]) TO service_role;

-- ------------------------------------------------------------
-- 11. Rotas de permissão
-- ------------------------------------------------------------
-- 0. Garante que a identidade de id está à frente do maior id existente
SELECT setval(
    pg_get_serial_sequence('cfg_routes', 'id'),
    GREATEST(
        (SELECT COALESCE(MAX(id), 1) FROM cfg_routes),
        (SELECT last_value FROM cfg_routes_id_seq)
    )
);

-- 11.1 Apuração de aluguel (atrás de Transporte/Ordens)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM cfg_routes WHERE route_key = 'transport_rental_apportionment') THEN
    INSERT INTO cfg_routes (route_key, route_path, description, icon, parent_id, order_index, is_available)
    VALUES (
        'transport_rental_apportionment',
        '/transport/rental-apportionment',
        'Apuração de Aluguel Veicular',
        'local_shipping',
        (SELECT id FROM cfg_routes WHERE route_key = 'orders'),
        20,
        true
    );
    RAISE NOTICE 'Rota transport_rental_apportionment criada com sucesso';
  ELSE
    RAISE NOTICE 'Rota transport_rental_apportionment já existe, ignorando';
  END IF;
END $$;

-- 11.2 Tipos de custo veicular (Configurações)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM cfg_routes WHERE route_key = 'settings_vehicle_cost_types') THEN
    INSERT INTO cfg_routes (route_key, route_path, description, icon, parent_id, order_index, is_available)
    VALUES (
        'settings_vehicle_cost_types',
        '/settings/vehicle-cost-types',
        'Tipos de Custo Veicular',
        'sell',
        (SELECT id FROM cfg_routes WHERE route_key = 'settings'),
        98,
        true
    );
    RAISE NOTICE 'Rota settings_vehicle_cost_types criada com sucesso';
  ELSE
    RAISE NOTICE 'Rota settings_vehicle_cost_types já existe, ignorando';
  END IF;
END $$;

-- 11.3 Concede view aos perfis que já enxergam a rota irmã/pai
--      (evita que a tela fique inacessível até alguém montar a
--       matriz de permissões; ajustável depois em Configurações)
INSERT INTO cfg_profiles_access (profile_id, route_id, can_view, can_create, can_edit, can_delete, can_search)
SELECT pa.profile_id, nova.id, true, false, false, false, false
FROM cfg_profiles_access pa
JOIN cfg_routes r ON r.id = pa.route_id
JOIN cfg_routes nova ON nova.route_key = 'transport_rental_apportionment'
WHERE r.route_key = 'orders_visits_financial_approve'
  AND pa.can_view = true
ON CONFLICT (profile_id, route_id) DO NOTHING;

INSERT INTO cfg_profiles_access (profile_id, route_id, can_view, can_create, can_edit, can_delete, can_search)
SELECT pa.profile_id, nova.id, true, false, false, false, false
FROM cfg_profiles_access pa
JOIN cfg_routes r ON r.id = pa.route_id
JOIN cfg_routes nova ON nova.route_key = 'settings_vehicle_cost_types'
WHERE r.route_key = 'settings'
  AND pa.can_view = true
ON CONFLICT (profile_id, route_id) DO NOTHING;

-- ============================================================
-- FIM DA MIGRATION 20261008_create_vehicle_rental_rateio.sql
-- ============================================================
