-- ============================================
-- MIGRAÇÃO: Sistema de Gamificação de Líderes
-- Data: 2026-08-07
-- ============================================

-- 1. View: Score individual por visita
DROP VIEW IF EXISTS public.v_order_visit_scores;

CREATE OR REPLACE VIEW public.v_order_visit_scores AS
SELECT
    ov.id AS ov_id,
    ov.o_id AS order_id,
    ov.ov_team_leader_id AS leader_id,
    u.name_short AS leader_name,
    u.team_id AS leader_team_id,
    t.description AS team_name,
    t.department_id AS leader_department_id,
    d.description AS department_name,
    ov.ov_started_at,
    ov.ov_ended_at,
    EXTRACT(YEAR FROM ov.ov_ended_at)::int AS score_year,
    EXTRACT(MONTH FROM ov.ov_ended_at)::int AS score_month,
    -- Total de requisitos avaliados nesta visita
    COUNT(ove.id)::int AS total_evaluations,
    -- Requisitos descumpridos (was_applied = true significa que NÃO cumpriu)
    COUNT(CASE WHEN ove.was_applied = true THEN 1 END)::int AS failed_evaluations,
    -- Score de penalidade: soma dos pesos dos requisitos descumpridos
    COALESCE(SUM(CASE WHEN ove.was_applied = true THEN cer.weight ELSE 0 END), 0)::numeric(10,2) AS penalty_score,
    -- Score máximo possível (soma de todos os weights do contrato para esta visita)
    COALESCE(SUM(cer.weight), 0)::numeric(10,2) AS max_possible_score,
    -- Score de conformidade: 100 = perfeito (zero descumprimentos), 0 = todas falharam
    CASE
        WHEN COALESCE(SUM(cer.weight), 0) = 0 THEN 100.00
        ELSE ROUND(
            (1.0 - COALESCE(SUM(CASE WHEN ove.was_applied = true THEN cer.weight ELSE 0 END), 0)
                / NULLIF(SUM(cer.weight), 0)::numeric) * 100, 2
        )
    END AS compliance_score
FROM public.orders_visits ov
JOIN public.users u ON u.id = ov.ov_team_leader_id
JOIN public.cfg_teams t ON t.id = u.team_id
JOIN public.cfg_departments d ON d.id = t.department_id
LEFT JOIN public.orders_visits_evaluations ove ON ove.ov_id = ov.id
LEFT JOIN public.contracts_evaluation_requirements cer ON cer.id = ove.contract_evaluation_id
WHERE ov.ov_status_id = 2  -- apenas visitas encerradas
  AND ov.ov_ended_at IS NOT NULL
GROUP BY ov.id, ov.o_id, ov.ov_team_leader_id, u.name_short, u.team_id,
         t.description, t.department_id, d.description, ov.ov_started_at, ov.ov_ended_at;


-- 2. Tabela: Snapshot mensal por líder (agregado)
CREATE TABLE IF NOT EXISTS public.leader_monthly_scores (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    leader_id bigint NOT NULL,
    leader_name character varying,
    department_id bigint NOT NULL,
    department_name character varying,
    score_year int NOT NULL,
    score_month int NOT NULL,
    total_visits int NOT NULL DEFAULT 0,
    total_evaluations int NOT NULL DEFAULT 0,
    failed_evaluations int NOT NULL DEFAULT 0,
    total_penalty_score numeric(10,2) NOT NULL DEFAULT 0,
    avg_compliance_score numeric(5,2) NOT NULL DEFAULT 0,
    best_compliance_score numeric(5,2) NOT NULL DEFAULT 0,
    worst_compliance_score numeric(5,2) NOT NULL DEFAULT 0,
    ranking_position int,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT leader_monthly_scores_pkey PRIMARY KEY (id),
    CONSTRAINT leader_monthly_scores_leader_id_fkey FOREIGN KEY (leader_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT leader_monthly_scores_department_id_fkey FOREIGN KEY (department_id)
        REFERENCES public.cfg_departments (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT leader_monthly_scores_unique UNIQUE (leader_id, score_year, score_month)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_leader_monthly_scores_dept_period
    ON public.leader_monthly_scores USING btree (department_id, score_year, score_month);

CREATE INDEX IF NOT EXISTS idx_leader_monthly_scores_leader
    ON public.leader_monthly_scores USING btree (leader_id);


-- 3. Tabela: Histórico detalhado (uma linha por visita avaliada)
CREATE TABLE IF NOT EXISTS public.leader_scores_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    leader_id bigint NOT NULL,
    ov_id bigint NOT NULL,
    order_id bigint,
    score_year int NOT NULL,
    score_month int NOT NULL,
    total_evaluations int NOT NULL DEFAULT 0,
    failed_evaluations int NOT NULL DEFAULT 0,
    penalty_score numeric(10,2) NOT NULL DEFAULT 0,
    max_possible_score numeric(10,2) NOT NULL DEFAULT 0,
    compliance_score numeric(5,2) NOT NULL DEFAULT 100,
    evaluated_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT leader_scores_history_pkey PRIMARY KEY (id),
    CONSTRAINT leader_scores_history_leader_id_fkey FOREIGN KEY (leader_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT leader_scores_history_ov_id_fkey FOREIGN KEY (ov_id)
        REFERENCES public.orders_visits (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT leader_scores_history_unique UNIQUE (ov_id)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_leader_scores_history_leader_period
    ON public.leader_scores_history USING btree (leader_id, score_year, score_month);

CREATE INDEX IF NOT EXISTS idx_leader_scores_history_dept_period
    ON public.leader_scores_history USING btree (leader_id, score_year, score_month);


-- 4. Tabela: Badges / Conquistas
CREATE TABLE IF NOT EXISTS public.leader_score_badges (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    leader_id bigint NOT NULL,
    badge_code character varying(50) NOT NULL,
    badge_name character varying(100) NOT NULL,
    badge_description text,
    score_year int NOT NULL,
    score_month int NOT NULL,
    earned_at timestamp without time zone DEFAULT now(),
    CONSTRAINT leader_score_badges_pkey PRIMARY KEY (id),
    CONSTRAINT leader_score_badges_leader_id_fkey FOREIGN KEY (leader_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_leader_score_badges_leader
    ON public.leader_score_badges USING btree (leader_id);

CREATE INDEX IF NOT EXISTS idx_leader_score_badges_period
    ON public.leader_score_badges USING btree (score_year, score_month);


-- 5. View: Ranking de líderes por departamento e período
DROP VIEW IF EXISTS public.v_leader_ranking;

CREATE OR REPLACE VIEW public.v_leader_ranking AS
SELECT
    lms.*,
    -- Tendência vs mês anterior
    prev.avg_compliance_score AS prev_month_compliance,
    CASE
        WHEN prev.avg_compliance_score IS NULL THEN 'stable'
        WHEN lms.avg_compliance_score > prev.avg_compliance_score THEN 'up'
        WHEN lms.avg_compliance_score < prev.avg_compliance_score THEN 'down'
        ELSE 'stable'
    END AS trend,
    -- Posição anterior
    prev.ranking_position AS prev_ranking_position,
    -- Variação da posição
    CASE
        WHEN prev.ranking_position IS NULL OR lms.ranking_position IS NULL THEN NULL
        WHEN prev.ranking_position > lms.ranking_position THEN prev.ranking_position - lms.ranking_position  -- subiu
        WHEN prev.ranking_position < lms.ranking_position THEN -(lms.ranking_position - prev.ranking_position)  -- desceu
        ELSE 0
    END AS position_change
FROM public.leader_monthly_scores lms
LEFT JOIN public.leader_monthly_scores prev
    ON prev.leader_id = lms.leader_id
    AND prev.score_year = CASE WHEN lms.score_month = 1 THEN lms.score_year - 1 ELSE lms.score_year END
    AND prev.score_month = CASE WHEN lms.score_month = 1 THEN 12 ELSE lms.score_month - 1 END;


-- 6. Função: Recalcular scores de um líder para um mês
CREATE OR REPLACE FUNCTION public.recalculate_leader_monthly_score(
    p_leader_id bigint,
    p_year int,
    p_month int
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    v_total_visits int;
    v_total_evals int;
    v_failed_evals int;
    v_total_penalty numeric(10,2);
    v_avg_compliance numeric(5,2);
    v_best_compliance numeric(5,2);
    v_worst_compliance numeric(5,2);
    v_leader_name varchar;
    v_dept_id bigint;
    v_dept_name varchar;
BEGIN
    -- Buscar dados do líder
    SELECT u.name_short, u.team_id, d.id, d.description
    INTO v_leader_name, v_dept_id, v_dept_id, v_dept_name
    FROM public.users u
    JOIN public.cfg_teams t ON t.id = u.team_id
    JOIN public.cfg_departments d ON d.id = t.department_id
    WHERE u.id = p_leader_id;

    -- Agregar scores do mês
    SELECT
        COUNT(*)::int,
        COALESCE(SUM(total_evaluations), 0)::int,
        COALESCE(SUM(failed_evaluations), 0)::int,
        COALESCE(SUM(penalty_score), 0)::numeric(10,2),
        CASE WHEN COUNT(*) = 0 THEN 0 ELSE ROUND(AVG(compliance_score), 2) END,
        COALESCE(MAX(compliance_score), 0)::numeric(5,2),
        COALESCE(MIN(compliance_score), 0)::numeric(5,2)
    INTO v_total_visits, v_total_evals, v_failed_evals, v_total_penalty,
         v_avg_compliance, v_best_compliance, v_worst_compliance
    FROM public.v_order_visit_scores
    WHERE leader_id = p_leader_id
      AND score_year = p_year
      AND score_month = p_month;

    -- Upsert no snapshot mensal
    INSERT INTO public.leader_monthly_scores (
        leader_id, leader_name, department_id, department_name,
        score_year, score_month,
        total_visits, total_evaluations, failed_evaluations,
        total_penalty_score, avg_compliance_score,
        best_compliance_score, worst_compliance_score,
        updated_at
    ) VALUES (
        p_leader_id, v_leader_name, v_dept_id, v_dept_name,
        p_year, p_month,
        v_total_visits, v_total_evals, v_failed_evals,
        v_total_penalty, v_avg_compliance,
        v_best_compliance, v_worst_compliance,
        now()
    )
    ON CONFLICT (leader_id, score_year, score_month)
    DO UPDATE SET
        leader_name = EXCLUDED.leader_name,
        department_name = EXCLUDED.department_name,
        total_visits = EXCLUDED.total_visits,
        total_evaluations = EXCLUDED.total_evaluations,
        failed_evaluations = EXCLUDED.failed_evaluations,
        total_penalty_score = EXCLUDED.total_penalty_score,
        avg_compliance_score = EXCLUDED.avg_compliance_score,
        best_compliance_score = EXCLUDED.best_compliance_score,
        worst_compliance_score = EXCLUDED.worst_compliance_score,
        updated_at = now();

    -- Upsert no histórico detalhado
    INSERT INTO public.leader_scores_history (
        leader_id, ov_id, order_id, score_year, score_month,
        total_evaluations, failed_evaluations, penalty_score,
        max_possible_score, compliance_score, evaluated_at
    )
    SELECT
        leader_id, ov_id, order_id, score_year, score_month,
        total_evaluations, failed_evaluations, penalty_score,
        max_possible_score, compliance_score, ov_ended_at
    FROM public.v_order_visit_scores
    WHERE leader_id = p_leader_id
      AND score_year = p_year
      AND score_month = p_month
    ON CONFLICT (ov_id)
    DO UPDATE SET
        total_evaluations = EXCLUDED.total_evaluations,
        failed_evaluations = EXCLUDED.failed_evaluations,
        penalty_score = EXCLUDED.penalty_score,
        max_possible_score = EXCLUDED.max_possible_score,
        compliance_score = EXCLUDED.compliance_score;

    -- Atualizar ranking por departamento
    WITH ranked AS (
        SELECT
            id,
            ROW_NUMBER() OVER (PARTITION BY department_id, score_year, score_month ORDER BY avg_compliance_score DESC, total_penalty_score ASC) AS new_rank
        FROM public.leader_monthly_scores
        WHERE department_id = v_dept_id
          AND score_year = p_year
          AND score_month = p_month
    )
    UPDATE public.leader_monthly_scores lms
    SET ranking_position = ranked.new_rank
    FROM ranked
    WHERE lms.id = ranked.id;
END;
$$;


-- 7. Função: Recalcular todos os líderes de um departamento/mês
CREATE OR REPLACE FUNCTION public.recalculate_department_scores(
    p_department_id bigint,
    p_year int,
    p_month int
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    rec RECORD;
BEGIN
    FOR rec IN
        SELECT DISTINCT ov.leader_id
        FROM public.v_order_visit_scores ov
        WHERE ov.leader_department_id = p_department_id
          AND ov.score_year = p_year
          AND ov.score_month = p_month
    LOOP
        PERFORM public.recalculate_leader_monthly_score(rec.leader_id, p_year, p_month);
    END LOOP;
END;
$$;


-- 8. Função: Recalcular TODOS os departamentos de um mês
CREATE OR REPLACE FUNCTION public.recalculate_all_scores(
    p_year int,
    p_month int
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    rec RECORD;
BEGIN
    FOR rec IN
        SELECT DISTINCT leader_department_id
        FROM public.v_order_visit_scores
        WHERE score_year = p_year
          AND score_month = p_month
    LOOP
        PERFORM public.recalculate_department_scores(rec.leader_department_id, p_year, p_month);
    END LOOP;
END;
$$;
