-- =====================================================
-- Migration: Create cfg_app_notices_workers + rota extra_workers
-- Date: 2026-10-03
-- Description: Durante um aviso (cfg_app_notices) em andamento,
--              registra a quantidade de trabalhadores extras
--              disponibilizados por unidade, escopado pela
--              company_id do usuário que lançou.
--
--              - Chave única (notice_id, unit_id, company_id):
--                companies diferentes podem lançar para a MESMA
--                unidade no mesmo aviso (exibição soma por unidade).
--              - Valor padrão 0, não negativo.
--              - Rota de permissão própria: extra_workers
--                (página "Trabalhadores Extras").
--
--              Aplicar manualmente no SQL Editor do Supabase.
--              Idempotente (seguro para reexecutar).
-- =====================================================

-- 1. Tabela de lançamentos ------------------------------------------
CREATE TABLE IF NOT EXISTS public.cfg_app_notices_workers (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id            integer NOT NULL
                              REFERENCES public.cfg_app_notices(id) ON DELETE CASCADE,
    company_id           bigint  NOT NULL
                              REFERENCES public.cfg_companies(id) ON DELETE CASCADE,
    unit_id              bigint  NOT NULL
                              REFERENCES public.units(id) ON DELETE CASCADE,
    workers_extra_amount integer NOT NULL DEFAULT 0
                              CONSTRAINT chk_notice_workers_amount CHECK (workers_extra_amount >= 0),
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now(),
    created_user_id      bigint,
    updated_user_id      bigint,
    CONSTRAINT uq_cfg_app_notices_workers
        UNIQUE (notice_id, unit_id, company_id)
);

COMMENT ON TABLE public.cfg_app_notices_workers IS
    'Trabalhadores extras disponibilizados por unidade durante um aviso ativo';
COMMENT ON COLUMN public.cfg_app_notices_workers.workers_extra_amount IS
    'Quantidade de trabalhadores extras informada pela company para a unidade no aviso';

-- 2. RLS ---------------------------------------------------------------
ALTER TABLE public.cfg_app_notices_workers ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    DROP POLICY IF EXISTS "authenticated can select cfg_app_notices_workers"
        ON public.cfg_app_notices_workers;
    DROP POLICY IF EXISTS "authenticated can insert cfg_app_notices_workers"
        ON public.cfg_app_notices_workers;
    DROP POLICY IF EXISTS "authenticated can update cfg_app_notices_workers"
        ON public.cfg_app_notices_workers;
    DROP POLICY IF EXISTS "authenticated can delete cfg_app_notices_workers"
        ON public.cfg_app_notices_workers;
END $$;

CREATE POLICY "authenticated can select cfg_app_notices_workers"
    ON public.cfg_app_notices_workers FOR SELECT
    TO authenticated USING (true);

CREATE POLICY "authenticated can insert cfg_app_notices_workers"
    ON public.cfg_app_notices_workers FOR INSERT
    TO authenticated WITH CHECK (true);

CREATE POLICY "authenticated can update cfg_app_notices_workers"
    ON public.cfg_app_notices_workers FOR UPDATE
    TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "authenticated can delete cfg_app_notices_workers"
    ON public.cfg_app_notices_workers FOR DELETE
    TO authenticated USING (true);

-- 3. Índices (FKs sem índice — padrão 20261003_fix_unindexed_fkeys_new_tables.sql)
-- cfg_app_notices_workers.notice_id
CREATE INDEX IF NOT EXISTS idx_cfg_app_notices_workers_notice_id
    ON public.cfg_app_notices_workers(notice_id);

-- cfg_app_notices_workers.company_id
CREATE INDEX IF NOT EXISTS idx_cfg_app_notices_workers_company_id
    ON public.cfg_app_notices_workers(company_id);

-- cfg_app_notices_workers.unit_id
CREATE INDEX IF NOT EXISTS idx_cfg_app_notices_workers_unit_id
    ON public.cfg_app_notices_workers(unit_id);

-- 4. Rota de permissão (padrão 20260927_add_materials_upload_route.sql)
--    Garante que a identidade de id está à frente do maior id existente
SELECT setval(
    pg_get_serial_sequence('cfg_routes', 'id'),
    GREATEST(
        (SELECT COALESCE(MAX(id), 1) FROM cfg_routes),
        (SELECT last_value FROM cfg_routes_id_seq)
    )
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM cfg_routes WHERE route_key = 'extra_workers') THEN
        INSERT INTO cfg_routes (route_key, route_path, description, icon, parent_id, order_index, is_available)
        VALUES (
            'extra_workers',
            '/notices/extra-workers',
            'Trabalhadores Extras',
            'groups',
            (SELECT id FROM cfg_routes WHERE route_key = 'app_notices'),
            60,
            true
        );
        RAISE NOTICE 'Rota extra_workers criada com sucesso';
    ELSE
        RAISE NOTICE 'Rota extra_workers já existe, ignorando';
    END IF;
END $$;

-- Concede view aos perfis que já possuem view em app_notices
INSERT INTO cfg_profiles_access (profile_id, route_id, can_view, can_create, can_edit, can_delete, can_search)
SELECT pa.profile_id, nw.id, true, false, true, false, false
FROM cfg_profiles_access pa
JOIN cfg_routes r ON r.id = pa.route_id
CROSS JOIN (SELECT id FROM cfg_routes WHERE route_key = 'extra_workers') nw
WHERE r.route_key = 'app_notices'
  AND pa.can_view = true
ON CONFLICT (profile_id, route_id) DO NOTHING;
