-- ============================================================
-- Migration: Contratos de R$/km (custo operacional por Km)
-- Date: 2026-10-10
-- Description:
--   O R$/km (custo operacional por Km) deixa de ser um valor estático
--   em vehicles.value_unit e passa a ser um CONTRATO COM VIGÊNCIA,
--   com o mesmo modelo dos contratos de aluguel:
--
--     • tabela cfg_vehicle_rate_contracts (veículo, R$/km, vigência,
--       ativo) — espelho de cfg_vehicles_rentals_contracts;
--     • fc_vehicle_rate_contract(vehicle_id, on_date) devolve o
--       contrato vigente NA DATA (mais recente vence; conflito se >1);
--     • o trigger fc_orders_visits_vehicles_before_save resolve o
--       preço da linha de odômetro pelo contrato vigente na data da
--     linha (created_at da linha; fallback: data da visita);
--     • informar Km em veículo SEM contrato vigente passa a ser
--       BLOQUEADO (amount > 0). amount = 0 (apenas adicionar o
--       veículo à visita) continua livre;
--     • vehicles.value_unit permanece como VALOR PADRÃO (origem do
--       import Manus) e é a fonte do backfill.
--
--   Semântica redefinida (documentada em UI/docs):
--     R$/km = custo OPERACIONAL por Km que NÃO inclui aluguel nem
--     despesas variáveis (combustível, pedágio, manutenção, seguro…
--     entram pela apuração como despesas do mês).
--
--   Backfill: todo veículo não-deletado recebe 1 contrato automático
--     • início = 1º dia do mês da 1ª linha de visita (ou 1º do mês
--       corrente, se o veículo ainda não tem visitas);
--     • fim    = 31/12/2026 (vigência encerra; depois disso um novo
--       contrato é exigido — a mensagem do trigger orienta);
--     • valor  = vehicles.value_unit atual.
--
--   Conteúdo:
--     1. cfg_vehicle_rate_contracts              (tabela + RLS/grants)
--     2. fc_vehicle_rate_contract(bigint, date)  (resolve por data)
--     3. Backfill automático de contratos        (idempotente)
--     4. fc_orders_visits_vehicles_before_save   (odometer usa o
--        contrato vigente na data; amount > 0 sem contrato ⇒ erro)
--     5. Rota transport_rate_contracts + grants
--
--   Aplicação MANUAL no SQL Editor do Supabase (regra do AGENTS.md),
--   DEPOIS de 20261008_create_vehicle_rental_rateio.sql e
--   20261009_add_vehicle_monthly_expenses.sql.
--   Idempotente: pode ser re-executada com segurança.
--   Nenhum DROP ... CASCADE nesta migration (regra do AGENTS.md).
--
--   Validação: dev/supabase/validate_rate_contracts.sql
-- ============================================================

-- ------------------------------------------------------------
-- 1. Contrato de R$/km por veículo (vigência)
--    Mesmo modelo de cfg_vehicles_rentals_contracts (Fase 1).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cfg_vehicle_rate_contracts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    vehicle_id bigint NOT NULL,
    value_unit numeric(14,6) NOT NULL,
    start_date date NOT NULL,
    end_date date,
    active boolean DEFAULT true NOT NULL,
    description text,
    is_deleted boolean DEFAULT false NOT NULL,
    created_user_id bigint,
    created_at timestamp without time zone DEFAULT now(),
    updated_user_id bigint,
    updated_at timestamp without time zone,
    CONSTRAINT cfg_vehicle_rate_contracts_pkey PRIMARY KEY (id),
    CONSTRAINT cfg_vehicle_rate_contracts_value_ck CHECK (value_unit >= 0),
    CONSTRAINT cfg_vehicle_rate_contracts_dates_ck CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT cfg_vehicle_rate_contracts_vehicle_fk
        FOREIGN KEY (vehicle_id) REFERENCES public.vehicles (id) ON DELETE CASCADE
);

COMMENT ON TABLE public.cfg_vehicle_rate_contracts IS
    'Contrato(s) de R$/km (custo operacional por Km) de veículo. Vigências sobrepostas para o mesmo veículo/data são permitidas na tabela; o trigger do odômetro escolhe a mais recente e o conflito é sinalizado. NÃO inclui aluguel nem despesas variáveis.';
COMMENT ON COLUMN public.cfg_vehicle_rate_contracts.value_unit IS
    'Custo operacional por Km (R$/km). Usado pelo trigger fc_orders_visits_vehicles_before_save para precificar linhas de odômetro (amount > 0 exige contrato vigente na data da linha).';

CREATE INDEX IF NOT EXISTS idx_cfg_vehicle_rate_contracts_vehicle
    ON public.cfg_vehicle_rate_contracts (vehicle_id)
    WHERE active AND NOT is_deleted;

CREATE INDEX IF NOT EXISTS idx_cfg_vehicle_rate_contracts_vigency
    ON public.cfg_vehicle_rate_contracts (vehicle_id, start_date, end_date)
    WHERE active AND NOT is_deleted;

ALTER TABLE public.cfg_vehicle_rate_contracts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Universal Access" ON public.cfg_vehicle_rate_contracts;
CREATE POLICY "Universal Access" ON public.cfg_vehicle_rate_contracts
    USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public.cfg_vehicle_rate_contracts TO authenticated, service_role;
REVOKE ALL ON TABLE public.cfg_vehicle_rate_contracts FROM anon;
GRANT USAGE ON SEQUENCE public.cfg_vehicle_rate_contracts_id_seq TO authenticated, service_role;

-- ------------------------------------------------------------
-- 2. Contrato de R$/km vigente em uma DATA
--    Mesmo algoritmo de fc_vehicle_rental_contract (Fase 1), mas
--    resolvido por data (não por mês): start_date <= on_date e
--    (end_date is null ou end_date >= on_date). Mais de um contrato
--    vigente na data ⇒ o mais recente vence e o conflito é sinalizado.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fc_vehicle_rate_contract(
    p_vehicle_id bigint,
    p_on_date date
) RETURNS TABLE (
    contract_id bigint,
    value_unit numeric,
    has_conflict boolean
)
    LANGUAGE plpgsql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
BEGIN
    RETURN QUERY
    SELECT c.id,
           c.value_unit,
           (count(*) OVER ()) > 1
    FROM public.cfg_vehicle_rate_contracts c
    WHERE c.vehicle_id = p_vehicle_id
      AND c.active
      AND NOT c.is_deleted
      AND c.start_date <= p_on_date
      AND (c.end_date IS NULL OR c.end_date >= p_on_date)
    ORDER BY c.start_date DESC, c.id DESC
    LIMIT 1;
END;
$$;

REVOKE ALL ON FUNCTION public.fc_vehicle_rate_contract(bigint, date) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.fc_vehicle_rate_contract(bigint, date) TO authenticated, service_role;

-- ------------------------------------------------------------
-- 3. Backfill automático (idempotente)
--    Todo veículo não-deletado sem nenhum contrato recebe 1 contrato:
--      início = 1º do mês da 1ª linha de visita (ou 1º do mês corrente)
--      fim    = 31/12/2026
--      valor  = vehicles.value_unit (valor padrão / import Manus)
--    Veículos que já têm contrato (inclusive criados por execuções
--    anteriores) são ignorados.
-- ------------------------------------------------------------
DO $$
DECLARE
    v record;
    v_start date;
BEGIN
    FOR v IN
        SELECT ve.id,
               ve.value_unit,
               (
                   SELECT min(COALESCE(ovv.created_at, ovs.ov_created_at))
                   FROM public.orders_visits_vehicles ovv
                   JOIN public.orders_visits ovs ON ovs.id = ovv.ov_id
                   WHERE ovv.vehicle_id = ve.id
                     AND NOT ovv.is_deleted
               ) AS first_at
        FROM public.vehicles ve
        WHERE NOT ve.is_deleted
          AND NOT EXISTS (
              SELECT 1
              FROM public.cfg_vehicle_rate_contracts rc
              WHERE rc.vehicle_id = ve.id
                AND NOT rc.is_deleted
          )
    LOOP
        v_start := CASE
            WHEN v.first_at IS NOT NULL THEN date_trunc('month', v.first_at)::date
            ELSE date_trunc('month', now())::date
        END;

        INSERT INTO public.cfg_vehicle_rate_contracts (
            vehicle_id, value_unit, start_date, end_date, active,
            description, created_at
        ) VALUES (
            v.id, COALESCE(v.value_unit, 0), v_start, DATE '2026-12-31', true,
            'Contrato gerado automaticamente (migração 20261010)', now()
        );
    END LOOP;
END $$;

-- ------------------------------------------------------------
-- 4. Recria o trigger BEFORE — MESMA assinatura, corpo da Fase 2
--    (20261009) preservado, com o ramo odometer passando a resolver
--    o preço pelo contrato de R$/km vigente na data da linha:
--      • conversion branch (odometer <-> rate) intacta;
--      • rental/variable intactos;
--      • 'rate' intacto (nunca recalcula);
--      • odometer: amount > 0 EXIGE contrato vigente (erro claro);
--        amount = 0 (apenas adicionando o veículo) usa o valor
--        padrão de vehicles.value_unit para exibição.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fc_orders_visits_vehicles_before_save() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'public'
    AS $$
DECLARE
    v_price numeric;
    v_on_date date;
BEGIN

    -- Conversão de origem feita pela apuração (odometer <-> rate):
    -- só cost_type muda; amount/value_unit/value_total/recorder e
    -- desconto ficam intactos (o rollup recalcula o mesmo total).
    IF TG_OP = 'UPDATE'
       AND NEW.cost_type IS DISTINCT FROM OLD.cost_type
       AND NEW.ov_id IS NOT DISTINCT FROM OLD.ov_id
       AND NEW.vehicle_id IS NOT DISTINCT FROM OLD.vehicle_id
       AND NEW.recorder_start IS NOT DISTINCT FROM OLD.recorder_start
       AND NEW.recorder_end IS NOT DISTINCT FROM OLD.recorder_end
       AND NEW.amount IS NOT DISTINCT FROM OLD.amount
       AND NEW.discount IS NOT DISTINCT FROM OLD.discount
       AND NEW.is_deleted IS NOT DISTINCT FROM OLD.is_deleted THEN
        RETURN NEW;
    END IF;

    -- Linhas de rateio/despesa não têm odômetro: preserva amount/value_unit
    -- informados e recalcula apenas value_total.
    IF NEW.cost_type IN ('rental', 'variable') THEN
        NEW.recorder_start := NULL;
        NEW.recorder_end   := NULL;
        NEW.value_unit     := COALESCE(NEW.value_unit, 0);
        NEW.amount         := COALESCE(NEW.amount, 0);
        NEW.value_total    := ROUND(
            NEW.amount * NEW.value_unit * COALESCE(NEW.discount, 1), 2
        );
        RETURN NEW;
    END IF;

    -- Linha já convertida para 'rate': jamais recalcula (só a RPC de
    -- estorno devolve a 'odometer'; fora do flag o guard bloqueia)
    IF NEW.cost_type = 'rate' THEN
        RETURN NEW;
    END IF;

    -- Ramo odometer --------------------------------------------------
    -- Data âncora: created_at da linha (estável entre updates),
    -- fallback da data da visita, depois hoje.
    v_on_date := COALESCE(
        NEW.created_at::date,
        (
            SELECT ovs.ov_created_at::date
            FROM public.orders_visits ovs
            WHERE ovs.id = NEW.ov_id
        ),
        now()::date
    );

    NEW.amount :=
        GREATEST(
            COALESCE(NEW.recorder_end,0)
            - COALESCE(NEW.recorder_start,0),
            0
        );

    -- Preço: contrato de R$/km vigente na data da linha
    SELECT c.value_unit
    INTO v_price
    FROM public.fc_vehicle_rate_contract(NEW.vehicle_id, v_on_date) c;

    IF v_price IS NULL THEN
        -- Sem contrato vigente: só é permitido ter Km a zero.
        IF NEW.amount > 0 THEN
            RAISE EXCEPTION 'Veículo (%) sem contrato de R$/km vigente em % — cadastre um contrato (Apuração > Contratos de R$/km) antes de informar o Km.',
                COALESCE(
                    (SELECT ve.description FROM public.vehicles ve WHERE ve.id = NEW.vehicle_id),
                    NEW.vehicle_id::text
                ),
                to_char(v_on_date, 'DD/MM/YYYY');
        END IF;
        -- amount = 0 (apenas cadastrando o veículo na visita):
        -- usa o valor padrão do cadastro para exibição.
        SELECT value_unit
        INTO v_price
        FROM public.vehicles
        WHERE id = NEW.vehicle_id;
    END IF;

    NEW.value_unit := COALESCE(v_price, 0);

    NEW.value_total :=
        NEW.amount
        * NEW.value_unit
        * COALESCE(NEW.discount,1);

    RETURN NEW;

END;
$$;

-- ------------------------------------------------------------
-- 5. Rota de permissão (Contratos de R$/km)
--    Mesmo padrão das rotas da Fase 1 (20261008 §11):
--    identidade de id à frente do maior id + grants copiando os
--    perfis que já veem a rota irmã transport_rental_apportionment.
-- ------------------------------------------------------------
SELECT setval(
    pg_get_serial_sequence('cfg_routes', 'id'),
    GREATEST(
        (SELECT COALESCE(MAX(id), 1) FROM cfg_routes),
        (SELECT last_value FROM cfg_routes_id_seq)
    )
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM cfg_routes WHERE route_key = 'transport_rate_contracts') THEN
    INSERT INTO cfg_routes (route_key, route_path, description, icon, parent_id, order_index, is_available)
    VALUES (
        'transport_rate_contracts',
        '/transport/rate-contracts',
        'Contratos de R$/km Veicular',
        'speed',
        (SELECT id FROM cfg_routes WHERE route_key = 'orders'),
        21,
        true
    );
    RAISE NOTICE 'Rota transport_rate_contracts criada com sucesso';
  ELSE
    RAISE NOTICE 'Rota transport_rate_contracts já existe, ignorando';
  END IF;
END $$;

INSERT INTO cfg_profiles_access (profile_id, route_id, can_view, can_create, can_edit, can_delete, can_search)
SELECT pa.profile_id, nova.id, true, false, false, false, false
FROM cfg_profiles_access pa
JOIN cfg_routes r ON r.id = pa.route_id
JOIN cfg_routes nova ON nova.route_key = 'transport_rate_contracts'
WHERE r.route_key = 'transport_rental_apportionment'
  AND pa.can_view = true
ON CONFLICT (profile_id, route_id) DO NOTHING;

-- ============================================================
-- FIM DA MIGRATION 20261010_add_vehicle_rate_contracts.sql
-- ============================================================
