-- =============================================================================
-- Migration: Create cfg_materials_types table and add type_id to materials
-- Date: 2026-07-01
-- =============================================================================

-- 1. Create cfg_materials_types table
CREATE TABLE IF NOT EXISTS public.cfg_materials_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code character varying NULL,
    description character varying NULL,
    CONSTRAINT cfg_materials_types_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- 2. Enable RLS for cfg_materials_types
ALTER TABLE public.cfg_materials_types ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS policies for cfg_materials_types
CREATE POLICY "Allow all authenticated read cfg_materials_types"
    ON public.cfg_materials_types
    FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Allow all authenticated insert cfg_materials_types"
    ON public.cfg_materials_types
    FOR INSERT
    TO authenticated
    WITH CHECK (true);

CREATE POLICY "Allow all authenticated update cfg_materials_types"
    ON public.cfg_materials_types
    FOR UPDATE
    TO authenticated
    USING (true);

CREATE POLICY "Allow all authenticated delete cfg_materials_types"
    ON public.cfg_materials_types
    FOR DELETE
    TO authenticated
    USING (true);

-- 4. Add type_id column to materials table
ALTER TABLE public.materials
ADD COLUMN IF NOT EXISTS type_id bigint NULL;

-- 5. Add foreign key constraint (optional - uncomment if you want referential integrity)
-- ALTER TABLE public.materials
-- ADD CONSTRAINT fk_materials_type_id
-- FOREIGN KEY (type_id) REFERENCES public.cfg_materials_types(id);
