-- ============================================================
-- Migration: Rateio de Aluguel Veicular — Fase 2
-- Date: 2026-10-09
-- Description:
--   1) Despesas variáveis mensais REAIS (combustível, pedágio,
--      manutenção, seguro/IPVA, outros — tabela cfg_vehicles_costs_types
--      criada na Fase 1) passam a compor a apuração junto com o
--      aluguel do contrato.
--   2) Componente R$/km: a linha de odômetro (km × vehicles.value_unit)
--      da visita passa a ser CONVERTIDA na linha 'rate' do rateio
--      quando a competência é alocada — mesmo id, mesmo value_total,
--      logo o total cobrado na visita NÃO muda (só a origem/rótulo).
--
--   Base da Fase 2:
--     total          = aluguel do contrato + despesas do mês
--                      (+ R$/km op. × total_km, componente proporcional)
--     custo/km       = (aluguel + despesas) ÷ total_km  (total_km = 0 => NULL)
--     custo total/km = custo/km + R$/km op.
--     rateio/visita  = até 2 linhas: cost_component 'RENTAL' e
--                      'VARIABLE' (a 2ª só quando despesas > 0)
--                      + conversão da linha de Km em cost_type 'rate'
--     ociosidade     = (aluguel + despesas) − Σ rateios
--                      (o R$/km op. NÃO gera ociosidade: é 100% proporcional)
--     utilização     = apropriado ÷ (aluguel + despesas)
--
--   Conteúdo:
--     1. vehicle_monthly_expenses        (despesas do mês por veículo)
--     2. Trigger de guarda: despesas bloqueadas quando a competência
--        está ALLOCATED/CLOSED
--     3. Guard de linhas: cost_type 'variable' e 'rate' imutáveis
--        junto com 'rental' (CREATE OR REPLACE, mesma assinatura)
--     4. orders_visits_vehicles.cost_type ganha o valor 'rate'
--        (DROP CONSTRAINT + ADD CONSTRAINT, sem CASCADE) e
--        fc_orders_visits_vehicles_before_save deixa a troca de
--        origem 'odometer' <-> 'rate' passar sem recalcular valores
--     5. fc_vehicle_rental_summary  (+ variable_value, variable_per_km,
--        operational_value, operational_per_km)
--     6. fc_vehicle_rental_detail   (+ rental_value, variable_value,
--        variable_ovv_id, operational_value) — DROP + CREATE
--        (mudança de return type)
--     7. fc_vehicle_rental_calculate (soma despesas; conta Km de
--        linhas 'odometer' E 'rate')
--     8. fc_vehicle_rental_allocate  (2 componentes por visita +
--        converte a linha de Km em 'rate')
--     9. fc_vehicle_rental_revert    (recalcula com despesas vigentes
--        e devolve as linhas 'rate' para 'odometer')
--
--   Sem mudança em: fc_vehicle_rental_contract/_close/_reopen,
--   fc_financial_orders_visits_vehicles_sum (já agrupa por cost_type),
--   v_orders_visits_vehicles, before_save (já trata 'variable').
--
--   Aplicação MANUAL no SQL Editor do Supabase (regra do AGENTS.md),
--   DEPOIS de 20261008_create_vehicle_rental_rateio.sql.
--   Idempotente: pode ser re-executada com segurança.
--   Nenhum DROP ... CASCADE nesta migration (regra do AGENTS.md).
--
--   ⚠ NÃO re-executar 20261008_create_vehicle_rental_rateio.sql DEPOIS
--     desta migration: o CREATE OR REPLACE de summary/detail da Fase 1
--     usaria return type mais estreito e falharia (falha ruidosa de
--     propósito — evita reverter em silêncio os guards das seções 3 e 4).
-- ============================================================

-- ------------------------------------------------------------
-- 1. Despesas variáveis mensais por veículo
--    Uma linha por lançamento (ex.: abastecimento, pedágio).
--    A soma do mês alimenta vehicle_rental_periods.variable_value
--    no cálculo da competência.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.vehicle_monthly_expenses (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    vehicle_id bigint NOT NULL,
    reference_month date NOT NULL,
    cost_type_id bigint NOT NULL,
    value numeric(14,2) NOT NULL,
    description text,
    created_user_id bigint,
    created_at timestamp without time zone DEFAULT now(),
    updated_user_id bigint,
    updated_at timestamp without time zone,
    CONSTRAINT vehicle_monthly_expenses_pkey PRIMARY KEY (id),
    CONSTRAINT vehicle_monthly_expenses_month_ck
        CHECK (reference_month = date_trunc('month', reference_month)::date),
    CONSTRAINT vehicle_monthly_expenses_value_ck CHECK (value > 0),
    CONSTRAINT vehicle_monthly_expenses_vehicle_fk
        FOREIGN KEY (vehicle_id) REFERENCES public.vehicles (id) ON DELETE CASCADE,
    CONSTRAINT vehicle_monthly_expenses_type_fk
        FOREIGN KEY (cost_type_id) REFERENCES public.cfg_vehicles_costs_types (id)
);

COMMENT ON TABLE public.vehicle_monthly_expenses IS
    'Despesas variáveis reais do veículo em uma competência (combustível, pedágio, ...). Somadas na apuração junto com o aluguel do contrato; bloqueadas quando a competência está ALLOCATED/CLOSED.';

CREATE INDEX IF NOT EXISTS idx_vehicle_monthly_expenses_lookup
    ON public.vehicle_monthly_expenses (vehicle_id, reference_month);

ALTER TABLE public.vehicle_monthly_expenses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Universal Access" ON public.vehicle_monthly_expenses;
CREATE POLICY "Universal Access" ON public.vehicle_monthly_expenses
    USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public.vehicle_monthly_expenses TO authenticated, service_role;
REVOKE ALL ON TABLE public.vehicle_monthly_expenses FROM anon;
GRANT USAGE ON SEQUENCE public.vehicle_monthly_expenses_id_seq TO authenticated, service_role;

-- ------------------------------------------------------------
-- 2. Guarda de imutabilidade das despesas
--    Após apropriação (ALLOCATED) ou fechamento (CLOSED) da
--    competência, nenhuma despesa pode entrar, sair ou mudar —
--    faça o estorno/reabra a competência antes de alterar.
--    (As RPCs nunca escrevem nesta tabela, então não há flag.)
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fc_vehicle_monthly_expenses_guard() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_status character varying;
BEGIN
    IF TG_OP <> 'DELETE' THEN
        SELECT p.status INTO v_status
        FROM public.vehicle_rental_periods p
        WHERE p.vehicle_id = NEW.vehicle_id
          AND p.reference_month = NEW.reference_month;

        IF v_status IN ('ALLOCATED', 'CLOSED') THEN
            RAISE EXCEPTION 'Despesas da competência % (veículo %) estão bloqueadas: período % — faça o estorno (fc_vehicle_rental_revert) ou reabra antes de alterar.',
                NEW.reference_month, NEW.vehicle_id, v_status;
        END IF;
    END IF;

    IF TG_OP <> 'INSERT' THEN
        SELECT p.status INTO v_status
        FROM public.vehicle_rental_periods p
        WHERE p.vehicle_id = OLD.vehicle_id
          AND p.reference_month = OLD.reference_month;

        IF v_status IN ('ALLOCATED', 'CLOSED') THEN
            RAISE EXCEPTION 'Despesas da competência % (veículo %) estão bloqueadas: período % — faça o estorno (fc_vehicle_rental_revert) ou reabra antes de alterar.',
                OLD.reference_month, OLD.vehicle_id, v_status;
        END IF;
    END IF;

    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

DROP TRIGGER IF EXISTS trg_vehicle_monthly_expenses_guard ON public.vehicle_monthly_expenses;
CREATE TRIGGER trg_vehicle_monthly_expenses_guard
    BEFORE INSERT OR UPDATE OR DELETE ON public.vehicle_monthly_expenses
    FOR EACH ROW EXECUTE FUNCTION public.fc_vehicle_monthly_expenses_guard();

-- ------------------------------------------------------------
-- 3. Guard de linhas rateadas: 'rental', 'variable' E 'rate'
--    imutáveis fora das RPCs
--    (CREATE OR REPLACE com a MESMA assinatura — o trigger já
--     existente continua apontando para a função. Sem DROP.)
--    'rate' = linha de Km (odômetro) CONVERTIDA pela apuração:
--    mesmo id/value_total da linha original, congelada enquanto a
--    competência estiver alocada/fechada; o estorno a devolve a
--    'odometer' e a destrava.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fc_orders_visits_vehicles_rateio_guard() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_flag boolean := coalesce(current_setting('app.vehicle_rental_write', true), '') = '1';
    v_status character varying;
    v_period_id bigint;
BEGIN
    IF TG_OP = 'INSERT' THEN
        -- Linhas de rateio/despesa/R$/km só nascem na apuração (RPC)
        IF v_flag THEN
            RETURN NEW;
        END IF;
        IF NEW.cost_type <> 'odometer' THEN
            RAISE EXCEPTION 'Linha de rateio (aluguel/despesa/R$/km) só pode ser criada pela apuração mensal (fc_vehicle_rental_*).';
        END IF;
        RETURN NEW;
    END IF;

    IF TG_OP = 'UPDATE' THEN
        -- Atualizações que não tocam em Km/valores são sempre permitidas
        -- (ex.: fc_sync_ov_costs_status espelha ov_costs_status da visita
        -- em todas as linhas filhas — incluindo linhas rateadas)
        IF NEW.ov_id IS NOT DISTINCT FROM OLD.ov_id
           AND NEW.vehicle_id IS NOT DISTINCT FROM OLD.vehicle_id
           AND NEW.recorder_start IS NOT DISTINCT FROM OLD.recorder_start
           AND NEW.recorder_end IS NOT DISTINCT FROM OLD.recorder_end
           AND NEW.amount IS NOT DISTINCT FROM OLD.amount
           AND NEW.discount IS NOT DISTINCT FROM OLD.discount
           AND NEW.cost_type IS NOT DISTINCT FROM OLD.cost_type
           AND NEW.is_deleted IS NOT DISTINCT FROM OLD.is_deleted THEN
            RETURN NEW;
        END IF;

        -- Linha de rateio (aluguel, despesa ou R$/km convertido):
        -- nunca editável fora da RPC
        IF NEW.cost_type IN ('rental', 'variable', 'rate') THEN
            IF v_flag THEN
                RETURN NEW;
            END IF;
            RAISE EXCEPTION 'Linha de rateio (aluguel/despesa/R$/km) é gerada pela apuração mensal e não pode ser editada.';
        END IF;

        -- Linha de odômetro já rateada: congelada até o estorno
        SELECT p.status, p.id INTO v_status, v_period_id
        FROM public.vehicles_rentals_allocations a
        JOIN public.vehicle_rental_periods p ON p.id = a.period_id
        WHERE a.ovv_id = NEW.id
        LIMIT 1;

        IF v_status IS NOT NULL AND NOT v_flag THEN
            RAISE EXCEPTION 'Km já rateado na competência % — faça o estorno (fc_vehicle_rental_revert) antes de alterar a leitura do odômetro.',
                v_period_id;
        END IF;

        RETURN NEW;
    END IF;

    -- DELETE ------------------------------------------------------------------
    IF OLD.cost_type IN ('rental', 'variable') THEN
        IF v_flag THEN
            RETURN OLD;
        END IF;

        SELECT p.status INTO v_status
        FROM public.vehicles_rentals_allocations a
        JOIN public.vehicle_rental_periods p ON p.id = a.period_id
        WHERE a.rental_ovv_id = OLD.id
        LIMIT 1;

        IF v_status = 'CLOSED' THEN
            RAISE EXCEPTION 'Competência fechada: o rateio (aluguel/despesa) é imutável (reabra a competência para alterar).';
        END IF;

        RETURN OLD;
    END IF;

    -- Linha de Km já rateada (ainda 'odometer' ou já convertida para
    -- 'rate'): bloqueia exclusão fora da RPC enquanto houver allocation
    SELECT p.status INTO v_status
    FROM public.vehicles_rentals_allocations a
    JOIN public.vehicle_rental_periods p ON p.id = a.period_id
    WHERE a.ovv_id = OLD.id
    LIMIT 1;

    IF v_status IS NOT NULL AND NOT v_flag THEN
        RAISE EXCEPTION 'Km já rateado — faça o estorno (fc_vehicle_rental_revert) antes de remover a linha do veículo.';
    END IF;

    RETURN OLD;
END;
$$;

-- ------------------------------------------------------------
-- 4. cost_type passa a aceitar 'rate'
--    'rate' = a MESMA linha de odômetro da visita depois de rateada
--    (mesmo id, amount, value_unit e value_total — a apuração apenas
--     troca a origem; o rollup soma todas as linhas, então ov_vehicles_value
--     não muda). DROP CONSTRAINT + ADD CONSTRAINT sem CASCADE: nenhum
--    objeto depende de uma CHECK constraint.
-- ------------------------------------------------------------
ALTER TABLE public.orders_visits_vehicles
    DROP CONSTRAINT IF EXISTS orders_visits_vehicles_cost_type_ck;

ALTER TABLE public.orders_visits_vehicles
    ADD CONSTRAINT orders_visits_vehicles_cost_type_ck
    CHECK (cost_type IN ('odometer', 'rental', 'variable', 'rate'));

-- ------------------------------------------------------------
-- 4.1 before_save: a conversão de origem não reprocessa a linha
--     O before_save da Fase 1 recalcula value_unit (de vehicles),
--     amount (odômetro) e value_total para tudo que não for
--     'rental'/'variable'. Se ele processasse a troca
--     'odometer' <-> 'rate', reescreveria o valor da linha (o total
--     cobrado deixaria de ser o de antes da alocação) e apagaria
--     as leituras do odômetro no estorno.
--     CREATE OR REPLACE com a MESMA assinatura (trigger aponta
--     para a função, não para o corpo).
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fc_orders_visits_vehicles_before_save() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'public'
    AS $$
DECLARE
    v_price numeric;
BEGIN

    -- Conversão de origem feita pela apuração (odometer <-> rate):
    -- só cost_type muda; amount/value_unit/value_total/recorder e
    -- desconto ficam intactos (o rollup recalcula o mesmo total).
    IF TG_OP = 'UPDATE'
       AND NEW.cost_type IS DISTINCT FROM OLD.cost_type
       AND NEW.ov_id IS NOT DISTINCT FROM OLD.ov_id
       AND NEW.vehicle_id IS NOT DISTINCT FROM OLD.vehicle_id
       AND NEW.recorder_start IS NOT DISTINCT FROM OLD.recorder_start
       AND NEW.recorder_end IS NOT DISTINCT FROM OLD.recorder_end
       AND NEW.amount IS NOT DISTINCT FROM OLD.amount
       AND NEW.discount IS NOT DISTINCT FROM OLD.discount
       AND NEW.is_deleted IS NOT DISTINCT FROM OLD.is_deleted THEN
        RETURN NEW;
    END IF;

    -- Linhas de rateio/despesa não têm odômetro: preserva amount/value_unit
    -- informados e recalcula apenas value_total.
    IF NEW.cost_type IN ('rental', 'variable') THEN
        NEW.recorder_start := NULL;
        NEW.recorder_end   := NULL;
        NEW.value_unit     := COALESCE(NEW.value_unit, 0);
        NEW.amount         := COALESCE(NEW.amount, 0);
        NEW.value_total    := ROUND(
            NEW.amount * NEW.value_unit * COALESCE(NEW.discount, 1), 2
        );
        RETURN NEW;
    END IF;

    -- Linha já convertida para 'rate': jamais recalcula (só a RPC de
    -- estorno devolve a 'odometer'; fora da flag o guard bloqueia)
    IF NEW.cost_type = 'rate' THEN
        RETURN NEW;
    END IF;

    SELECT value_unit
    INTO v_price
    FROM public.vehicles
    WHERE id = NEW.vehicle_id;

    NEW.value_unit := COALESCE(v_price,0);

    NEW.amount :=
        GREATEST(
            COALESCE(NEW.recorder_end,0)
            - COALESCE(NEW.recorder_start,0),
            0
        );

    NEW.value_total :=
        NEW.amount
        * NEW.value_unit
        * COALESCE(NEW.discount,1);

    RETURN NEW;

END;
$$;

-- ------------------------------------------------------------
-- 8.2 Resumo da competência (tabela da tela de Apuração)
--     + variable_value / variable_per_km
--     + operational_value / operational_per_km (componente R$/km:
--       soma das linhas de Km, sejam 'odometer' ou já convertidas
--       para 'rate' pelo allocate)
--     Gravado só em ALLOCATED/CLOSED (guard congela despesas/Km);
--     em OPEN e CALCULATED tudo é calculado ao vivo — depois de um
--     estorno o card senão mostraria as despesas de quando o cálculo
--     foi gravado.
--     DROP sem CASCADE (mudança de return type exige DROP; nenhum
--     caller no front-end nem no banco depende das colunas antigas).
-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS public.fc_vehicle_rental_summary(date);

CREATE FUNCTION public.fc_vehicle_rental_summary(p_reference_month date)
RETURNS TABLE (
    period_id bigint,
    period_status character varying,
    vehicle_id bigint,
    vehicle_description text,
    vehicle_plates text,
    contract_id bigint,
    contract_value numeric,
    has_conflict boolean,
    total_km bigint,
    cost_per_km numeric,
    allocated_value numeric,
    idle_value numeric,
    utilization numeric,
    variable_value numeric,
    variable_per_km numeric,
    operational_value numeric,
    operational_per_km numeric
)
    LANGUAGE plpgsql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_month date := (date_trunc('month', p_reference_month::timestamp))::date;
    v_month_end date := (date_trunc('month', p_reference_month::timestamp) + interval '1 month - 1 day')::date;
    v_row record;
    v_period public.vehicle_rental_periods%ROWTYPE;
    v_km bigint;
    v_rate numeric;
    v_rental_rate numeric;
    v_var_rate numeric;
    v_alloc numeric;
    v_alloc_rental numeric;
    v_alloc_variable numeric;
    v_value numeric;
    v_variable numeric;
    v_op numeric;
BEGIN
    FOR v_row IN
        WITH contract_info AS (
            SELECT c.vehicle_id,
                   count(*) AS n_contracts,
                   (array_agg(c.id ORDER BY c.start_date DESC, c.id DESC))[1] AS best_id,
                   (array_agg(c.monthly_value ORDER BY c.start_date DESC, c.id DESC))[1] AS best_value
            FROM public.cfg_vehicles_rentals_contracts c
            WHERE c.active AND NOT c.is_deleted
              AND c.start_date <= v_month_end
              AND (c.end_date IS NULL OR c.end_date >= v_month)
            GROUP BY c.vehicle_id
        ),
        base AS (
            SELECT u.vvehicle, u.vcid, u.vvalue, u.prio
            FROM (
                SELECT p.vehicle_id AS vvehicle, p.contract_id AS vcid,
                       p.contract_value AS vvalue, 0 AS prio
                FROM public.vehicle_rental_periods p
                WHERE p.reference_month = v_month
                UNION ALL
                SELECT ci.vehicle_id, ci.best_id, ci.best_value, 1
                FROM contract_info ci
            ) u
        )
        SELECT DISTINCT ON (b.vvehicle)
               b.vvehicle, b.vcid, b.vvalue,
               COALESCE(ci.n_contracts, 0) > 1 AS vconflict,
               ve.description AS vd, ve.plates AS vp
        FROM base b
        LEFT JOIN contract_info ci ON ci.vehicle_id = b.vvehicle
        JOIN public.vehicles ve ON ve.id = b.vvehicle AND NOT ve.is_deleted
        ORDER BY b.vvehicle, b.prio, ve.description
    LOOP
        SELECT p.* INTO v_period
        FROM public.vehicle_rental_periods p
        WHERE p.vehicle_id = v_row.vvehicle
          AND p.reference_month = v_month;

        -- Km total do mês (âncora: created_at da linha, fallback da visita).
        -- Conta linhas 'odometer' E 'rate' (a mesma linha depois de rateada).
        SELECT COALESCE(sum(ovv.amount), 0)::bigint,
               COALESCE(sum(ovv.value_total), 0)
        INTO v_km, v_op
        FROM public.orders_visits_vehicles ovv
        JOIN public.orders_visits ovs ON ovs.id = ovv.ov_id
        WHERE ovv.vehicle_id = v_row.vvehicle
          AND NOT ovv.is_deleted
          AND ovv.cost_type IN ('odometer', 'rate')
          AND ovv.amount > 0
          AND COALESCE(ovv.created_at, ovs.ov_created_at) >= v_month
          AND COALESCE(ovv.created_at, ovs.ov_created_at) < v_month + interval '1 month';

        v_value := COALESCE(v_period.contract_value, v_row.vvalue, 0);

        -- Despesas variáveis do mês (ao vivo; se o período já existe,
        -- o valor gravado no cálculo prevalece — ver IF abaixo)
        SELECT COALESCE(sum(e.value), 0)
        INTO v_variable
        FROM public.vehicle_monthly_expenses e
        WHERE e.vehicle_id = v_row.vvehicle
          AND e.reference_month = v_month;

        IF v_period.id IS NOT NULL THEN
            period_id := v_period.id;
            period_status := v_period.status;
        ELSE
            period_id := NULL;
            period_status := 'OPEN';
        END IF;

        IF v_period.id IS NOT NULL AND v_period.status IN ('ALLOCATED', 'CLOSED') THEN
            -- Competência confirmada/fechada: valores gravados são a
            -- fonte do rateio (o guard trava despesas e Km => gravado
            -- é idêntico ao ao vivo).
            total_km := v_period.total_km;
            v_rate := v_period.cost_per_km;
            v_alloc := v_period.allocated_value;
            v_variable := COALESCE(v_period.variable_value, 0);
        ELSE
            -- Prévia ao vivo: sem período, ou status CALCULATED (após
            -- estorno ou alocação interrompida). Nesse estado despesas
            -- e Km continuam editáveis, então usar o valor gravado no
            -- cálculo mostraria despesas desatualizadas no card.
            total_km := v_km;
            v_rate := CASE WHEN v_km > 0 THEN (v_value + v_variable) / v_km::numeric ELSE NULL END;
            v_rental_rate := CASE WHEN v_km > 0 THEN v_value / v_km::numeric ELSE NULL END;
            v_var_rate := CASE WHEN v_km > 0 AND v_variable > 0 THEN v_variable / v_km::numeric ELSE NULL END;

            -- Prévia: soma dos valores já arredondados por visita e por
            -- componente (mesma fórmula do fc_vehicle_rental_allocate)
            SELECT COALESCE(sum(round(ovv.amount * v_rental_rate, 2)), 0),
                   COALESCE(sum(round(ovv.amount * v_var_rate, 2)), 0)
            INTO v_alloc_rental, v_alloc_variable
            FROM public.orders_visits_vehicles ovv
            JOIN public.orders_visits ovs ON ovs.id = ovv.ov_id
            WHERE ovv.vehicle_id = v_row.vvehicle
              AND NOT ovv.is_deleted
              AND ovv.cost_type IN ('odometer', 'rate')
              AND ovv.amount > 0
              AND COALESCE(ovv.created_at, ovs.ov_created_at) >= v_month
              AND COALESCE(ovv.created_at, ovs.ov_created_at) < v_month + interval '1 month';

            v_alloc := v_alloc_rental + v_alloc_variable;
        END IF;

        vehicle_id := v_row.vvehicle;
        vehicle_description := v_row.vd;
        vehicle_plates := v_row.vp;
        contract_id := v_row.vcid;
        contract_value := v_value;
        has_conflict := v_row.vconflict;
        cost_per_km := v_rate;
        allocated_value := v_alloc;
        idle_value := (v_value + v_variable) - v_alloc;
        utilization := CASE
            WHEN (v_value + v_variable) > 0 THEN round(v_alloc / (v_value + v_variable), 4)
            ELSE NULL
        END;
        variable_value := v_variable;
        variable_per_km := CASE
            WHEN total_km > 0 AND v_variable > 0 THEN round(v_variable / total_km::numeric, 6)
            ELSE NULL
        END;
        operational_value := v_op;
        operational_per_km := CASE
            WHEN total_km > 0 THEN round(v_op / total_km::numeric, 6)
            ELSE NULL
        END;

        RETURN NEXT;
    END LOOP;
END;
$$;

REVOKE ALL ON FUNCTION public.fc_vehicle_rental_summary(date) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.fc_vehicle_rental_summary(date) TO authenticated, service_role;

-- ------------------------------------------------------------
-- 8.3 Detalhe visita a visita (tabela da SIMULAR)
--     + rental_value / variable_value / variable_ovv_id
--     + operational_value (valor da linha de Km da visita — o
--       componente R$/km que a apuração exibe; seja a linha ainda
--       'odometer' ou já convertida para 'rate')
--     DROP sem CASCADE (mudança de return type).
-- ------------------------------------------------------------
DROP FUNCTION IF EXISTS public.fc_vehicle_rental_detail(bigint, date);

CREATE FUNCTION public.fc_vehicle_rental_detail(
    p_vehicle_id bigint,
    p_reference_month date
) RETURNS TABLE (
    period_id bigint,
    period_status character varying,
    ov_id bigint,
    ovv_id bigint,
    visit_mask character varying,
    km bigint,
    rate numeric,
    value numeric,
    rental_value numeric,
    variable_value numeric,
    rental_ovv_id bigint,
    variable_ovv_id bigint,
    operational_value numeric
)
    LANGUAGE plpgsql STABLE SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_month date := (date_trunc('month', p_reference_month::timestamp))::date;
    v_period public.vehicle_rental_periods%ROWTYPE;
    v_contract numeric;
    v_variable numeric;
    v_rate numeric;
    v_rental_rate numeric;
    v_var_rate numeric;
    v_rate_km bigint;
    v_total bigint;
BEGIN
    SELECT p.* INTO v_period
    FROM public.vehicle_rental_periods p
    WHERE p.vehicle_id = p_vehicle_id
      AND p.reference_month = v_month;

    -- Km total do mês (âncora: created_at da linha, fallback da visita)
    SELECT COALESCE(sum(ovv.amount), 0)::bigint
    INTO v_total
    FROM public.orders_visits_vehicles ovv
    JOIN public.orders_visits ovs ON ovs.id = ovv.ov_id
    WHERE ovv.vehicle_id = p_vehicle_id
      AND NOT ovv.is_deleted
      AND ovv.cost_type IN ('odometer', 'rate')
      AND ovv.amount > 0
      AND COALESCE(ovv.created_at, ovs.ov_created_at) >= v_month
      AND COALESCE(ovv.created_at, ovs.ov_created_at) < v_month + interval '1 month';

    IF v_period.id IS NOT NULL AND v_period.status IN ('ALLOCATED', 'CLOSED') THEN
        -- Competência confirmada/fechada: rates gravados (fonte do
        -- allocate; guard trava despesas e Km => gravado = ao vivo)
        v_contract := COALESCE(v_period.contract_value, 0);
        v_variable := COALESCE(v_period.variable_value, 0);
        v_rate_km := v_period.total_km;
        v_rate := v_period.cost_per_km;
    ELSE
        -- Prévia ao vivo: contrato vigente + despesas do mês. Vale
        -- sem período (OPEN) e também em CALCULATED, onde despesas e
        -- Km ainda podem mudar depois do cálculo.
        SELECT c.monthly_value INTO v_contract
        FROM public.fc_vehicle_rental_contract(p_vehicle_id, v_month) c;

        SELECT COALESCE(sum(e.value), 0) INTO v_variable
        FROM public.vehicle_monthly_expenses e
        WHERE e.vehicle_id = p_vehicle_id
          AND e.reference_month = v_month;

        v_rate_km := v_total;
        v_rate := CASE
            WHEN v_total > 0 THEN (v_contract + v_variable) / v_total::numeric
            ELSE NULL
        END;
    END IF;

    -- Rates por componente: idênticos aos usados no allocate
    v_rental_rate := CASE
        WHEN v_rate_km > 0 THEN round(v_contract / v_rate_km::numeric, 6)
        ELSE NULL
    END;
    v_var_rate := CASE
        WHEN v_rate_km > 0 AND v_variable > 0 THEN round(v_variable / v_rate_km::numeric, 6)
        ELSE NULL
    END;

    RETURN QUERY
    SELECT
        v_period.id,
        COALESCE(v_period.status, 'OPEN')::character varying,
        ovv.ov_id,
        ovv.id,
        ovs.ov_mask,
        ovv.amount,
        v_rate,
        COALESCE(round(ovv.amount * v_rental_rate, 2), 0)
            + COALESCE(round(ovv.amount * v_var_rate, 2), 0),
        round(ovv.amount * v_rental_rate, 2),
        round(ovv.amount * v_var_rate, 2),
        a_rental.rental_ovv_id,
        a_var.rental_ovv_id,
        ovv.value_total
    FROM public.orders_visits_vehicles ovv
    JOIN public.orders_visits ovs ON ovs.id = ovv.ov_id
    LEFT JOIN public.vehicles_rentals_allocations a_rental
           ON a_rental.ovv_id = ovv.id
          AND a_rental.period_id IS NOT DISTINCT FROM v_period.id
          AND a_rental.cost_component = 'RENTAL'
    LEFT JOIN public.vehicles_rentals_allocations a_var
           ON a_var.ovv_id = ovv.id
          AND a_var.period_id IS NOT DISTINCT FROM v_period.id
          AND a_var.cost_component = 'VARIABLE'
    WHERE ovv.vehicle_id = p_vehicle_id
      AND NOT ovv.is_deleted
      AND ovv.cost_type IN ('odometer', 'rate')
      AND ovv.amount > 0
      AND COALESCE(ovv.created_at, ovs.ov_created_at) >= v_month
      AND COALESCE(ovv.created_at, ovs.ov_created_at) < v_month + interval '1 month'
    ORDER BY COALESCE(ovv.created_at, ovs.ov_created_at), ovv.id;
END;
$$;

REVOKE ALL ON FUNCTION public.fc_vehicle_rental_detail(bigint, date) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.fc_vehicle_rental_detail(bigint, date) TO authenticated, service_role;

-- ------------------------------------------------------------
-- 8.4 Calcula a competência: contrato vigente + despesas do mês
--     + Km do mês + custo/km total
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fc_vehicle_rental_calculate(
    p_vehicle_id bigint,
    p_reference_month date,
    p_user_id bigint DEFAULT NULL
) RETURNS SETOF public.vehicle_rental_periods
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_month date := (date_trunc('month', p_reference_month::timestamp))::date;
    v_period public.vehicle_rental_periods%ROWTYPE;
    v_contract_id bigint;
    v_contract_value numeric;
    v_has_conflict boolean;
    v_total_km bigint;
    v_expenses numeric;
    v_rate numeric;
    v_rental_rate numeric;
    v_var_rate numeric;
    v_alloc numeric;
    v_alloc_rental numeric;
    v_alloc_variable numeric;
BEGIN
    PERFORM set_config('app.vehicle_rental_write', '1', true);

    SELECT p.* INTO v_period
    FROM public.vehicle_rental_periods p
    WHERE p.vehicle_id = p_vehicle_id
      AND p.reference_month = v_month
    FOR UPDATE;

    IF v_period.id IS NOT NULL AND v_period.status IN ('ALLOCATED', 'CLOSED') THEN
        RAISE EXCEPTION 'Competência % do veículo % já alocada/fechada: faça o estorno antes de recalcular.',
            v_month, p_vehicle_id;
    END IF;

    SELECT c.contract_id, c.monthly_value, c.has_conflict
    INTO v_contract_id, v_contract_value, v_has_conflict
    FROM public.fc_vehicle_rental_contract(p_vehicle_id, v_month) c;

    IF v_contract_id IS NULL THEN
        RAISE EXCEPTION 'Nenhum contrato de aluguel ativo para o veículo % na competência %.',
            p_vehicle_id, v_month;
    END IF;

    -- Despesas variáveis lançadas no mês
    SELECT COALESCE(sum(e.value), 0)
    INTO v_expenses
    FROM public.vehicle_monthly_expenses e
    WHERE e.vehicle_id = p_vehicle_id
      AND e.reference_month = v_month;

    -- Km total do mês (âncora: created_at da linha, fallback da visita).
    -- Inclui linhas 'rate' para que re-calcular uma competência já
    -- alocada não zere o Km (a linha foi CONVERTIDA, não removida).
    SELECT COALESCE(sum(ovv.amount), 0)::bigint
    INTO v_total_km
    FROM public.orders_visits_vehicles ovv
    JOIN public.orders_visits ovs ON ovs.id = ovv.ov_id
    WHERE ovv.vehicle_id = p_vehicle_id
      AND NOT ovv.is_deleted
      AND ovv.cost_type IN ('odometer', 'rate')
      AND ovv.amount > 0
      AND COALESCE(ovv.created_at, ovs.ov_created_at) >= v_month
      AND COALESCE(ovv.created_at, ovs.ov_created_at) < v_month + interval '1 month';

    -- custo/km = (aluguel + despesas) / total_km
    -- (total_km = 0 => NULL, tudo vira ociosidade)
    v_rate := CASE
        WHEN v_total_km > 0 THEN round((v_contract_value + v_expenses) / v_total_km::numeric, 6)
        ELSE NULL
    END;
    v_rental_rate := CASE
        WHEN v_total_km > 0 THEN round(v_contract_value / v_total_km::numeric, 6)
        ELSE NULL
    END;
    v_var_rate := CASE
        WHEN v_total_km > 0 AND v_expenses > 0 THEN round(v_expenses / v_total_km::numeric, 6)
        ELSE NULL
    END;

    -- Prévia do apropriado: soma dos valores já arredondados por visita
    -- e por componente (idêntica ao fc_vehicle_rental_allocate)
    SELECT COALESCE(sum(round(ovv.amount * v_rental_rate, 2)), 0),
           COALESCE(sum(round(ovv.amount * v_var_rate, 2)), 0)
    INTO v_alloc_rental, v_alloc_variable
    FROM public.orders_visits_vehicles ovv
    JOIN public.orders_visits ovs ON ovs.id = ovv.ov_id
    WHERE ovv.vehicle_id = p_vehicle_id
      AND NOT ovv.is_deleted
      AND ovv.cost_type IN ('odometer', 'rate')
      AND ovv.amount > 0
      AND COALESCE(ovv.created_at, ovs.ov_created_at) >= v_month
      AND COALESCE(ovv.created_at, ovs.ov_created_at) < v_month + interval '1 month';

    v_alloc := v_alloc_rental + v_alloc_variable;

    INSERT INTO public.vehicle_rental_periods (
        vehicle_id, reference_month, contract_id, contract_value, total_km,
        cost_per_km, variable_value, variable_per_km, allocated_value,
        idle_value, has_conflict, status,
        created_user_id, created_at, updated_user_id, updated_at
    ) VALUES (
        p_vehicle_id, v_month, v_contract_id, v_contract_value, v_total_km,
        v_rate, v_expenses, v_var_rate, v_alloc,
        (v_contract_value + v_expenses) - v_alloc, v_has_conflict, 'CALCULATED',
        p_user_id, now(), p_user_id, now()
    )
    ON CONFLICT (vehicle_id, reference_month) DO UPDATE SET
        contract_id = EXCLUDED.contract_id,
        contract_value = EXCLUDED.contract_value,
        total_km = EXCLUDED.total_km,
        cost_per_km = EXCLUDED.cost_per_km,
        variable_value = EXCLUDED.variable_value,
        variable_per_km = EXCLUDED.variable_per_km,
        allocated_value = EXCLUDED.allocated_value,
        idle_value = EXCLUDED.idle_value,
        has_conflict = EXCLUDED.has_conflict,
        status = 'CALCULATED',
        updated_user_id = EXCLUDED.updated_user_id,
        updated_at = now();

    RETURN QUERY
    SELECT p.* FROM public.vehicle_rental_periods p
    WHERE p.vehicle_id = p_vehicle_id
      AND p.reference_month = v_month;
END;
$$;

-- ------------------------------------------------------------
-- 8.5 Aloca o rateio: para cada linha de Km do mês cria até
--     DUAS linhas de visita — 'rental' (aluguel) e, quando há
--     despesas no mês, 'variable' — apontadas por allocations com
--     cost_component 'RENTAL'/'VARIABLE' — e CONVERTE a própria
--     linha de Km de 'odometer' para 'rate' (mesmo id, mesmo
--     value_total: o total cobrado na visita não muda; muda só a
--     origem, permitindo congelar/estornar e somar o R$/km op.
--     no custo/km da apuração).
--     Não altera ov_costs_status da visita (aprovadas mantêm status).
--     Idempotente: re-executar não duplica (unique index) nem
--     re-converte (UPDATE com condição cost_type = 'odometer').
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fc_vehicle_rental_allocate(
    p_vehicle_id bigint,
    p_reference_month date,
    p_user_id bigint DEFAULT NULL
) RETURNS SETOF public.vehicle_rental_periods
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_month date := (date_trunc('month', p_reference_month::timestamp))::date;
    v_period public.vehicle_rental_periods%ROWTYPE;
    v_line record;
    v_rental_id bigint;
    v_var_id bigint;
    v_rental_rate numeric;
    v_var_rate numeric;
    v_value numeric;
    v_alloc_total numeric;
BEGIN
    PERFORM set_config('app.vehicle_rental_write', '1', true);

    SELECT p.* INTO v_period
    FROM public.vehicle_rental_periods p
    WHERE p.vehicle_id = p_vehicle_id
      AND p.reference_month = v_month
    FOR UPDATE;

    IF v_period.id IS NULL THEN
        RAISE EXCEPTION 'Competência % do veículo % não foi calculada: execute o cálculo antes da alocação.',
            v_month, p_vehicle_id;
    END IF;

    IF v_period.status NOT IN ('CALCULATED', 'ALLOCATED') THEN
        RAISE EXCEPTION 'Competência % está %: reabra antes de alocar.',
            v_month, v_period.status;
    END IF;

    IF v_period.cost_per_km IS NULL THEN
        RAISE EXCEPTION 'Competência % sem Km rodado: nada a alocar (aluguel e despesas ficam integralmente em ociosidade).',
            v_month;
    END IF;

    -- Rates por componente (memósmos do cálculo): aluguel e despesas
    -- entram em linhas separadas da mesma visita.
    v_rental_rate := round(v_period.contract_value / v_period.total_km::numeric, 6);
    v_var_rate := CASE
        WHEN COALESCE(v_period.variable_value, 0) > 0
            THEN round(v_period.variable_value / v_period.total_km::numeric, 6)
        ELSE NULL
    END;

    FOR v_line IN
        SELECT ovv.id AS ovv_id,
               ovv.ov_id,
               ovv.amount AS km,
               ovs.ov_costs_status AS visit_status
        FROM public.orders_visits_vehicles ovv
        JOIN public.orders_visits ovs ON ovs.id = ovv.ov_id
        WHERE ovv.vehicle_id = p_vehicle_id
          AND NOT ovv.is_deleted
          AND ovv.cost_type IN ('odometer', 'rate')
          AND ovv.amount > 0
          AND COALESCE(ovv.created_at, ovs.ov_created_at) >= v_month
          AND COALESCE(ovv.created_at, ovs.ov_created_at) < v_month + interval '1 month'
        ORDER BY ovv.id
    LOOP
        -- Componente RENTAL (aluguel) ------------------------------------
        IF NOT EXISTS (
            SELECT 1
            FROM public.vehicles_rentals_allocations a
            WHERE a.period_id = v_period.id
              AND a.ovv_id = v_line.ovv_id
              AND a.cost_component = 'RENTAL'
        ) THEN
            v_value := round(v_line.km * v_rental_rate, 2);

            -- Linha de rateio: amount = km, value_unit = custo/km aluguel.
            -- ov_costs_status copiado da visita => status aprovado preservado.
            INSERT INTO public.orders_visits_vehicles (
                ov_id, vehicle_id, amount, value_unit, discount, cost_type,
                ov_costs_status, created_user_id, created_at, is_deleted
            ) VALUES (
                v_line.ov_id, p_vehicle_id, v_line.km, v_rental_rate, 1,
                'rental', COALESCE(v_line.visit_status, 'pending'), p_user_id, now(), false
            )
            RETURNING id INTO v_rental_id;

            INSERT INTO public.vehicles_rentals_allocations (
                period_id, ov_id, ovv_id, rental_ovv_id, km, rate, value,
                cost_component, created_at
            ) VALUES (
                v_period.id, v_line.ov_id, v_line.ovv_id, v_rental_id,
                v_line.km, v_rental_rate, v_value, 'RENTAL', now()
            )
            ON CONFLICT (period_id, ovv_id, cost_component) DO NOTHING;
        END IF;

        -- Componente VARIABLE (despesas do mês) --------------------------
        IF v_var_rate IS NOT NULL AND NOT EXISTS (
            SELECT 1
            FROM public.vehicles_rentals_allocations a
            WHERE a.period_id = v_period.id
              AND a.ovv_id = v_line.ovv_id
              AND a.cost_component = 'VARIABLE'
        ) THEN
            v_value := round(v_line.km * v_var_rate, 2);

            INSERT INTO public.orders_visits_vehicles (
                ov_id, vehicle_id, amount, value_unit, discount, cost_type,
                ov_costs_status, created_user_id, created_at, is_deleted
            ) VALUES (
                v_line.ov_id, p_vehicle_id, v_line.km, v_var_rate, 1,
                'variable', COALESCE(v_line.visit_status, 'pending'), p_user_id, now(), false
            )
            RETURNING id INTO v_var_id;

            INSERT INTO public.vehicles_rentals_allocations (
                period_id, ov_id, ovv_id, rental_ovv_id, km, rate, value,
                cost_component, created_at
            ) VALUES (
                v_period.id, v_line.ov_id, v_line.ovv_id, v_var_id,
                v_line.km, v_var_rate, v_value, 'VARIABLE', now()
            )
            ON CONFLICT (period_id, ovv_id, cost_component) DO NOTHING;
        END IF;

        -- Componente R$/km: converte a linha de Km em 'rate' --------
        -- Depois de criadas as allocations (o guard passa a enxergar a
        -- linha via a.ovv_id) e sem tocar em amount/value_unit/value_total,
        -- logo ov_vehicles_value (rollup que soma TODAS as linhas) fica
        -- exatamente igual ao de antes da alocação.
        UPDATE public.orders_visits_vehicles ovv
        SET cost_type = 'rate'
        WHERE ovv.id = v_line.ovv_id
          AND ovv.cost_type = 'odometer';
    END LOOP;

    SELECT COALESCE(sum(a.value), 0)
    INTO v_alloc_total
    FROM public.vehicles_rentals_allocations a
    WHERE a.period_id = v_period.id;

    UPDATE public.vehicle_rental_periods p
    SET allocated_value = v_alloc_total,
        idle_value = (p.contract_value + COALESCE(p.variable_value, 0)) - v_alloc_total,
        status = 'ALLOCATED',
        updated_user_id = p_user_id,
        updated_at = now()
    WHERE p.id = v_period.id;

    RETURN QUERY
    SELECT p.* FROM public.vehicle_rental_periods p
    WHERE p.id = v_period.id;
END;
$$;

-- ------------------------------------------------------------
-- 8.7 Estorna o rateio: apaga linhas rental E variable geradas
--     (cada allocation aponta a própria linha em rental_ovv_id),
--     DEVOLVE as linhas de Km convertidas de 'rate' para
--     'odometer' (editáveis de novo) e recalcula com Km e DESPESAS
--     vigentes (status CALCULATED).
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fc_vehicle_rental_revert(
    p_vehicle_id bigint,
    p_reference_month date,
    p_user_id bigint DEFAULT NULL
) RETURNS SETOF public.vehicle_rental_periods
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
    v_month date := (date_trunc('month', p_reference_month::timestamp))::date;
    v_period public.vehicle_rental_periods%ROWTYPE;
    v_total_km bigint;
    v_expenses numeric;
    v_rate numeric;
    v_rental_rate numeric;
    v_var_rate numeric;
    v_alloc numeric;
    v_alloc_rental numeric;
    v_alloc_variable numeric;
BEGIN
    PERFORM set_config('app.vehicle_rental_write', '1', true);

    SELECT p.* INTO v_period
    FROM public.vehicle_rental_periods p
    WHERE p.vehicle_id = p_vehicle_id
      AND p.reference_month = v_month
    FOR UPDATE;

    IF v_period.id IS NULL THEN
        RAISE EXCEPTION 'Competência % do veículo % não existe.', v_month, p_vehicle_id;
    END IF;

    IF v_period.status = 'CLOSED' THEN
        RAISE EXCEPTION 'Competência % está fechada: reabra antes de estornar.', v_month;
    END IF;

    IF v_period.status <> 'ALLOCATED' THEN
        RAISE EXCEPTION 'Competência % não tem rateio alocado (status: %).', v_month, v_period.status;
    END IF;

    -- Devolve as linhas de Km convertidas para 'rate' ao odômetro
    -- (ids vêm das allocations — captura ANTES de apagá-las; a troca
    --  de cost_type não muda value_total, então o rollup recalcula o
    --  mesmo ov_vehicles_value e a linha volta a ser editável)
    UPDATE public.orders_visits_vehicles ovv
    SET cost_type = 'odometer'
    WHERE ovv.cost_type = 'rate'
      AND ovv.id IN (
          SELECT a.ovv_id
          FROM public.vehicles_rentals_allocations a
          WHERE a.period_id = v_period.id
      );

    -- Remove as linhas de rateio (o rollup recalcula ov_vehicles_value)
    DELETE FROM public.orders_visits_vehicles ovv
    WHERE ovv.id IN (
        SELECT a.rental_ovv_id
        FROM public.vehicles_rentals_allocations a
        WHERE a.period_id = v_period.id
          AND a.rental_ovv_id IS NOT NULL
    );

    DELETE FROM public.vehicles_rentals_allocations a
    WHERE a.period_id = v_period.id;

    -- Recalcula com o Km e as despesas vigentes
    -- ('odometer' e 'rate' — defensivo: uma linha que por algum motivo
    --  não tenha sido devolvida acima ainda é Km real do mês)
    SELECT COALESCE(sum(ovv.amount), 0)::bigint
    INTO v_total_km
    FROM public.orders_visits_vehicles ovv
    JOIN public.orders_visits ovs ON ovs.id = ovv.ov_id
    WHERE ovv.vehicle_id = p_vehicle_id
      AND NOT ovv.is_deleted
      AND ovv.cost_type IN ('odometer', 'rate')
      AND ovv.amount > 0
      AND COALESCE(ovv.created_at, ovs.ov_created_at) >= v_month
      AND COALESCE(ovv.created_at, ovs.ov_created_at) < v_month + interval '1 month';

    SELECT COALESCE(sum(e.value), 0)
    INTO v_expenses
    FROM public.vehicle_monthly_expenses e
    WHERE e.vehicle_id = p_vehicle_id
      AND e.reference_month = v_month;

    v_rate := CASE
        WHEN v_total_km > 0 THEN round((v_period.contract_value + v_expenses) / v_total_km::numeric, 6)
        ELSE NULL
    END;
    v_rental_rate := CASE
        WHEN v_total_km > 0 THEN round(v_period.contract_value / v_total_km::numeric, 6)
        ELSE NULL
    END;
    v_var_rate := CASE
        WHEN v_total_km > 0 AND v_expenses > 0 THEN round(v_expenses / v_total_km::numeric, 6)
        ELSE NULL
    END;

    -- Prévia do apropriado (mesma fórmula componente a componente do
    -- fc_vehicle_rental_calculate/allocate)
    SELECT COALESCE(sum(round(ovv.amount * v_rental_rate, 2)), 0),
           COALESCE(sum(round(ovv.amount * v_var_rate, 2)), 0)
    INTO v_alloc_rental, v_alloc_variable
    FROM public.orders_visits_vehicles ovv
    JOIN public.orders_visits ovs ON ovs.id = ovv.ov_id
    WHERE ovv.vehicle_id = p_vehicle_id
      AND NOT ovv.is_deleted
      AND ovv.cost_type IN ('odometer', 'rate')
      AND ovv.amount > 0
      AND COALESCE(ovv.created_at, ovs.ov_created_at) >= v_month
      AND COALESCE(ovv.created_at, ovs.ov_created_at) < v_month + interval '1 month';

    v_alloc := v_alloc_rental + v_alloc_variable;

    UPDATE public.vehicle_rental_periods p
    SET total_km = v_total_km,
        cost_per_km = v_rate,
        variable_value = v_expenses,
        variable_per_km = v_var_rate,
        allocated_value = v_alloc,
        idle_value = (p.contract_value + v_expenses) - v_alloc,
        status = 'CALCULATED',
        updated_user_id = p_user_id,
        updated_at = now()
    WHERE p.id = v_period.id;

    RETURN QUERY
    SELECT p.* FROM public.vehicle_rental_periods p
    WHERE p.id = v_period.id;
END;
$$;

-- ------------------------------------------------------------
-- 9. Permissões das RPCs alteradas (DROP + CREATE recria o objeto;
--    as demais RPCs e a flag de sessão não mudaram)
-- ------------------------------------------------------------
REVOKE ALL ON FUNCTION public.fc_vehicle_rental_summary(date) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.fc_vehicle_rental_detail(bigint, date) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.fc_vehicle_rental_calculate(bigint, date, bigint) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.fc_vehicle_rental_allocate(bigint, date, bigint) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.fc_vehicle_rental_revert(bigint, date, bigint) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.fc_vehicle_rental_summary(date) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.fc_vehicle_rental_detail(bigint, date) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.fc_vehicle_rental_calculate(bigint, date, bigint) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.fc_vehicle_rental_allocate(bigint, date, bigint) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.fc_vehicle_rental_revert(bigint, date, bigint) TO authenticated, service_role;
