ALTER TABLE public.cfg_activities OWNER TO supabase_admin;

ALTER TABLE public.assets OWNER TO supabase_admin;

ALTER TABLE public.cfg_assets_couplings_models OWNER TO supabase_admin;

ALTER TABLE public.cfg_assets_priorities OWNER TO supabase_admin;

ALTER TABLE public.cfg_assets_statuses OWNER TO supabase_admin;

ALTER TABLE public.cfg_assets_tags OWNER TO supabase_admin;

ALTER TABLE public.cfg_assets_tags_subs OWNER TO supabase_admin;

ALTER TABLE public.cfg_assets_types OWNER TO supabase_admin;

ALTER TABLE public.cfg_companies OWNER TO supabase_admin;

ALTER TABLE public.clients OWNER TO supabase_admin;

ALTER TABLE public.materials OWNER TO supabase_admin;

ALTER TABLE public.units OWNER TO supabase_admin;

ALTER TABLE public.cfg_services OWNER TO supabase_admin;

ALTER TABLE public.contracts_services OWNER TO supabase_admin;

ALTER TABLE public.cfg_orders_causes_reasons OWNER TO supabase_admin;

ALTER TABLE public.cfg_orders_priorities OWNER TO supabase_admin;

ALTER TABLE public.cfg_orders_types OWNER TO supabase_admin;

ALTER TABLE public.cfg_orders_types_subs OWNER TO supabase_admin;

ALTER TABLE public.cfg_orders_visits_extras_processing OWNER TO supabase_admin;

ALTER TABLE public.cfg_systems OWNER TO supabase_admin;

ALTER TABLE public.cfg_teams OWNER TO supabase_admin;

ALTER TABLE public.cfg_units_types OWNER TO supabase_admin;

ALTER TABLE public.orders_visits_extras OWNER TO supabase_admin;

ALTER TABLE public.users OWNER TO supabase_admin;

ALTER TABLE public.cfg_orders_cancel_reasons OWNER TO supabase_admin;

ALTER TABLE public.cfg_orders_objects OWNER TO supabase_admin;

ALTER TABLE public.cfg_orders_plans OWNER TO supabase_admin;

ALTER TABLE public.cfg_orders_statuses OWNER TO supabase_admin;

ALTER TABLE public.cfg_orders_suspended_reasons OWNER TO supabase_admin;

ALTER TABLE public.contracts OWNER TO supabase_admin;

ALTER TABLE public.orders OWNER TO supabase_admin;

ALTER TABLE public.cfg_orders_types_activities OWNER TO supabase_admin;

ALTER TABLE public.technicals_manuals OWNER TO supabase_admin;

ALTER TABLE public.cfg_units_assets_tags OWNER TO supabase_admin;

ALTER TABLE public.cfg_assets_available_processing OWNER TO supabase_admin;

ALTER TABLE public.cfg_assets_unavailable_reasons OWNER TO supabase_admin;

ALTER TABLE public.cfg_units_statuses OWNER TO supabase_admin;

ALTER TABLE auth.audit_log_entries OWNER TO supabase_auth_admin;

ALTER TABLE auth.flow_state OWNER TO supabase_auth_admin;

ALTER TABLE auth.identities OWNER TO supabase_auth_admin;

ALTER TABLE auth.instances OWNER TO supabase_auth_admin;

ALTER TABLE auth.mfa_amr_claims OWNER TO supabase_auth_admin;

ALTER TABLE auth.mfa_challenges OWNER TO supabase_auth_admin;

ALTER TABLE auth.mfa_factors OWNER TO supabase_auth_admin;

ALTER TABLE auth.oauth_authorizations OWNER TO supabase_auth_admin;

ALTER TABLE auth.oauth_clients OWNER TO supabase_auth_admin;

ALTER TABLE auth.oauth_consents OWNER TO supabase_auth_admin;

ALTER TABLE auth.one_time_tokens OWNER TO supabase_auth_admin;

ALTER TABLE auth.refresh_tokens OWNER TO supabase_auth_admin;

ALTER TABLE auth.saml_providers OWNER TO supabase_auth_admin;

ALTER TABLE auth.saml_relay_states OWNER TO supabase_auth_admin;

ALTER TABLE auth.schema_migrations OWNER TO supabase_auth_admin;

ALTER TABLE auth.sessions OWNER TO supabase_auth_admin;

ALTER TABLE auth.sso_domains OWNER TO supabase_auth_admin;

ALTER TABLE auth.sso_providers OWNER TO supabase_auth_admin;

ALTER TABLE auth.users OWNER TO supabase_auth_admin;

ALTER TABLE public.ai_chat_histories OWNER TO supabase_admin;

ALTER TABLE public.ai_chat_sessions OWNER TO supabase_admin;

ALTER TABLE public.ai_knowledge OWNER TO supabase_admin;

ALTER TABLE public.ai_messages OWNER TO supabase_admin;

ALTER TABLE public.api_keys OWNER TO supabase_admin;

ALTER TABLE public.api_keys ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.api_keys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.assets_alerts OWNER TO supabase_admin;

ALTER TABLE public.assets_alerts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_alerts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.assets_attributes_values OWNER TO supabase_admin;

ALTER TABLE public.assets_available OWNER TO supabase_admin;

ALTER TABLE public.assets_available ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_available_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.assets_followers OWNER TO supabase_admin;

ALTER TABLE public.assets_followers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_followers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.assets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.assets_loans OWNER TO supabase_admin;

ALTER TABLE public.assets_loans_checklists OWNER TO supabase_admin;

ALTER TABLE public.assets_loans_checklists_images OWNER TO supabase_admin;

ALTER TABLE public.assets_materials OWNER TO supabase_admin;

ALTER TABLE public.assets_materials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_materials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.audits_logs OWNER TO supabase_admin;

ALTER TABLE public.carts_materials OWNER TO supabase_admin;

ALTER TABLE public.carts_materials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_materials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_activities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_activities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_app OWNER TO supabase_admin;

ALTER TABLE public.cfg_app ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_app_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_app_notices OWNER TO supabase_admin;

ALTER TABLE public.cfg_app_notices_categories OWNER TO supabase_admin;

ALTER TABLE public.cfg_app_notices_severities OWNER TO supabase_admin;

ALTER TABLE public.cfg_app_offline_updates OWNER TO supabase_admin;

ALTER TABLE public.cfg_app_offline_updates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_app_offline_updates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_app_pages OWNER TO supabase_admin;

ALTER TABLE public.cfg_app_pages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_app_pages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_app_tips OWNER TO supabase_admin;

ALTER TABLE public.cfg_app_tips_companies OWNER TO supabase_admin;

ALTER TABLE public.cfg_app_tips_departments OWNER TO supabase_admin;

ALTER TABLE public.cfg_app_tips_dismissals OWNER TO supabase_admin;

ALTER TABLE public.cfg_app_tips_profiles OWNER TO supabase_admin;

ALTER TABLE public.cfg_app_versions_update OWNER TO supabase_admin;

ALTER TABLE public.cfg_app_versions_update ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_app_versions_update_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_assets_attributes OWNER TO supabase_admin;

ALTER TABLE public.cfg_assets_attributes_groups OWNER TO supabase_admin;

ALTER TABLE public.cfg_assets_attributes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_assets_attributes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_assets_available_processing ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_assets_available_processing_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_assets_couplings_models ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_assets_couplings_models_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_assets_priorities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_assets_priorities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_assets_statuses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_assets_statuses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_assets_types_attributes OWNER TO supabase_admin;

ALTER TABLE public.cfg_assets_types_attributes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_assets_types_attributes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_assets_types_loans_checklists OWNER TO supabase_admin;

ALTER TABLE public.cfg_assets_unavailable_reasons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_assets_unavailable_reasons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_companies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_companies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_contracts_statuses OWNER TO supabase_admin;

ALTER TABLE public.cfg_contracts_statuses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_contracts_statuses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_departments OWNER TO supabase_admin;

ALTER TABLE public.cfg_departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_evaluation_requirements OWNER TO supabase_admin;

ALTER TABLE public.cfg_evaluation_requirements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_evaluation_requirements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_loans_checklists OWNER TO supabase_admin;

ALTER TABLE public.cfg_materials_purchases_statuses OWNER TO supabase_admin;

ALTER TABLE public.cfg_materials_purchases_cancel_reasons OWNER TO supabase_admin;

ALTER TABLE public.cfg_materials_purchases_types OWNER TO supabase_admin;

ALTER TABLE public.cfg_materials_statuses OWNER TO supabase_admin;

ALTER TABLE public.cfg_materials_statuses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_materials_statuses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_materials_types OWNER TO supabase_admin;

ALTER TABLE public.cfg_materials_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_materials_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_orders_cancel_reasons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_orders_cancel_reasons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_orders_causes_reasons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_orders_causes_reasons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_orders_counter OWNER TO supabase_admin;

ALTER TABLE public.cfg_orders_counter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_orders_counter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_orders_objects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_orders_objects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_orders_plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_orders_plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_orders_priorities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_orders_priorities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_orders_statuses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_orders_statuses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_orders_suspended_reasons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_orders_suspended_reasons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_orders_types_activities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_orders_types_activities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_orders_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_orders_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_orders_types_subs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_orders_types_subs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_orders_visits_extras_processing ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_orders_visits_extras_processing_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_orders_visits_processing OWNER TO supabase_admin;

ALTER TABLE public.cfg_orders_visits_processing ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_orders_visits_processing_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_orders_visits_statuses OWNER TO supabase_admin;

ALTER TABLE public.cfg_orders_visits_statuses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_orders_visits_statuses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_profiles OWNER TO supabase_admin;

ALTER TABLE public.cfg_profiles_access OWNER TO supabase_admin;

ALTER TABLE public.cfg_profiles_access ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_profiles_access_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_profiles_permissions OWNER TO supabase_admin;

ALTER TABLE public.cfg_profiles_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_profiles_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_routes OWNER TO supabase_admin;

ALTER TABLE public.cfg_routes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_routes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_systems ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_systems_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_technicals_manuals_categories OWNER TO supabase_admin;

ALTER TABLE public.cfg_technicals_manuals_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_technicals_manuals_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_units_assets_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_units_assets_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_units_statuses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_units_statuses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_units_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_units_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.cfg_users_statuses OWNER TO supabase_admin;

ALTER TABLE public.cfg_users_statuses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cfg_users_statuses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.chat_agent_ai OWNER TO supabase_admin;

ALTER TABLE public.chat_agent_ai ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.contracts_evaluation_requirements OWNER TO supabase_admin;

ALTER TABLE public.contracts_evaluation_requirements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_evaluation_requirements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.contracts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.contracts_managers OWNER TO supabase_admin;

ALTER TABLE public.contracts_managers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_managers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.contracts_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contracts_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.documents OWNER TO supabase_admin;

ALTER TABLE public.extensions OWNER TO supabase_admin;

ALTER TABLE public.goose_db_version OWNER TO postgres;

ALTER TABLE public.goose_db_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.impersonation_password_backup OWNER TO supabase_admin;

ALTER TABLE public.import_orders_visits_contracts OWNER TO supabase_admin;

ALTER TABLE public.leader_monthly_scores OWNER TO supabase_admin;

ALTER TABLE public.leader_monthly_scores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leader_monthly_scores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.leader_score_badges OWNER TO supabase_admin;

ALTER TABLE public.leader_score_badges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leader_score_badges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.leader_scores_history OWNER TO supabase_admin;

ALTER TABLE public.leader_scores_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leader_scores_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.logs_api OWNER TO supabase_admin;

ALTER TABLE public.logs_api ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.logs_api_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.audits_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.maintenances_plans OWNER TO supabase_admin;

ALTER TABLE public.maintenances_plans_sections OWNER TO supabase_admin;

ALTER TABLE public.maintenances_plans_sections_activities OWNER TO supabase_admin;

ALTER TABLE public.materials_purchases OWNER TO supabase_admin;

ALTER TABLE public.materials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.materials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.materials_purchases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.materials_purchases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.n8n_chat_histories OWNER TO supabase_admin;

ALTER TABLE public.orders_followers OWNER TO supabase_admin;

ALTER TABLE public.orders_followers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_followers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.orders_statuses_logs OWNER TO supabase_admin;

ALTER TABLE public.orders_statuses_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_statuses_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.orders_visits OWNER TO supabase_admin;

ALTER TABLE public.orders_visits_assets OWNER TO supabase_admin;

ALTER TABLE public.orders_visits_assets_activities OWNER TO supabase_admin;

ALTER TABLE public.orders_visits_assets_activities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_visits_assets_activities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.orders_visits_assets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_visits_assets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.orders_visits_assets_materials OWNER TO supabase_admin;

ALTER TABLE public.orders_visits_assets_materials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_visits_assets_materials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.orders_visits_chat OWNER TO supabase_admin;

ALTER TABLE public.orders_visits_chat_participants OWNER TO supabase_admin;

ALTER TABLE public.orders_visits_chat_reads OWNER TO supabase_admin;

ALTER TABLE public.orders_visits_evaluations OWNER TO supabase_admin;

ALTER TABLE public.orders_visits_evaluations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_visits_evaluations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.orders_visits_extras_followers OWNER TO supabase_admin;

ALTER TABLE public.orders_visits_extras_followers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_visits_extras_followers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.orders_visits_extras ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_visits_extras_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.orders_visits_extras_teams OWNER TO supabase_admin;

ALTER TABLE public.orders_visits_extras_teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_visits_extras_teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.orders_visits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_visits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.orders_visits_services OWNER TO supabase_admin;

ALTER TABLE public.orders_visits_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_visits_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.orders_visits_teams OWNER TO supabase_admin;

ALTER TABLE public.orders_visits_teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_visits_teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.orders_visits_vehicles OWNER TO supabase_admin;

ALTER TABLE public.orders_visits_vehicles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_visits_vehicles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.schema_migrations OWNER TO supabase_admin;

ALTER TABLE public.technicals_manuals_assets OWNER TO supabase_admin;

ALTER TABLE public.technicals_manuals_assets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.technicals_manuals_assets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.technicals_manuals_files OWNER TO supabase_admin;

ALTER TABLE public.technicals_manuals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.technicals_manuals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.tenants OWNER TO supabase_admin;

ALTER TABLE public.import_orders_visits_contracts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tmp_contracts_import_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.tools OWNER TO supabase_admin;

ALTER TABLE public.units ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.units_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.users_notifications OWNER TO supabase_admin;

ALTER TABLE public.users_notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.users_tools OWNER TO supabase_admin;

ALTER TABLE public.users_tools_movements OWNER TO supabase_admin;

ALTER TABLE public.users_tracker OWNER TO supabase_admin;

ALTER TABLE public.users_tracker ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_tracker_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.warehouses OWNER TO supabase_admin;

ALTER TABLE public.warehouses_materials OWNER TO supabase_admin;

ALTER TABLE public.vehicles OWNER TO supabase_admin;

ALTER TABLE public.vehicles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.warehouses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE storage.buckets OWNER TO supabase_storage_admin;

ALTER TABLE storage.buckets_analytics OWNER TO supabase_storage_admin;

ALTER TABLE storage.buckets_vectors OWNER TO supabase_storage_admin;

ALTER TABLE storage.iceberg_namespaces OWNER TO supabase_storage_admin;

ALTER TABLE storage.iceberg_tables OWNER TO supabase_storage_admin;

ALTER TABLE storage.migrations OWNER TO supabase_storage_admin;

ALTER TABLE storage.objects OWNER TO supabase_storage_admin;

ALTER TABLE storage.prefixes OWNER TO supabase_storage_admin;

ALTER TABLE storage.s3_multipart_uploads OWNER TO supabase_storage_admin;

ALTER TABLE storage.s3_multipart_uploads_parts OWNER TO supabase_storage_admin;

ALTER TABLE storage.vector_indexes OWNER TO supabase_storage_admin;

ALTER TABLE ONLY auth.refresh_tokens ALTER COLUMN id SET DEFAULT nextval('auth.refresh_tokens_id_seq'::regclass);

ALTER TABLE ONLY public.ai_chat_histories ALTER COLUMN id SET DEFAULT nextval('public.ai_chat_histories_id_seq'::regclass);

ALTER TABLE ONLY public.assets_loans ALTER COLUMN id SET DEFAULT nextval('public.assets_loans_id_seq'::regclass);

ALTER TABLE ONLY public.assets_loans_checklists ALTER COLUMN id SET DEFAULT nextval('public.assets_loans_checklists_id_seq'::regclass);

ALTER TABLE ONLY public.assets_loans_checklists_images ALTER COLUMN id SET DEFAULT nextval('public.assets_loans_checklists_images_id_seq'::regclass);

ALTER TABLE ONLY public.cfg_app_notices ALTER COLUMN id SET DEFAULT nextval('public.system_notices_id_seq'::regclass);

ALTER TABLE ONLY public.cfg_app_notices_categories ALTER COLUMN id SET DEFAULT nextval('public.system_notice_categories_id_seq'::regclass);

ALTER TABLE ONLY public.cfg_app_notices_severities ALTER COLUMN id SET DEFAULT nextval('public.system_notice_severities_id_seq'::regclass);

ALTER TABLE ONLY public.cfg_app_tips ALTER COLUMN id SET DEFAULT nextval('public.cfg_app_tips_new_id_seq'::regclass);

ALTER TABLE ONLY public.cfg_app_tips_companies ALTER COLUMN id SET DEFAULT nextval('public.cfg_app_tips_companies_id_seq'::regclass);

ALTER TABLE ONLY public.cfg_app_tips_departments ALTER COLUMN id SET DEFAULT nextval('public.cfg_app_tips_departments_id_seq'::regclass);

ALTER TABLE ONLY public.cfg_app_tips_dismissals ALTER COLUMN id SET DEFAULT nextval('public.cfg_app_tips_dismissals_id_seq'::regclass);

ALTER TABLE ONLY public.cfg_app_tips_profiles ALTER COLUMN id SET DEFAULT nextval('public.cfg_app_tips_profiles_id_seq'::regclass);

ALTER TABLE ONLY public.cfg_assets_attributes_groups ALTER COLUMN id SET DEFAULT nextval('public.cfg_assets_attributes_groups_id_seq'::regclass);

ALTER TABLE ONLY public.cfg_assets_types_loans_checklists ALTER COLUMN id SET DEFAULT nextval('public.cfg_assets_types_loans_checklists_id_seq'::regclass);

ALTER TABLE ONLY public.cfg_loans_checklists ALTER COLUMN id SET DEFAULT nextval('public.cfg_loans_checklists_id_seq'::regclass);

ALTER TABLE ONLY public.documents ALTER COLUMN id SET DEFAULT nextval('public.documents_id_seq'::regclass);

ALTER TABLE ONLY public.impersonation_password_backup ALTER COLUMN id SET DEFAULT nextval('public.impersonation_password_backup_id_seq'::regclass);

ALTER TABLE ONLY public.maintenances_plans ALTER COLUMN id SET DEFAULT nextval('public.maintenances_plans_id_seq'::regclass);

ALTER TABLE ONLY public.maintenances_plans_sections ALTER COLUMN id SET DEFAULT nextval('public.maintenances_plans_sections_id_seq'::regclass);

ALTER TABLE ONLY public.maintenances_plans_sections_activities ALTER COLUMN id SET DEFAULT nextval('public.maintenances_plans_sections_activities_id_seq'::regclass);

ALTER TABLE ONLY public.n8n_chat_histories ALTER COLUMN id SET DEFAULT nextval('public.n8n_chat_histories_id_seq'::regclass);

ALTER TABLE ONLY public.orders_visits_chat ALTER COLUMN id SET DEFAULT nextval('public.orders_visits_chat_id_seq'::regclass);

ALTER TABLE ONLY public.orders_visits_chat_participants ALTER COLUMN id SET DEFAULT nextval('public.orders_visits_chat_participants_id_seq'::regclass);

ALTER TABLE ONLY public.orders_visits_chat_reads ALTER COLUMN id SET DEFAULT nextval('public.orders_visits_chat_reads_id_seq'::regclass);

ALTER TABLE ONLY public.tools ALTER COLUMN id SET DEFAULT nextval('public.tools_id_seq'::regclass);

ALTER TABLE ONLY public.users_tools ALTER COLUMN id SET DEFAULT nextval('public.users_tools_id_seq'::regclass);

ALTER TABLE ONLY public.users_tools_movements ALTER COLUMN id SET DEFAULT nextval('public.users_tools_movements_id_seq'::regclass);

ALTER TABLE ONLY public.warehouses_materials ALTER COLUMN id SET DEFAULT nextval('public.warehouses_materials_id_seq'::regclass);

ALTER TABLE ONLY auth.mfa_amr_claims
    ADD CONSTRAINT amr_id_pk PRIMARY KEY (id);

ALTER TABLE ONLY auth.audit_log_entries
    ADD CONSTRAINT audit_log_entries_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.flow_state
    ADD CONSTRAINT flow_state_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.identities
    ADD CONSTRAINT identities_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.identities
    ADD CONSTRAINT identities_provider_id_provider_unique UNIQUE (provider_id, provider);

ALTER TABLE ONLY auth.instances
    ADD CONSTRAINT instances_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.mfa_amr_claims
    ADD CONSTRAINT mfa_amr_claims_session_id_authentication_method_pkey UNIQUE (session_id, authentication_method);

ALTER TABLE ONLY auth.mfa_challenges
    ADD CONSTRAINT mfa_challenges_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.mfa_factors
    ADD CONSTRAINT mfa_factors_last_challenged_at_key UNIQUE (last_challenged_at);

ALTER TABLE ONLY auth.mfa_factors
    ADD CONSTRAINT mfa_factors_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.oauth_authorizations
    ADD CONSTRAINT oauth_authorizations_authorization_code_key UNIQUE (authorization_code);

ALTER TABLE ONLY auth.oauth_authorizations
    ADD CONSTRAINT oauth_authorizations_authorization_id_key UNIQUE (authorization_id);

ALTER TABLE ONLY auth.oauth_authorizations
    ADD CONSTRAINT oauth_authorizations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.oauth_clients
    ADD CONSTRAINT oauth_clients_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.oauth_consents
    ADD CONSTRAINT oauth_consents_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.oauth_consents
    ADD CONSTRAINT oauth_consents_user_client_unique UNIQUE (user_id, client_id);

ALTER TABLE ONLY auth.one_time_tokens
    ADD CONSTRAINT one_time_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_unique UNIQUE (token);

ALTER TABLE ONLY auth.saml_providers
    ADD CONSTRAINT saml_providers_entity_id_key UNIQUE (entity_id);

ALTER TABLE ONLY auth.saml_providers
    ADD CONSTRAINT saml_providers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.saml_relay_states
    ADD CONSTRAINT saml_relay_states_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);

ALTER TABLE ONLY auth.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.sso_domains
    ADD CONSTRAINT sso_domains_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.sso_providers
    ADD CONSTRAINT sso_providers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.users
    ADD CONSTRAINT users_phone_key UNIQUE (phone);

ALTER TABLE ONLY auth.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_chat_histories
    ADD CONSTRAINT ai_chat_histories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_chat_sessions
    ADD CONSTRAINT ai_chat_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_knowledge
    ADD CONSTRAINT ai_knowledge_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_messages
    ADD CONSTRAINT ai_messages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_api_key_key UNIQUE (api_key);

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_app
    ADD CONSTRAINT app_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_app_pages
    ADD CONSTRAINT apppages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_app_versions_update
    ADD CONSTRAINT appversionsupdate_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.assets_alerts
    ADD CONSTRAINT assets_alerts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_assets_attributes
    ADD CONSTRAINT assets_attributes_field_key_unique UNIQUE (field_key);

ALTER TABLE ONLY public.cfg_assets_attributes
    ADD CONSTRAINT assets_attributes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.assets_attributes_values
    ADD CONSTRAINT assets_attributes_values_pkey PRIMARY KEY (asset_id, field_key);

ALTER TABLE ONLY public.assets_loans_checklists_images
    ADD CONSTRAINT assets_loans_checklists_images_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.assets_loans_checklists
    ADD CONSTRAINT assets_loans_checklists_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.assets_loans
    ADD CONSTRAINT assets_loans_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_assets_tags
    ADD CONSTRAINT assets_tags_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_assets_types_attributes
    ADD CONSTRAINT assets_types_attributes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_assets_types_attributes
    ADD CONSTRAINT assets_types_attributes_unique UNIQUE (asset_type_id, attribute_id);

ALTER TABLE ONLY public.cfg_assets_types
    ADD CONSTRAINT assets_types_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_assets_couplings_models
    ADD CONSTRAINT assetscouplingsmodels_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.assets_followers
    ADD CONSTRAINT assetsfollowers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.assets_materials
    ADD CONSTRAINT assetsmaterials_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_assets_priorities
    ADD CONSTRAINT assetspriorities_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_assets_statuses
    ADD CONSTRAINT assetsstatuses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_assets_tags_subs
    ADD CONSTRAINT assetstagssubs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.carts_materials
    ADD CONSTRAINT cart_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_activities
    ADD CONSTRAINT cfg_activities_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_app_notices
    ADD CONSTRAINT cfg_app_notices_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_app_offline_updates
    ADD CONSTRAINT cfg_app_offline_tables_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_app_tips_companies
    ADD CONSTRAINT cfg_app_tips_companies_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_app_tips_companies
    ADD CONSTRAINT cfg_app_tips_companies_tip_id_company_id_key UNIQUE (tip_id, company_id);

ALTER TABLE ONLY public.cfg_app_tips_departments
    ADD CONSTRAINT cfg_app_tips_departments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_app_tips_departments
    ADD CONSTRAINT cfg_app_tips_departments_tip_id_department_id_key UNIQUE (tip_id, department_id);

ALTER TABLE ONLY public.cfg_app_tips_dismissals
    ADD CONSTRAINT cfg_app_tips_dismissals_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_app_tips_dismissals
    ADD CONSTRAINT cfg_app_tips_dismissals_tip_id_user_id_key UNIQUE (tip_id, user_id);

ALTER TABLE ONLY public.cfg_app_tips
    ADD CONSTRAINT cfg_app_tips_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_app_tips_profiles
    ADD CONSTRAINT cfg_app_tips_profiles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_app_tips_profiles
    ADD CONSTRAINT cfg_app_tips_profiles_tip_id_profile_id_key UNIQUE (tip_id, profile_id);

ALTER TABLE ONLY public.cfg_assets_attributes_groups
    ADD CONSTRAINT cfg_assets_attributes_groups_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_assets_available_processing
    ADD CONSTRAINT cfg_assets_available_processing_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_assets_types_loans_checklists
    ADD CONSTRAINT cfg_assets_types_loans_checklist_checklist_id_asset_type_id_key UNIQUE (checklist_id, asset_type_id);

ALTER TABLE ONLY public.cfg_assets_types_loans_checklists
    ADD CONSTRAINT cfg_assets_types_loans_checklists_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_assets_unavailable_reasons
    ADD CONSTRAINT cfg_assets_unavailable_reasons_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_orders_visits_extras_processing
    ADD CONSTRAINT cfg_eap_processing_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_evaluation_requirements
    ADD CONSTRAINT cfg_evaluation_requirements_code_key UNIQUE (code);

ALTER TABLE ONLY public.cfg_evaluation_requirements
    ADD CONSTRAINT cfg_evaluation_requirements_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_loans_checklists
    ADD CONSTRAINT cfg_loans_checklists_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_materials_purchases_statuses
    ADD CONSTRAINT cfg_material_purchases_statuses_code_key UNIQUE (code);

ALTER TABLE ONLY public.cfg_materials_purchases_statuses
    ADD CONSTRAINT cfg_material_purchases_statuses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_materials_purchases_cancel_reasons
    ADD CONSTRAINT cfg_materials_purchases_cancel_reasons_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_materials_purchases_types
    ADD CONSTRAINT cfg_materials_purchases_types_code_key UNIQUE (code);

ALTER TABLE ONLY public.cfg_materials_purchases_types
    ADD CONSTRAINT cfg_materials_purchases_types_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_materials_statuses
    ADD CONSTRAINT cfg_materials_statuses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_materials_types
    ADD CONSTRAINT cfg_materials_types_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_orders_suspended_reasons
    ADD CONSTRAINT cfg_orders_suspended_reasons_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_profiles_access
    ADD CONSTRAINT cfg_profiles_access_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_routes
    ADD CONSTRAINT cfg_routes_route_key_key UNIQUE (route_key);

ALTER TABLE ONLY public.cfg_services
    ADD CONSTRAINT cfg_services_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_technicals_manuals_categories
    ADD CONSTRAINT cfg_technicals_manuals_categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.chat_agent_ai
    ADD CONSTRAINT chat_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.contracts_evaluation_requirements
    ADD CONSTRAINT contracts_evaluation_requirements_contract_evaluation_unique UNIQUE (contract_id, evaluation_id);

ALTER TABLE ONLY public.contracts_evaluation_requirements
    ADD CONSTRAINT contracts_evaluation_requirements_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.contracts
    ADD CONSTRAINT contracts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.contracts_managers
    ADD CONSTRAINT contractsmanagers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.contracts_services
    ADD CONSTRAINT contractsservices_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_contracts_statuses
    ADD CONSTRAINT contractsstatuses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_departments
    ADD CONSTRAINT department_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.extensions
    ADD CONSTRAINT extensions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.impersonation_password_backup
    ADD CONSTRAINT impersonation_password_backup_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.leader_monthly_scores
    ADD CONSTRAINT leader_monthly_scores_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.leader_monthly_scores
    ADD CONSTRAINT leader_monthly_scores_unique UNIQUE (leader_id, score_year, score_month);

ALTER TABLE ONLY public.leader_score_badges
    ADD CONSTRAINT leader_score_badges_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.leader_scores_history
    ADD CONSTRAINT leader_scores_history_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.leader_scores_history
    ADD CONSTRAINT leader_scores_history_unique UNIQUE (ov_id);

ALTER TABLE ONLY public.logs_api
    ADD CONSTRAINT logs_api_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.audits_logs
    ADD CONSTRAINT logs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.maintenances_plans
    ADD CONSTRAINT maintenances_plans_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.maintenances_plans_sections_activities
    ADD CONSTRAINT maintenances_plans_sections_a_maintenance_plan_section_id_a_key UNIQUE (maintenance_plan_section_id, activity_id);

ALTER TABLE ONLY public.maintenances_plans_sections_activities
    ADD CONSTRAINT maintenances_plans_sections_activities_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.maintenances_plans_sections
    ADD CONSTRAINT maintenances_plans_sections_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.materials_purchases
    ADD CONSTRAINT material_purchases_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.materials
    ADD CONSTRAINT materials_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.n8n_chat_histories
    ADD CONSTRAINT n8n_chat_histories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_orders_counter
    ADD CONSTRAINT orders_counter_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders_followers
    ADD CONSTRAINT orders_followers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_orders_visits_statuses
    ADD CONSTRAINT orders_visitis_statuses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders_visits_assets_activities
    ADD CONSTRAINT orders_visits_assets_activities_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders_visits_assets
    ADD CONSTRAINT orders_visits_assets_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders_visits_chat_participants
    ADD CONSTRAINT orders_visits_chat_participants_ov_id_user_id_key UNIQUE (ov_id, user_id);

ALTER TABLE ONLY public.orders_visits_chat_participants
    ADD CONSTRAINT orders_visits_chat_participants_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders_visits_chat
    ADD CONSTRAINT orders_visits_chat_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders_visits_chat_reads
    ADD CONSTRAINT orders_visits_chat_reads_chat_id_user_id_key UNIQUE (chat_id, user_id);

ALTER TABLE ONLY public.orders_visits_chat_reads
    ADD CONSTRAINT orders_visits_chat_reads_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders_visits_evaluations
    ADD CONSTRAINT orders_visits_evaluations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders_visits_extras
    ADD CONSTRAINT orders_visits_extras_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders_visits_extras_teams
    ADD CONSTRAINT orders_visits_extras_teams_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders_visits
    ADD CONSTRAINT orders_visits_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_orders_visits_processing
    ADD CONSTRAINT orders_visits_processing_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders_visits_teams
    ADD CONSTRAINT orders_visits_teams_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_orders_cancel_reasons
    ADD CONSTRAINT orderscancelreasons_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_orders_causes_reasons
    ADD CONSTRAINT orderscauses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_orders_objects
    ADD CONSTRAINT ordersobjects_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_orders_plans
    ADD CONSTRAINT ordersplans_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_orders_priorities
    ADD CONSTRAINT orderspriorities_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders_statuses_logs
    ADD CONSTRAINT ordersstatuseslogs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_orders_statuses
    ADD CONSTRAINT ordersstatusess_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_orders_types
    ADD CONSTRAINT orderstypes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_orders_types_activities
    ADD CONSTRAINT orderstypesactivities_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_orders_types_subs
    ADD CONSTRAINT orderstypessubs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders_visits_assets_materials
    ADD CONSTRAINT ordersvisitsassetsmaterials_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders_visits_services
    ADD CONSTRAINT ordersvisitsservices_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders_visits_vehicles
    ADD CONSTRAINT ordersvisitsvehicles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_profiles_access
    ADD CONSTRAINT profiles_access_unique UNIQUE (profile_id, route_id);

ALTER TABLE ONLY public.cfg_routes
    ADD CONSTRAINT routes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);

ALTER TABLE ONLY public.cfg_app_notices_categories
    ADD CONSTRAINT system_notice_categories_code_key UNIQUE (code);

ALTER TABLE ONLY public.cfg_app_notices_categories
    ADD CONSTRAINT system_notice_categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_app_notices_severities
    ADD CONSTRAINT system_notice_severities_code_key UNIQUE (code);

ALTER TABLE ONLY public.cfg_app_notices_severities
    ADD CONSTRAINT system_notice_severities_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_systems
    ADD CONSTRAINT systems_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.technicals_manuals_files
    ADD CONSTRAINT technicals_manuals_files_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.technicals_manuals
    ADD CONSTRAINT technicals_manuals_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.import_orders_visits_contracts
    ADD CONSTRAINT tmp_contracts_import_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tools
    ADD CONSTRAINT tools_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders_visits_assets
    ADD CONSTRAINT unique_ov_asset UNIQUE (ov_id, asset_id);

ALTER TABLE ONLY public.assets_available
    ADD CONSTRAINT units_assets_available_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_units_assets_tags
    ADD CONSTRAINT units_assets_tags_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.units
    ADD CONSTRAINT units_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_units_statuses
    ADD CONSTRAINT unitsstatuses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_units_types
    ADD CONSTRAINT unitstypes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users_notifications
    ADD CONSTRAINT users_notifications_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users_tools_movements
    ADD CONSTRAINT users_tools_movements_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users_tools
    ADD CONSTRAINT users_tools_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_profiles
    ADD CONSTRAINT usersprofiles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_profiles_permissions
    ADD CONSTRAINT usersprofilespermissions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.cfg_users_statuses
    ADD CONSTRAINT usersstatuses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users_tracker
    ADD CONSTRAINT userstracks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.vehicles
    ADD CONSTRAINT vehicles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.warehouses_materials
    ADD CONSTRAINT warehouses_materials_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.warehouses_materials
    ADD CONSTRAINT warehouses_materials_warehouse_id_material_id_key UNIQUE (warehouse_id, material_id);

ALTER TABLE ONLY public.warehouses
    ADD CONSTRAINT warehouses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY storage.buckets_analytics
    ADD CONSTRAINT buckets_analytics_pkey PRIMARY KEY (id);

ALTER TABLE ONLY storage.buckets
    ADD CONSTRAINT buckets_pkey PRIMARY KEY (id);

ALTER TABLE ONLY storage.buckets_vectors
    ADD CONSTRAINT buckets_vectors_pkey PRIMARY KEY (id);

ALTER TABLE ONLY storage.iceberg_namespaces
    ADD CONSTRAINT iceberg_namespaces_pkey PRIMARY KEY (id);

ALTER TABLE ONLY storage.iceberg_tables
    ADD CONSTRAINT iceberg_tables_pkey PRIMARY KEY (id);

ALTER TABLE ONLY storage.migrations
    ADD CONSTRAINT migrations_name_key UNIQUE (name);

ALTER TABLE ONLY storage.migrations
    ADD CONSTRAINT migrations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY storage.objects
    ADD CONSTRAINT objects_pkey PRIMARY KEY (id);

ALTER TABLE ONLY storage.prefixes
    ADD CONSTRAINT prefixes_pkey PRIMARY KEY (bucket_id, level, name);

ALTER TABLE ONLY storage.s3_multipart_uploads_parts
    ADD CONSTRAINT s3_multipart_uploads_parts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY storage.s3_multipart_uploads
    ADD CONSTRAINT s3_multipart_uploads_pkey PRIMARY KEY (id);

ALTER TABLE ONLY storage.vector_indexes
    ADD CONSTRAINT vector_indexes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY auth.identities
    ADD CONSTRAINT identities_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth.mfa_amr_claims
    ADD CONSTRAINT mfa_amr_claims_session_id_fkey FOREIGN KEY (session_id) REFERENCES auth.sessions(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth.mfa_challenges
    ADD CONSTRAINT mfa_challenges_auth_factor_id_fkey FOREIGN KEY (factor_id) REFERENCES auth.mfa_factors(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth.mfa_factors
    ADD CONSTRAINT mfa_factors_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth.oauth_authorizations
    ADD CONSTRAINT oauth_authorizations_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.oauth_clients(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth.oauth_authorizations
    ADD CONSTRAINT oauth_authorizations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth.oauth_consents
    ADD CONSTRAINT oauth_consents_client_id_fkey FOREIGN KEY (client_id) REFERENCES auth.oauth_clients(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth.oauth_consents
    ADD CONSTRAINT oauth_consents_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth.one_time_tokens
    ADD CONSTRAINT one_time_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth.refresh_tokens
    ADD CONSTRAINT refresh_tokens_session_id_fkey FOREIGN KEY (session_id) REFERENCES auth.sessions(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth.saml_providers
    ADD CONSTRAINT saml_providers_sso_provider_id_fkey FOREIGN KEY (sso_provider_id) REFERENCES auth.sso_providers(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth.saml_relay_states
    ADD CONSTRAINT saml_relay_states_flow_state_id_fkey FOREIGN KEY (flow_state_id) REFERENCES auth.flow_state(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth.saml_relay_states
    ADD CONSTRAINT saml_relay_states_sso_provider_id_fkey FOREIGN KEY (sso_provider_id) REFERENCES auth.sso_providers(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth.sessions
    ADD CONSTRAINT sessions_oauth_client_id_fkey FOREIGN KEY (oauth_client_id) REFERENCES auth.oauth_clients(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth.sessions
    ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY auth.sso_domains
    ADD CONSTRAINT sso_domains_sso_provider_id_fkey FOREIGN KEY (sso_provider_id) REFERENCES auth.sso_providers(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.ai_chat_sessions
    ADD CONSTRAINT ai_chat_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.ai_messages
    ADD CONSTRAINT ai_messages_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.ai_chat_sessions(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.assets_alerts
    ADD CONSTRAINT assets_alerts_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.assets(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.assets_alerts
    ADD CONSTRAINT assets_alerts_o_type_id_fkey FOREIGN KEY (o_type_id) REFERENCES public.cfg_orders_types(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.assets_alerts
    ADD CONSTRAINT assets_alerts_ova_id_fkey FOREIGN KEY (ova_id) REFERENCES public.orders_visits_assets(id);

ALTER TABLE ONLY public.assets_alerts
    ADD CONSTRAINT assets_alerts_priority_id_fkey FOREIGN KEY (priority_id) REFERENCES public.cfg_orders_priorities(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.assets_available
    ADD CONSTRAINT assets_available_asset_tag_id_fkey FOREIGN KEY (asset_tag_id) REFERENCES public.cfg_assets_tags(id);

ALTER TABLE ONLY public.assets_available
    ADD CONSTRAINT assets_available_asset_tag_sub_id_fkey FOREIGN KEY (asset_tag_sub_id) REFERENCES public.cfg_assets_tags_subs(id);

ALTER TABLE ONLY public.assets_available
    ADD CONSTRAINT assets_available_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.units(id);

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.cfg_companies(id) ON UPDATE CASCADE;

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_company_owner_id_fkey FOREIGN KEY (company_owner_id) REFERENCES public.cfg_companies(id);

ALTER TABLE ONLY public.assets_loans
    ADD CONSTRAINT assets_loans_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.assets(id);

ALTER TABLE ONLY public.assets_loans_checklists
    ADD CONSTRAINT assets_loans_checklists_filled_by_user_id_fkey FOREIGN KEY (filled_by_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.assets_loans_checklists_images
    ADD CONSTRAINT assets_loans_checklists_images_checklist_id_fkey FOREIGN KEY (checklist_id) REFERENCES public.assets_loans_checklists(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.assets_loans_checklists_images
    ADD CONSTRAINT assets_loans_checklists_images_uploaded_by_user_id_fkey FOREIGN KEY (uploaded_by_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.assets_loans_checklists
    ADD CONSTRAINT assets_loans_checklists_loan_checklist_id_fkey FOREIGN KEY (loan_checklist_id) REFERENCES public.cfg_loans_checklists(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.assets_loans_checklists
    ADD CONSTRAINT assets_loans_checklists_loan_id_fkey FOREIGN KEY (loan_id) REFERENCES public.assets_loans(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.assets_loans
    ADD CONSTRAINT assets_loans_created_user_id_fkey FOREIGN KEY (created_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.assets_loans
    ADD CONSTRAINT assets_loans_deleted_user_id_fkey FOREIGN KEY (deleted_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.assets_loans
    ADD CONSTRAINT assets_loans_inspector_delivery_user_id_fkey FOREIGN KEY (inspector_delivery_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.assets_loans
    ADD CONSTRAINT assets_loans_inspector_return_user_id_fkey FOREIGN KEY (inspector_return_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.assets_loans
    ADD CONSTRAINT assets_loans_lender_user_id_fkey FOREIGN KEY (lender_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.materials(id);

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_type_id_fkey FOREIGN KEY (type_id) REFERENCES public.cfg_assets_types(id);

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_unit_asset_tag_id_fkey FOREIGN KEY (unit_asset_tag_id) REFERENCES public.cfg_units_assets_tags(id);

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.units(id);

ALTER TABLE ONLY public.cfg_app_notices
    ADD CONSTRAINT cfg_app_notices_created_user_id_fkey FOREIGN KEY (created_user_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.cfg_app_tips_companies
    ADD CONSTRAINT cfg_app_tips_companies_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.cfg_companies(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.cfg_app_tips_companies
    ADD CONSTRAINT cfg_app_tips_companies_tip_id_fkey FOREIGN KEY (tip_id) REFERENCES public.cfg_app_tips(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.cfg_app_tips
    ADD CONSTRAINT cfg_app_tips_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);

ALTER TABLE ONLY public.cfg_app_tips_departments
    ADD CONSTRAINT cfg_app_tips_departments_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.cfg_departments(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.cfg_app_tips_departments
    ADD CONSTRAINT cfg_app_tips_departments_tip_id_fkey FOREIGN KEY (tip_id) REFERENCES public.cfg_app_tips(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.cfg_app_tips_dismissals
    ADD CONSTRAINT cfg_app_tips_dismissals_tip_id_fkey FOREIGN KEY (tip_id) REFERENCES public.cfg_app_tips(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.cfg_app_tips_dismissals
    ADD CONSTRAINT cfg_app_tips_dismissals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.cfg_app_tips_profiles
    ADD CONSTRAINT cfg_app_tips_profiles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.cfg_profiles(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.cfg_app_tips_profiles
    ADD CONSTRAINT cfg_app_tips_profiles_tip_id_fkey FOREIGN KEY (tip_id) REFERENCES public.cfg_app_tips(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.cfg_assets_attributes
    ADD CONSTRAINT cfg_assets_attributes_select_options_group_id_fkey FOREIGN KEY (select_options_group_id) REFERENCES public.cfg_assets_attributes_groups(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.cfg_assets_types_attributes
    ADD CONSTRAINT cfg_assets_types_attributes_asset_type_id_fkey FOREIGN KEY (asset_type_id) REFERENCES public.cfg_assets_types(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.cfg_assets_types_attributes
    ADD CONSTRAINT cfg_assets_types_attributes_attribute_id_fkey FOREIGN KEY (attribute_id) REFERENCES public.cfg_assets_attributes(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.cfg_assets_types_loans_checklists
    ADD CONSTRAINT cfg_assets_types_loans_checklists_asset_type_id_fkey FOREIGN KEY (asset_type_id) REFERENCES public.cfg_assets_types(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.cfg_assets_types_loans_checklists
    ADD CONSTRAINT cfg_assets_types_loans_checklists_checklist_id_fkey FOREIGN KEY (checklist_id) REFERENCES public.cfg_loans_checklists(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.cfg_units_assets_tags
    ADD CONSTRAINT cfg_units_assets_tags_asset_tag_id_fkey FOREIGN KEY (asset_tag_id) REFERENCES public.cfg_assets_tags(id) ON UPDATE CASCADE;

ALTER TABLE ONLY public.cfg_units_assets_tags
    ADD CONSTRAINT cfg_units_assets_tags_asset_tag_sub_id_fkey FOREIGN KEY (asset_tag_sub_id) REFERENCES public.cfg_assets_tags_subs(id) ON UPDATE CASCADE;

ALTER TABLE ONLY public.cfg_units_assets_tags
    ADD CONSTRAINT cfg_units_assets_tags_created_user_id_fkey FOREIGN KEY (created_user_id) REFERENCES public.users(id) ON UPDATE CASCADE;

ALTER TABLE ONLY public.cfg_units_assets_tags
    ADD CONSTRAINT cfg_units_assets_tags_deleted_user_id_fkey FOREIGN KEY (deleted_user_id) REFERENCES public.users(id) ON UPDATE CASCADE;

ALTER TABLE ONLY public.cfg_units_assets_tags
    ADD CONSTRAINT cfg_units_assets_tags_last_created_user_id_fkey FOREIGN KEY (last_created_user_id) REFERENCES public.users(id) ON UPDATE CASCADE;

ALTER TABLE ONLY public.cfg_units_assets_tags
    ADD CONSTRAINT cfg_units_assets_tags_last_processing_id_fkey FOREIGN KEY (last_processing_id) REFERENCES public.cfg_assets_available_processing(id) ON UPDATE CASCADE;

ALTER TABLE ONLY public.cfg_units_assets_tags
    ADD CONSTRAINT cfg_units_assets_tags_last_reported_user_id_fkey FOREIGN KEY (last_reported_user_id) REFERENCES public.users(id) ON UPDATE CASCADE;

ALTER TABLE ONLY public.cfg_units_assets_tags
    ADD CONSTRAINT cfg_units_assets_tags_last_reported_user_id_fkey1 FOREIGN KEY (last_reported_user_id) REFERENCES public.users(id) ON UPDATE CASCADE;

ALTER TABLE ONLY public.cfg_units_assets_tags
    ADD CONSTRAINT cfg_units_assets_tags_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.units(id) ON UPDATE CASCADE;

ALTER TABLE ONLY public.contracts_evaluation_requirements
    ADD CONSTRAINT contracts_evaluation_requirements_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.contracts_evaluation_requirements
    ADD CONSTRAINT contracts_evaluation_requirements_evaluation_id_fkey FOREIGN KEY (evaluation_id) REFERENCES public.cfg_evaluation_requirements(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.contracts_managers
    ADD CONSTRAINT contracts_managers_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY public.extensions
    ADD CONSTRAINT extensions_tenant_external_id_fkey FOREIGN KEY (tenant_external_id) REFERENCES public.tenants(external_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.assets_alerts
    ADD CONSTRAINT fk_assets_alerts_order FOREIGN KEY (o_id) REFERENCES public.orders(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.materials_purchases
    ADD CONSTRAINT fk_materials_purchases_cancel_reason FOREIGN KEY (cancel_reason_id) REFERENCES public.cfg_materials_purchases_cancel_reasons(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.leader_monthly_scores
    ADD CONSTRAINT leader_monthly_scores_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.cfg_departments(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.leader_monthly_scores
    ADD CONSTRAINT leader_monthly_scores_leader_id_fkey FOREIGN KEY (leader_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.leader_score_badges
    ADD CONSTRAINT leader_score_badges_leader_id_fkey FOREIGN KEY (leader_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.leader_scores_history
    ADD CONSTRAINT leader_scores_history_leader_id_fkey FOREIGN KEY (leader_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.leader_scores_history
    ADD CONSTRAINT leader_scores_history_ov_id_fkey FOREIGN KEY (ov_id) REFERENCES public.orders_visits(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.maintenances_plans_sections_activities
    ADD CONSTRAINT maintenances_plans_sections_ac_maintenance_plan_section_id_fkey FOREIGN KEY (maintenance_plan_section_id) REFERENCES public.maintenances_plans_sections(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.maintenances_plans_sections_activities
    ADD CONSTRAINT maintenances_plans_sections_activities_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.cfg_activities(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.maintenances_plans_sections
    ADD CONSTRAINT maintenances_plans_sections_maintenance_plan_id_fkey FOREIGN KEY (maintenance_plan_id) REFERENCES public.maintenances_plans(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_cancel_reason_id_fkey FOREIGN KEY (cancel_reason_id) REFERENCES public.cfg_orders_cancel_reasons(id) ON UPDATE CASCADE;

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_object_id_fkey FOREIGN KEY (object_id) REFERENCES public.cfg_orders_objects(id);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_type_id_fkey FOREIGN KEY (type_id) REFERENCES public.cfg_orders_types(id) ON UPDATE CASCADE;

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_type_sub_id_fkey FOREIGN KEY (type_sub_id) REFERENCES public.cfg_orders_types_subs(id) ON UPDATE CASCADE;

ALTER TABLE ONLY public.orders_visits_assets_activities
    ADD CONSTRAINT orders_visits_assets_activities_maintenance_plan_id_fkey FOREIGN KEY (maintenance_plan_id) REFERENCES public.maintenances_plans(id);

ALTER TABLE ONLY public.orders_visits_assets
    ADD CONSTRAINT orders_visits_assets_after_unit_id_fkey FOREIGN KEY (after_unit_id) REFERENCES public.units(id);

ALTER TABLE ONLY public.orders_visits_assets
    ADD CONSTRAINT orders_visits_assets_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.assets(id);

ALTER TABLE ONLY public.orders_visits_assets
    ADD CONSTRAINT orders_visits_assets_before_unit_id_fkey FOREIGN KEY (before_unit_id) REFERENCES public.units(id);

ALTER TABLE ONLY public.orders_visits_assets
    ADD CONSTRAINT orders_visits_assets_ov_id_fkey FOREIGN KEY (ov_id) REFERENCES public.orders_visits(id);

ALTER TABLE ONLY public.orders_visits_assets
    ADD CONSTRAINT orders_visits_assets_ov_id_fkey1 FOREIGN KEY (ov_id) REFERENCES public.orders_visits(id);

ALTER TABLE ONLY public.orders_visits
    ADD CONSTRAINT orders_visits_chat_closed_user_id_fkey FOREIGN KEY (chat_closed_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.orders_visits
    ADD CONSTRAINT orders_visits_chat_created_user_id_fkey FOREIGN KEY (chat_created_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.orders_visits_chat
    ADD CONSTRAINT orders_visits_chat_ov_id_fkey FOREIGN KEY (ov_id) REFERENCES public.orders_visits(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.orders_visits_chat_participants
    ADD CONSTRAINT orders_visits_chat_participants_ov_id_fkey FOREIGN KEY (ov_id) REFERENCES public.orders_visits(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.orders_visits_chat_participants
    ADD CONSTRAINT orders_visits_chat_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.orders_visits_chat_reads
    ADD CONSTRAINT orders_visits_chat_reads_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES public.orders_visits_chat(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.orders_visits_chat_reads
    ADD CONSTRAINT orders_visits_chat_reads_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.orders_visits_chat
    ADD CONSTRAINT orders_visits_chat_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.orders_visits_evaluations
    ADD CONSTRAINT orders_visits_evaluations_contract_evaluation_id_fkey FOREIGN KEY (contract_evaluation_id) REFERENCES public.contracts_evaluation_requirements(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.orders_visits_evaluations
    ADD CONSTRAINT orders_visits_evaluations_evaluated_by_user_id_fkey FOREIGN KEY (evaluated_by_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.orders_visits_evaluations
    ADD CONSTRAINT orders_visits_evaluations_ov_id_fkey FOREIGN KEY (ov_id) REFERENCES public.orders_visits(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.orders_visits_extras
    ADD CONSTRAINT orders_visits_extras_asset_tag_id_fkey FOREIGN KEY (asset_tag_id) REFERENCES public.cfg_assets_tags(id);

ALTER TABLE ONLY public.orders_visits_extras_followers
    ADD CONSTRAINT orders_visits_extras_followers_ove_id_fkey FOREIGN KEY (ove_id) REFERENCES public.orders_visits_extras(id);

ALTER TABLE ONLY public.orders_visits_extras_followers
    ADD CONSTRAINT orders_visits_extras_followers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.orders_visits_extras
    ADD CONSTRAINT orders_visits_extras_o_cause_reason_id_fkey FOREIGN KEY (o_cause_reason_id) REFERENCES public.cfg_orders_causes_reasons(id);

ALTER TABLE ONLY public.orders_visits_extras
    ADD CONSTRAINT orders_visits_extras_o_type_id_fkey FOREIGN KEY (o_type_id) REFERENCES public.cfg_orders_types(id);

ALTER TABLE ONLY public.orders_visits_extras
    ADD CONSTRAINT orders_visits_extras_o_type_sub_id_fkey FOREIGN KEY (o_type_sub_id) REFERENCES public.cfg_orders_types_subs(id);

ALTER TABLE ONLY public.orders_visits_extras
    ADD CONSTRAINT orders_visits_extras_priority_id_fkey FOREIGN KEY (priority_id) REFERENCES public.cfg_orders_priorities(id);

ALTER TABLE ONLY public.orders_visits_extras
    ADD CONSTRAINT orders_visits_extras_processing_id_fkey FOREIGN KEY (processing_id) REFERENCES public.cfg_orders_visits_extras_processing(id);

ALTER TABLE ONLY public.orders_visits_extras
    ADD CONSTRAINT orders_visits_extras_system_id_fkey FOREIGN KEY (system_id) REFERENCES public.cfg_systems(id);

ALTER TABLE ONLY public.orders_visits_extras
    ADD CONSTRAINT orders_visits_extras_system_id_fkey1 FOREIGN KEY (system_id) REFERENCES public.cfg_systems(id);

ALTER TABLE ONLY public.orders_visits_extras
    ADD CONSTRAINT orders_visits_extras_system_parent_id_fkey FOREIGN KEY (system_parent_id) REFERENCES public.cfg_systems(id);

ALTER TABLE ONLY public.orders_visits_extras
    ADD CONSTRAINT orders_visits_extras_system_parent_id_fkey1 FOREIGN KEY (system_parent_id) REFERENCES public.cfg_systems(id);

ALTER TABLE ONLY public.orders_visits_extras
    ADD CONSTRAINT orders_visits_extras_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.cfg_teams(id);

ALTER TABLE ONLY public.orders_visits_extras
    ADD CONSTRAINT orders_visits_extras_team_leader_id_fkey FOREIGN KEY (team_leader_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.orders_visits_extras_teams
    ADD CONSTRAINT orders_visits_extras_teams_ove_id_fkey FOREIGN KEY (ove_id) REFERENCES public.orders_visits_extras(id);

ALTER TABLE ONLY public.orders_visits_extras_teams
    ADD CONSTRAINT orders_visits_extras_teams_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.orders_visits_extras
    ADD CONSTRAINT orders_visits_extras_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.units(id);

ALTER TABLE ONLY public.orders_visits_extras
    ADD CONSTRAINT orders_visits_extras_unit_type_id_fkey FOREIGN KEY (unit_type_id) REFERENCES public.cfg_units_types(id);

ALTER TABLE ONLY public.orders_visits_extras
    ADD CONSTRAINT orders_visits_extras_unit_type_parent_id_fkey FOREIGN KEY (unit_type_parent_id) REFERENCES public.cfg_units_types(id);

ALTER TABLE ONLY public.orders_visits
    ADD CONSTRAINT orders_visits_ov_costs_approved_user_id_fkey FOREIGN KEY (ov_costs_approved_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.orders_visits
    ADD CONSTRAINT orders_visits_ov_costs_rejected_user_id_fkey FOREIGN KEY (ov_costs_rejected_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.orders_visits
    ADD CONSTRAINT orders_visits_ov_costs_submitted_user_id_fkey FOREIGN KEY (ov_costs_waiting_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.orders_visits_vehicles
    ADD CONSTRAINT orders_visits_vehicles_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.cfg_profiles_access
    ADD CONSTRAINT profiles_access_profile_fkey FOREIGN KEY (profile_id) REFERENCES public.cfg_profiles(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.cfg_profiles_access
    ADD CONSTRAINT profiles_access_route_fkey FOREIGN KEY (route_id) REFERENCES public.cfg_routes(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.cfg_profiles
    ADD CONSTRAINT public_usersprofiles_departmentid_fkey FOREIGN KEY (department_id) REFERENCES public.cfg_departments(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY public.cfg_routes
    ADD CONSTRAINT routes_parent_fkey FOREIGN KEY (parent_id) REFERENCES public.cfg_routes(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.cfg_app_notices
    ADD CONSTRAINT system_notices_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.cfg_app_notices_categories(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.cfg_app_notices
    ADD CONSTRAINT system_notices_severity_id_fkey FOREIGN KEY (severity_id) REFERENCES public.cfg_app_notices_severities(id) ON DELETE RESTRICT;

ALTER TABLE ONLY public.technicals_manuals_files
    ADD CONSTRAINT technicals_manuals_files_tm_category_id_fkey FOREIGN KEY (tm_category_id) REFERENCES public.cfg_technicals_manuals_categories(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.technicals_manuals_files
    ADD CONSTRAINT technicals_manuals_files_tm_id_fkey FOREIGN KEY (tm_id) REFERENCES public.technicals_manuals(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tools
    ADD CONSTRAINT tools_created_user_id_fkey FOREIGN KEY (created_user_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.tools
    ADD CONSTRAINT tools_deleted_user_id_fkey FOREIGN KEY (deleted_user_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.tools
    ADD CONSTRAINT tools_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.materials(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.tools
    ADD CONSTRAINT tools_updated_user_id_fkey FOREIGN KEY (updated_user_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.units
    ADD CONSTRAINT units_unit_type_id_fkey FOREIGN KEY (unit_type_id) REFERENCES public.cfg_units_types(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.users_notifications
    ADD CONSTRAINT users_notifications_user_id_from_fkey FOREIGN KEY (user_id_from) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.users_notifications
    ADD CONSTRAINT users_notifications_user_id_to_fkey FOREIGN KEY (user_id_to) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.cfg_profiles(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_status_id_fkey FOREIGN KEY (status_id) REFERENCES public.cfg_users_statuses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.cfg_teams(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY public.users_tools
    ADD CONSTRAINT users_tools_created_user_id_fkey FOREIGN KEY (created_user_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.users_tools_movements
    ADD CONSTRAINT users_tools_movements_created_user_id_fkey FOREIGN KEY (created_user_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.users_tools_movements
    ADD CONSTRAINT users_tools_movements_from_user_id_fkey FOREIGN KEY (from_user_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.users_tools_movements
    ADD CONSTRAINT users_tools_movements_to_user_id_fkey FOREIGN KEY (to_user_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.users_tools_movements
    ADD CONSTRAINT users_tools_movements_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tools(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.users_tools
    ADD CONSTRAINT users_tools_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tools(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.users_tools
    ADD CONSTRAINT users_tools_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.warehouses_materials
    ADD CONSTRAINT warehouses_materials_deleted_user_id_fkey FOREIGN KEY (deleted_user_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.warehouses_materials
    ADD CONSTRAINT warehouses_materials_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.materials(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.warehouses_materials
    ADD CONSTRAINT warehouses_materials_updated_user_id_fkey FOREIGN KEY (updated_user_id) REFERENCES public.users(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.warehouses_materials
    ADD CONSTRAINT warehouses_materials_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE CASCADE;

ALTER TABLE ONLY storage.iceberg_namespaces
    ADD CONSTRAINT iceberg_namespaces_bucket_id_fkey FOREIGN KEY (bucket_id) REFERENCES storage.buckets_analytics(id) ON DELETE CASCADE;

ALTER TABLE ONLY storage.iceberg_tables
    ADD CONSTRAINT iceberg_tables_bucket_id_fkey FOREIGN KEY (bucket_id) REFERENCES storage.buckets_analytics(id) ON DELETE CASCADE;

ALTER TABLE ONLY storage.iceberg_tables
    ADD CONSTRAINT iceberg_tables_namespace_id_fkey FOREIGN KEY (namespace_id) REFERENCES storage.iceberg_namespaces(id) ON DELETE CASCADE;

ALTER TABLE ONLY storage.objects
    ADD CONSTRAINT "objects_bucketId_fkey" FOREIGN KEY (bucket_id) REFERENCES storage.buckets(id);

ALTER TABLE ONLY storage.prefixes
    ADD CONSTRAINT "prefixes_bucketId_fkey" FOREIGN KEY (bucket_id) REFERENCES storage.buckets(id);

ALTER TABLE ONLY storage.s3_multipart_uploads
    ADD CONSTRAINT s3_multipart_uploads_bucket_id_fkey FOREIGN KEY (bucket_id) REFERENCES storage.buckets(id);

ALTER TABLE ONLY storage.s3_multipart_uploads_parts
    ADD CONSTRAINT s3_multipart_uploads_parts_bucket_id_fkey FOREIGN KEY (bucket_id) REFERENCES storage.buckets(id);

ALTER TABLE ONLY storage.s3_multipart_uploads_parts
    ADD CONSTRAINT s3_multipart_uploads_parts_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES storage.s3_multipart_uploads(id) ON DELETE CASCADE;

ALTER TABLE ONLY storage.vector_indexes
    ADD CONSTRAINT vector_indexes_bucket_id_fkey FOREIGN KEY (bucket_id) REFERENCES storage.buckets_vectors(id);

ALTER TABLE auth.audit_log_entries ENABLE ROW LEVEL SECURITY;

ALTER TABLE auth.flow_state ENABLE ROW LEVEL SECURITY;

ALTER TABLE auth.identities ENABLE ROW LEVEL SECURITY;

ALTER TABLE auth.instances ENABLE ROW LEVEL SECURITY;

ALTER TABLE auth.mfa_amr_claims ENABLE ROW LEVEL SECURITY;

ALTER TABLE auth.mfa_challenges ENABLE ROW LEVEL SECURITY;

ALTER TABLE auth.mfa_factors ENABLE ROW LEVEL SECURITY;

ALTER TABLE auth.one_time_tokens ENABLE ROW LEVEL SECURITY;

ALTER TABLE auth.refresh_tokens ENABLE ROW LEVEL SECURITY;

ALTER TABLE auth.saml_providers ENABLE ROW LEVEL SECURITY;

ALTER TABLE auth.saml_relay_states ENABLE ROW LEVEL SECURITY;

ALTER TABLE auth.schema_migrations ENABLE ROW LEVEL SECURITY;

ALTER TABLE auth.sessions ENABLE ROW LEVEL SECURITY;

ALTER TABLE auth.sso_domains ENABLE ROW LEVEL SECURITY;

ALTER TABLE auth.sso_providers ENABLE ROW LEVEL SECURITY;

ALTER TABLE auth.users ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.ai_chat_histories ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.ai_chat_sessions ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.ai_knowledge ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.ai_messages ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.assets ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.assets_alerts ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.assets_attributes_values ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.assets_available ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.assets_followers ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.assets_loans ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.assets_loans_checklists_images ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.assets_materials ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.audits_logs ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.carts_materials ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_activities ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_app ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_app_notices ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_app_notices_categories ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_app_notices_severities ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_app_offline_updates ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_app_pages ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_app_tips ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_app_tips_companies ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_app_tips_departments ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_app_tips_dismissals ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_app_tips_profiles ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_app_versions_update ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_assets_attributes ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_assets_attributes_groups ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_assets_available_processing ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_assets_couplings_models ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_assets_priorities ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_assets_statuses ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_assets_tags ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_assets_tags_subs ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_assets_types ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_assets_types_attributes ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_assets_types_loans_checklists ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_assets_unavailable_reasons ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_companies ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_contracts_statuses ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_departments ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_evaluation_requirements ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_loans_checklists ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_materials_purchases_cancel_reasons ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_materials_purchases_statuses ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_materials_purchases_types ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_materials_statuses ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_materials_types ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_orders_cancel_reasons ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_orders_causes_reasons ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_orders_counter ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_orders_objects ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_orders_plans ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_orders_priorities ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_orders_statuses ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_orders_suspended_reasons ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_orders_types ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_orders_types_activities ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_orders_types_subs ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_orders_visits_extras_processing ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_orders_visits_processing ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_orders_visits_statuses ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_profiles ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_profiles_access ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_profiles_permissions ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_routes ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_services ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_systems ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_teams ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_technicals_manuals_categories ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_units_assets_tags ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_units_statuses ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_units_types ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.cfg_users_statuses ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.chat_agent_ai ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.contracts ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.contracts_evaluation_requirements ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.contracts_managers ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.contracts_services ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.extensions ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.goose_db_version ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.impersonation_password_backup ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.import_orders_visits_contracts ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.leader_monthly_scores ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.leader_score_badges ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.leader_scores_history ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.logs_api ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.maintenances_plans ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.maintenances_plans_sections ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.maintenances_plans_sections_activities ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.materials_purchases ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.n8n_chat_histories ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.orders_followers ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.orders_statuses_logs ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.orders_visits ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.orders_visits_assets ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.orders_visits_assets_activities ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.orders_visits_assets_materials ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.orders_visits_chat ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.orders_visits_chat_participants ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.orders_visits_chat_reads ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.orders_visits_evaluations ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.orders_visits_extras ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.orders_visits_extras_followers ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.orders_visits_extras_teams ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.orders_visits_services ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.orders_visits_teams ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.orders_visits_vehicles ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.schema_migrations ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.technicals_manuals ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.technicals_manuals_assets ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.technicals_manuals_files ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.tools ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.units ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.users_notifications ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.users_tools ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.users_tools_movements ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.users_tracker ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.warehouses ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.warehouses_materials ENABLE ROW LEVEL SECURITY;

ALTER TABLE storage.buckets ENABLE ROW LEVEL SECURITY;

ALTER TABLE storage.buckets_analytics ENABLE ROW LEVEL SECURITY;

ALTER TABLE storage.buckets_vectors ENABLE ROW LEVEL SECURITY;

ALTER TABLE storage.iceberg_namespaces ENABLE ROW LEVEL SECURITY;

ALTER TABLE storage.iceberg_tables ENABLE ROW LEVEL SECURITY;

ALTER TABLE storage.migrations ENABLE ROW LEVEL SECURITY;

ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

ALTER TABLE storage.prefixes ENABLE ROW LEVEL SECURITY;

ALTER TABLE storage.s3_multipart_uploads ENABLE ROW LEVEL SECURITY;

ALTER TABLE storage.s3_multipart_uploads_parts ENABLE ROW LEVEL SECURITY;

ALTER TABLE storage.vector_indexes ENABLE ROW LEVEL SECURITY;
