-- =============================================================================
-- Seed Data: cfg_activities
-- Exported: 2026-03-05T17:29:21.462Z
-- Records: 661
-- =============================================================================

INSERT INTO public.cfg_activities (id, company_id, department_id, description, is_available, is_deleted, code)
VALUES
    (1, 1, 9, '(INFORMACOES DIVERSAS)', true, false, NULL),
    (47, 1, 9, 'Ajuste de gaxetas', true, true, NULL),
    (161, 1, 9, 'Informacoes diversas', true, true, NULL),
    (206, 1, 9, 'Solicitacao de servicos', true, true, NULL),
    (317, 1, 9, 'Substituicao gaxetas', true, true, NULL),
    (318, 1, 9, 'SUBSTITUICAO ROLAMENTO', true, true, NULL),
    (319, 1, 9, 'Substituicao selo mecanico', true, true, NULL),
    (320, 1, 9, 'Substituicao rotor', true, true, NULL),
    (321, 1, 9, 'Substituicao acoplamento', true, true, NULL),
    (322, 1, 9, 'Substituicao lubrificante', false, true, NULL),
    (323, 1, 9, 'Substituicao estator', true, true, NULL),
    (324, 1, 9, 'SUBSTITUICAO EIXO', true, true, NULL),
    (325, 1, 9, 'Substituicao membrana', true, true, NULL),
    (326, 1, 9, 'Substituicao membrana', false, true, NULL),
    (327, 1, 9, 'Substituicao anel oring', false, true, NULL),
    (328, 1, 9, 'Retirado equipamento', true, true, NULL),
    (329, 1, 9, 'Transporte equipamento p/terceiros', true, true, NULL),
    (330, 1, 9, 'INSTALACAO (ANDAMENTO)', true, false, NULL),
    (331, 1, 9, 'Escorvado', true, true, NULL),
    (332, 1, 9, 'Alinhado', true, true, NULL),
    (333, 1, 9, 'LIMPEZA', true, false, NULL),
    (334, 1, 9, 'REAPERTO CONEXAO(OES)', true, false, NULL),
    (335, 1, 9, 'Ajuste de fixacao', true, true, NULL),
    (336, 1, 9, 'Limpeza do rotametro', false, true, NULL),
    (337, 1, 9, 'Regulagem modulo de desvio', true, true, NULL),
    (338, 1, 9, 'Alteracao linha produto/ponto aplicacao', true, true, NULL),
    (339, 1, 9, 'Substituicao conexao/tubulacao', true, true, NULL),
    (340, 1, 9, 'Desobstrucao linha produto', true, true, NULL),
    (341, 1, 9, 'Melhoria no equipamento', true, true, NULL),
    (342, 1, 9, 'Regulagem diversa', false, true, NULL),
    (343, 1, 9, 'Substituicao componentes diversos', true, true, NULL),
    (344, 1, 9, 'Confeccao peca especial', true, true, NULL),
    (345, 1, 9, 'SUBSTITUICAO FUSIVEL (BT)', true, false, NULL),
    (346, 1, 9, 'SUBSTITUICAO RSC', true, false, NULL),
    (347, 1, 9, 'SUBSTITUICAO RFF', true, false, NULL),
    (348, 1, 9, 'REGULAGEM RFF', true, false, NULL),
    (349, 1, 9, 'REGULAGEM RSC', true, false, NULL),
    (350, 1, 9, 'SUBSTITUICAO AMPERIMETRO', true, false, NULL),
    (351, 1, 9, 'SUBSTITUICAO VOLTIMETRO', true, false, NULL),
    (352, 1, 9, 'REMOCAO AMPERIMETRO', true, false, NULL),
    (353, 1, 9, 'REMOCAO VOLTIMETRO', true, false, NULL),
    (354, 1, 9, 'INSTALACAO AMPERIMETRO', true, false, NULL),
    (355, 1, 9, 'INSTALACAO VOLTIMETRO', true, false, NULL),
    (356, 1, 9, 'SUBSTITUICAO HOROMETRO', true, false, NULL),
    (357, 1, 9, 'REMOCAO HOROMETRO', true, false, NULL),
    (358, 1, 9, 'INSTALACAO HOROMETRO', true, false, NULL),
    (359, 1, 9, 'Retificado motor', true, true, NULL),
    (360, 1, 9, 'Completado oleo lubrificante', true, true, NULL),
    (361, 1, 9, 'Substituicao oleo lubrificante', true, true, NULL),
    (362, 1, 9, 'Substituicao filtro oleo lubrificante', true, true, NULL),
    (363, 1, 9, 'Substituicao filtro oleo hidraulico', true, true, NULL),
    (364, 1, 9, 'Substituicao oleo hidraulico', true, true, NULL),
    (365, 1, 9, 'Completado oleo hidraulico', true, true, NULL),
    (366, 1, 9, 'Substituicao filtro ar', true, true, NULL),
    (367, 1, 9, 'Substituicao bomba alimentadora', true, true, NULL),
    (368, 1, 9, 'Substituicao pastilha de freio', true, true, NULL),
    (369, 1, 9, 'Substituicao lampada', true, true, NULL),
    (370, 1, 9, 'SUBSTITUICAO FUSIVEL', false, false, NULL),
    (371, 1, 9, 'Substituicao pneu', true, true, NULL),
    (372, 1, 9, 'Conserto pneu', true, true, NULL),
    (373, 1, 9, 'Recuperacao pneu', true, true, NULL),
    (374, 1, 9, 'Calibracao pneu', true, true, NULL),
    (375, 1, 9, 'Substituicao farol', true, true, NULL),
    (376, 1, 9, 'Substituicao sinaleira', true, true, NULL),
    (377, 1, 9, 'Lavagem geral', true, true, NULL),
    (378, 1, 9, 'Substituicao espelho retrovisor', true, true, NULL),
    (379, 1, 9, 'Substituicao trinque/macaneta/manivela', true, true, NULL),
    (380, 1, 9, 'Chapeacao/pintura', true, true, NULL),
    (381, 1, 9, 'Substituicao para-choque', true, true, NULL),
    (382, 1, 9, 'Substituicao amortecedor', true, true, NULL),
    (383, 1, 9, 'Substituicao lona de freio', true, true, NULL),
    (384, 1, 9, 'Substituicao motor de partida', true, true, NULL),
    (385, 1, 9, 'Limpeza filtro de ar', true, true, NULL),
    (386, 1, 9, 'Encaminhado para orcamento', true, true, NULL),
    (387, 1, 9, 'Encaminhado para conserto', true, true, NULL),
    (388, 1, 9, 'Substituicao chave-boia', true, true, NULL),
    (389, 1, 9, 'SUBSTITUICAO RELE NIVEL', true, false, NULL),
    (390, 1, 9, 'SUBSTITUICAO CONTACTOR', true, false, NULL),
    (391, 1, 9, 'Regulagem de freios', true, true, NULL),
    (392, 1, 9, 'SUBSTITUICAO VENTOINHA', true, false, NULL),
    (393, 1, 9, 'Substituicao pino elastico', true, true, NULL),
    (394, 1, 9, 'Regulagem chave-boia', true, true, NULL),
    (395, 1, 9, 'Substituicao lente', true, true, NULL),
    (396, 1, 9, 'Plantao tecnico', true, true, NULL),
    (397, 1, 9, 'SUBSTITUICAO BATERIA', true, false, NULL),
    (398, 1, 9, 'REMOCAO BATERIA', true, false, NULL),
    (399, 1, 9, 'INSTALACAO BATERIA', true, false, NULL),
    (400, 1, 9, 'Conserto alternador', true, true, NULL),
    (401, 1, 9, 'Substituicao radio', true, true, NULL),
    (402, 1, 9, 'Substituicao antena', true, true, NULL),
    (403, 1, 9, 'Programacao radio', true, true, NULL),
    (404, 1, 9, 'Substituicao cabos (comunicacao)', true, true, NULL),
    (405, 1, 9, 'Substituicao centelhador', true, true, NULL),
    (406, 1, 9, 'Substituicao placa e/s digital', true, true, NULL),
    (407, 1, 9, 'AJUSTES CONFIGURACAO', true, true, NULL),
    (408, 1, 9, 'Substituicao placa e/s analogica', true, true, NULL),
    (409, 1, 9, 'SUBSTITUIÇÃO ELO FUSIVEL (AT)', true, false, NULL),
    (410, 1, 9, 'SUBSTITUICAO CHAVE FUSIVEL (AT)', true, false, NULL),
    (411, 1, 9, 'SUBSTITUICAO CHAVE SECCIONADORA(AT)', true, false, NULL),
    (412, 1, 9, 'INSTALACAO ATERRAMENTO (AT)', true, false, NULL),
    (413, 1, 9, 'SUBSTITUICAO PARA RAIO (AT) (at)', true, false, NULL),
    (414, 1, 9, 'Substituicao isolador at', true, true, NULL),
    (415, 1, 9, 'Substituicao poste (at)', true, true, NULL),
    (416, 1, 9, 'Substituicao cruzeta (at)', true, true, NULL),
    (417, 1, 9, 'Substituicao autotrafo', true, true, NULL),
    (418, 1, 9, 'Substituicao contatos (circ.princ)', true, true, NULL),
    (419, 1, 9, 'Substituicao contator (circ.princ)', true, true, NULL),
    (420, 1, 9, 'Instalacao antena', true, true, NULL),
    (421, 1, 9, 'Substituicao fonte (sist.comunicacao)', true, true, NULL),
    (422, 1, 9, 'Substituicao protetor surto ac/dc', true, true, NULL),
    (423, 1, 9, 'Substituicao tiristores', true, true, NULL),
    (424, 1, 9, 'Substituicao diodos', true, true, NULL),
    (425, 1, 9, 'Substituicao compressor', true, true, NULL),
    (426, 1, 9, 'Limpeza externa', true, true, NULL),
    (428, 1, 9, 'Complementado lubrificante', true, true, NULL),
    (429, 1, 9, 'Checagem dados operacionais', true, true, NULL),
    (430, 1, 9, 'Regulagem diversas', true, true, NULL),
    (431, 1, 9, 'Transporte equipamento', true, true, NULL),
    (432, 1, 9, 'Transporte material', true, true, NULL),
    (433, 1, 9, 'Montagem equipamento', true, true, NULL),
    (434, 1, 9, 'Ponte na bateria', true, true, NULL),
    (435, 1, 9, 'Limpeza filtro combustivel', true, true, NULL),
    (436, 1, 9, 'Limpeza bicos injetores', true, true, NULL),
    (437, 1, 9, 'Limpeza tanque combustivel', true, true, NULL),
    (438, 1, 9, 'LUBRIFICACAO', true, false, NULL),
    (439, 1, 9, 'Substituicao radiador', true, true, NULL),
    (440, 1, 9, 'Completado liq.arrefecimento', true, true, NULL),
    (441, 1, 9, 'Substituicao mang/conexao (sist.arref)', true, true, NULL),
    (442, 1, 9, 'Substituicao limp.para-brisa', true, true, NULL),
    (443, 1, 9, 'Regulagem limp.para-brisa', true, true, NULL),
    (444, 1, 9, 'Substituicao de eletrodos', true, true, NULL),
    (445, 1, 9, 'Rearme do disjuntor', true, true, NULL),
    (446, 1, 9, 'Retirado compressor', false, true, NULL),
    (447, 1, 9, 'Instalado compressor', true, true, NULL),
    (448, 1, 9, 'Substituicao ventilador', true, true, NULL),
    (449, 1, 9, 'Colocacao gas refrigerante', true, true, NULL),
    (450, 1, 9, 'Substituicao serpentina', true, true, NULL),
    (451, 1, 9, 'Servicos de pintura', true, true, NULL),
    (452, 1, 9, 'Regulagem termostato', true, true, NULL),
    (453, 1, 9, 'Substituicao termostato', true, true, NULL),
    (454, 1, 9, 'Substituicao vedacao espuma', true, true, NULL),
    (455, 1, 9, 'Substituicao condensador', true, true, NULL),
    (456, 1, 9, 'Substituicao filtro de ar', false, true, NULL),
    (457, 1, 9, 'Limpeza filtro evaporador', true, true, NULL),
    (458, 1, 9, 'Limpeza espirais', true, true, NULL),
    (459, 1, 9, 'Desumidificado', true, true, NULL),
    (460, 1, 9, 'Substituicao bobina contator (circ.princ)', true, true, NULL),
    (461, 1, 9, 'Substituicao resistencia', true, true, NULL),
    (462, 1, 9, 'Substituicao ch.fim-de-curso', true, true, NULL),
    (463, 1, 9, 'Substituicao base fusivel nh', true, true, NULL),
    (464, 1, 9, 'RESETADO EQUIPAMENTO', true, true, NULL),
    (500, 1, 9, 'Regulagem alternador', true, true, NULL),
    (501, 1, 9, 'Substituicao terminal/cabo bateria', true, true, NULL),
    (502, 1, 9, 'Servicos solda', false, true, NULL),
    (503, 1, 9, 'Substituicao apara-barro', true, true, NULL),
    (504, 1, 9, 'Substituicao mangueira (tq.pipa)', true, true, NULL),
    (505, 1, 9, 'Limpeza bomba alimentadora combustivel', true, true, NULL),
    (506, 1, 9, 'Completado combustivel', true, true, NULL),
    (507, 1, 9, 'Reaperto abrac/conex/mang (tq.pipa)', true, true, NULL),
    (508, 1, 9, 'Substituicao abracadeira/conexao (tq.pipa)', true, true, NULL),
    (509, 1, 9, 'Reaperto abrac/conex/mang (sist.alim)', true, true, NULL),
    (510, 1, 9, 'Substituicao abrac/conex/mang (sist.alim)', true, true, NULL),
    (511, 1, 9, 'Substituicao mang/conexao (sist.alim.)', true, true, NULL),
    (512, 1, 9, 'Identificacao pneu', true, true, NULL),
    (513, 1, 9, 'Revisao embreagem', true, true, NULL),
    (514, 1, 9, 'Substituicao liq.arrefecimento', true, true, NULL),
    (515, 1, 9, 'Completado liq.freio', true, true, NULL),
    (516, 1, 9, 'Substituicao mang/conexao (sist.freio)', true, true, NULL),
    (517, 1, 9, 'Substituicao filtro combustivel', true, true, NULL),
    (518, 1, 9, 'Substituicao cabo acelerador', true, true, NULL),
    (519, 1, 9, 'Regulagem cabo acelerador', true, true, NULL),
    (520, 1, 9, 'Substituicao disco de freio', true, true, NULL),
    (521, 1, 9, 'Substituicao cilindro freio', true, true, NULL),
    (522, 1, 9, 'Substituicao bomba dagua', true, true, NULL),
    (523, 1, 9, 'Substituicao tampa filtro ar', true, true, NULL),
    (524, 1, 9, 'Substituicao boia tq combustivel', true, true, NULL),
    (525, 1, 9, 'Regulagem trinque/macaneta/manivela', true, true, NULL),
    (526, 1, 9, 'Conserto estofamento', true, true, NULL),
    (527, 1, 9, 'Substituicao mang/conexao (sist.hidr)', true, true, NULL),
    (547, 1, 9, 'Servicos diversos de solda', true, true, NULL),
    (548, 1, 9, 'Desmontagem/montagem pneu', true, true, NULL),
    (549, 1, 9, 'Fornecimento material', true, true, NULL),
    (550, 1, 9, 'Substituicao filtro harmonica', true, true, NULL),
    (551, 1, 9, 'Instalacao filtro harmonica', true, true, NULL),
    (552, 1, 9, 'Retirado filtro harmonica (by pass)', true, true, NULL),
    (553, 1, 9, 'Retirada banco arrefcim inverter', true, true, NULL),
    (554, 1, 9, 'Instalacao banco arrefcim inverter', true, true, NULL),
    (555, 1, 9, 'Instalacao banco arrefcim diverter', false, true, NULL),
    (556, 1, 9, 'Retirada banco arrefcim diverter', false, true, NULL),
    (557, 1, 9, 'Substituicao cooler', true, true, NULL),
    (558, 1, 9, 'Comando via ch.partida', true, true, NULL),
    (559, 1, 9, 'Comando via inversor', true, true, NULL),
    (560, 1, 9, 'Rebobinagem', true, true, NULL),
    (561, 1, 9, 'Substituicao escova carvao (sist.induc)', true, true, NULL),
    (562, 1, 9, 'Rebobinagem', false, true, NULL),
    (563, 1, 9, 'Medicao pressao', true, true, NULL),
    (564, 1, 9, 'Limpeza sensor', true, true, NULL),
    (565, 1, 9, 'Limpeza contator/contatos', true, true, NULL),
    (566, 1, 9, 'Medicao capacitancia', true, true, NULL),
    (567, 1, 9, 'Medicao temperatura', true, true, NULL),
    (568, 1, 9, 'Medicao tensao', true, true, NULL),
    (569, 1, 9, 'Medicao corrente eletrica', true, true, NULL),
    (570, 1, 9, 'Reversao para circ.secundario', true, true, NULL),
    (571, 1, 9, 'Reversao para circ.principal', true, true, NULL),
    (572, 1, 9, 'Substituicao mufla', true, true, NULL),
    (573, 1, 9, 'Substituicao cabo at', true, true, NULL),
    (574, 1, 9, 'Reaperto terminal', true, true, NULL),
    (575, 1, 9, 'Substituicao rele tempo', true, true, NULL),
    (576, 1, 9, 'Regulagem rele tempo', true, true, NULL),
    (577, 1, 9, 'Substituicao indicador vazao', true, true, NULL),
    (578, 1, 9, 'Substituicao indicador corrente', true, true, NULL),
    (579, 1, 9, 'Substituicao indicador tensao', true, true, NULL),
    (580, 1, 9, 'Substituicao indicador pressao', true, true, NULL),
    (581, 1, 9, 'Substituicao indicador nivel', true, true, NULL),
    (582, 1, 9, 'Substituicao sensor nivel', true, true, NULL),
    (583, 1, 9, 'Substituicao sensor pressao', true, true, NULL),
    (584, 1, 9, 'VISTORIA TECNICA', true, false, NULL),
    (603, 1, 9, 'Substituicao vela ignicao', true, true, NULL),
    (604, 1, 9, 'Substituicao correia/tensor (alternador)', true, true, NULL),
    (605, 1, 9, 'Solicitacao documentos', true, true, NULL),
    (606, 1, 9, 'Solicitacao termo aditivo', true, true, NULL),
    (607, 1, 9, 'Solicitacao reajuste precos', true, true, NULL),
    (608, 1, 9, 'Substituicao cabo embreagem', true, true, NULL),
    (609, 1, 9, 'Substituicao garfo embreagem', true, true, NULL),
    (610, 1, 9, 'Substituicao rolamento embreagem', true, true, NULL),
    (611, 1, 9, 'Substituicao plato embreagem', true, true, NULL),
    (612, 1, 9, 'Substituicao ponta eixo', true, true, NULL),
    (613, 1, 9, 'Substituicao borboleta embreagem', true, true, NULL),
    (614, 1, 9, 'Substituicao disco embreagem', true, true, NULL),
    (615, 1, 9, 'Substituicao flexivel embreagem', true, true, NULL),
    (616, 1, 9, 'Substituicao rolamento int/ext roda', true, true, NULL),
    (617, 1, 9, 'Substituicao cubo roda', true, true, NULL),
    (618, 1, 9, 'Substituicao retentor roda', true, true, NULL),
    (619, 1, 9, 'Substituicao homocinetica', true, true, NULL),
    (621, 1, 9, 'Substituicao retentor', true, true, NULL),
    (622, 1, 9, 'Substituicao embreagem', true, true, NULL),
    (623, 1, 9, 'Substituicao selo motor', true, true, NULL),
    (624, 1, 9, 'Substituicao cilindro roda', true, true, NULL),
    (625, 1, 9, 'Substituicao liq.freio', true, true, NULL),
    (626, 1, 9, 'Equipamento danificado', true, true, NULL),
    (627, 1, 9, 'Locacao equipamento', true, true, NULL),
    (628, 1, 9, 'Manutencao geral', true, true, NULL),
    (629, 1, 9, 'Recarga bateria', true, true, NULL),
    (630, 1, 9, 'Substituicao bateria p/reserva', true, true, NULL),
    (631, 1, 9, 'Remocao componentes p/compra', true, true, NULL),
    (632, 1, 9, 'Regulagem farol', true, true, NULL),
    (633, 1, 9, 'Regulagem farolete', true, true, NULL),
    (634, 1, 9, 'Conserto alerta marcha a re', true, true, NULL),
    (635, 1, 9, 'Conserto farolete', true, true, NULL),
    (636, 1, 9, 'Conserto chave ignicao', true, true, NULL),
    (637, 1, 9, 'Reinstalacao de equipamento', true, true, NULL),
    (638, 1, 9, 'Conserto sinalizacao rotativa', true, true, NULL),
    (639, 1, 9, 'Inspecionado', true, true, NULL),
    (640, 1, 9, 'Conserto barra estabilizadora', true, true, NULL),
    (641, 1, 9, 'Substituicao bomba oleo (sist.hidr)', true, true, NULL),
    (643, 1, 9, 'Conserto maquina vidro', true, true, NULL),
    (644, 1, 9, 'Equipamento em observacao', true, true, NULL),
    (645, 1, 9, 'Substituicao registro (tq.pipa)', true, true, NULL),
    (646, 1, 9, 'Substituicao cubo roda', false, true, NULL),
    (647, 1, 9, 'Desmontagem de freios', true, true, NULL),
    (648, 1, 9, 'Ligado equipamento', true, true, NULL),
    (649, 1, 9, 'Desligado equipamento', true, true, NULL),
    (650, 1, 9, 'Substituicao alternador', true, true, NULL),
    (651, 1, 9, 'Revisao sist freios', true, true, NULL),
    (652, 1, 9, 'Revisao sist.eletrico', true, true, NULL),
    (653, 1, 9, 'Reaperto cabo/terminal bateria', true, true, NULL),
    (654, 1, 9, 'Reaperto grampo feixe molas', true, true, NULL),
    (655, 1, 9, 'Conserto pedal embreagem', true, true, NULL),
    (656, 1, 9, 'Substituicao botao', true, true, NULL),
    (657, 1, 9, 'Revisao sist.arrefecimento', true, true, NULL),
    (658, 1, 9, 'Substituicao regulador voltagem', true, true, NULL),
    (659, 1, 9, 'Substituicao buzina', true, true, NULL),
    (660, 1, 9, 'Conserto sinalizacao', true, true, NULL),
    (661, 1, 9, 'Consertos diversos (moto-amoladora)', true, true, NULL),
    (662, 1, 9, 'Consertos diversos (motor agrale)', true, true, NULL),
    (663, 1, 9, 'Reaperto descarga', true, true, NULL),
    (664, 1, 9, 'Conserto descarga', true, true, NULL),
    (665, 1, 9, 'Conserto motor de partida', true, true, NULL),
    (666, 1, 9, 'Limpeza caburador', true, true, NULL),
    (667, 1, 9, 'Conserto bomba combustivel', true, true, NULL),
    (668, 1, 9, 'Montagem equipamento (bomba lufersa)', true, true, NULL),
    (669, 1, 9, 'Compra material', true, true, NULL),
    (670, 1, 9, 'Patrimonizacao equipamento', true, true, NULL),
    (671, 1, 9, 'Conserto motor', true, true, NULL),
    (672, 1, 9, 'Conserto sist.suspensao', true, true, NULL),
    (673, 1, 9, 'Balanceamento/geometria', true, true, NULL),
    (674, 1, 9, 'Servicos diversos (chassi)', true, true, NULL),
    (675, 1, 9, 'Substituicao kit ralo', true, true, NULL),
    (676, 1, 9, 'Substituicao bico boca', true, true, NULL),
    (677, 1, 9, 'Substituicao bico copo', true, true, NULL),
    (678, 1, 9, 'Substituicao filtro', true, true, NULL),
    (679, 1, 9, 'Substituicao reservatorio', true, true, NULL),
    (680, 1, 9, 'Substituicao rele', true, true, NULL),
    (681, 1, 9, 'Consertos diversos (bomba lufersa)', true, true, NULL),
    (682, 1, 9, 'Limpeza/organizacao geral (secao)', true, true, NULL),
    (683, 1, 9, 'Substituicao surdina', true, true, NULL),
    (684, 1, 9, 'Substituicao sensor (sist.eletrico)', true, true, NULL),
    (685, 1, 9, 'Conserto para-choque', true, true, NULL),
    (686, 1, 9, 'Substituicao cabos (vela ignicao)', true, true, NULL),
    (687, 1, 9, 'Substituicao rotor (distribuidor)', true, true, NULL),
    (688, 1, 9, 'Substituicao palheta limp.para-brisa', true, true, NULL),
    (689, 1, 9, 'Substituicao pneu p/estepe', true, true, NULL),
    (690, 1, 9, 'Limpeza sist.alimentacao', true, true, NULL),
    (691, 1, 9, 'Regulagem maquina vidro', true, true, NULL),
    (692, 1, 9, 'Substituicao cabo energia', true, true, NULL),
    (693, 1, 9, 'SUBSTITUICAO CHAVE SELETORA', true, false, NULL),
    (694, 1, 9, 'Substituicao tacografo', true, true, NULL),
    (695, 1, 9, 'Conserto tacografo', true, true, NULL),
    (696, 1, 9, 'Substituicao cilindro mestre embreagem', true, true, NULL),
    (697, 1, 9, 'Substituicao sapatas/lonas de freio', true, true, NULL),
    (698, 1, 9, 'Conserto porta', true, true, NULL),
    (699, 1, 9, 'Substituicao vidro janela', true, true, NULL),
    (700, 1, 9, 'Completado oleo lubrificante (cx.mudanca)', true, true, NULL),
    (701, 1, 9, 'Substituicao oleo lubrificante (cx.mudanca)', true, true, NULL),
    (702, 1, 9, 'Conserto janela', true, true, NULL),
    (703, 1, 9, 'Regulagem porta', true, true, NULL),
    (704, 1, 9, 'Substituicao filtro dagua', true, true, NULL),
    (705, 1, 9, 'Conserto molas (sist.suspensao)', true, true, NULL),
    (706, 1, 9, 'Substituicao junta (motor)', true, true, NULL),
    (707, 1, 9, 'Substituicao mang/conexao (sist.lubrif)', true, true, NULL),
    (708, 1, 9, 'Substituicao engrenagem cmdo (motor)', true, true, NULL),
    (709, 1, 9, 'Regulagem acelerador', true, true, NULL),
    (710, 1, 9, 'Remocao componentes p/manutencao', true, true, NULL),
    (711, 1, 9, 'Revisao estofamento', true, true, NULL),
    (712, 1, 9, 'Substituicao concha/pa carregadeira', true, true, NULL),
    (713, 1, 9, 'Substituicao farolete', true, true, NULL),
    (714, 1, 9, 'Instalacao faixa refletiva', true, true, NULL),
    (715, 1, 9, 'Substituicao bomba oleo (dir.hidr)', true, true, NULL),
    (716, 1, 9, 'Substituicao faixa refletiva', true, true, NULL),
    (717, 1, 9, 'Conserto farol', true, true, NULL),
    (718, 1, 9, 'Reaperto abrac/conex/mang (sist.arref)', true, true, NULL),
    (720, 1, 9, 'Reaperto abrac/conex/mang (sist.hidr)', true, true, NULL),
    (721, 1, 9, 'Substituicao reserv.expansao (sits.arref)', true, true, NULL),
    (722, 1, 9, 'Transporte funcionario', true, true, NULL),
    (723, 1, 9, 'Completado oleo hidraulico (dir.hidr)', true, true, NULL),
    (724, 1, 9, 'Revisao banco (estofamento)', true, true, NULL),
    (725, 1, 9, 'Revisao bomba hidraulica (dir.hidr)', true, true, NULL),
    (726, 1, 9, '(nao executado: sem necessidade)', true, true, NULL),
    (727, 1, 9, 'Reforma sist.eletrico', true, true, NULL),
    (728, 1, 9, 'Equipamento desatolado', true, true, NULL),
    (729, 1, 9, 'Regulagem cabo (tomada forca)', true, true, NULL),
    (730, 1, 9, 'Conserto buzina', true, true, NULL),
    (731, 1, 9, 'Substituicao engate reboque', true, true, NULL),
    (732, 1, 9, 'Desmontagem equipamento', true, true, NULL),
    (733, 1, 9, 'Fiscalizacao servicos terceiros', true, true, NULL),
    (734, 1, 9, 'Revisao diferencial', true, true, NULL),
    (735, 1, 9, 'Substituicao graxeira', true, true, NULL),
    (736, 1, 9, 'Conserto eixo cardan', true, true, NULL),
    (737, 1, 9, 'Reaperto abrac/conexao (sist.descarga)', true, true, NULL),
    (741, 1, 9, 'Substituicao valvula ar quente', true, true, NULL),
    (742, 1, 9, 'Notificacao funcional', true, true, NULL),
    (743, 1, 9, 'Recapagem pneu', true, true, NULL),
    (744, 1, 9, 'Substituicao coxim (cx.mudanca)', true, true, NULL),
    (745, 1, 9, 'Substituicao coxim (filtro ar)', true, true, NULL),
    (746, 1, 9, 'Substituicao coxim (motor)', true, true, NULL),
    (747, 1, 9, 'Substituicao cilindro (porta)', true, true, NULL),
    (748, 1, 9, 'Substituicao coifa homocinetica (sist.direcao)', true, true, NULL),
    (749, 1, 9, 'Rodizio pneu', true, true, NULL),
    (750, 1, 9, 'Inspecao', false, true, NULL),
    (751, 1, 9, 'Teste link', true, true, NULL),
    (752, 1, 9, 'Instalacao engate reboque', true, true, NULL),
    (753, 1, 9, 'Recodificacao radio', true, true, NULL),
    (754, 1, 9, 'Substituicao valvula termostatica', true, true, NULL),
    (755, 1, 9, 'Substituicao maquina vidro', true, true, NULL),
    (756, 1, 9, 'Substituicao braco dir.auxiliar (sist.direcao)', true, true, NULL),
    (757, 1, 9, 'Substituicao braco dir.pitman (sist.direcao)', true, true, NULL),
    (758, 1, 9, 'Desmontagem/montagem pneu aro 20', true, true, NULL),
    (759, 1, 9, 'Desmontagem/montagem pneu aro 13', true, true, NULL),
    (760, 1, 9, 'Desmontagem/montagem pneu aro 16', true, true, NULL),
    (761, 1, 9, 'Desmontagem/montagem pneu aro 22,5', true, true, NULL),
    (762, 1, 9, 'Desmontagem/montagem pneu aro 12', true, true, NULL),
    (763, 1, 9, 'Conserto pneu aro 20', true, true, NULL),
    (764, 1, 9, 'Conserto pneu aro 16', true, true, NULL),
    (765, 1, 9, 'Conserto pneu aro 13', true, true, NULL),
    (766, 1, 9, 'Conserto pneu aro 08', true, true, NULL),
    (767, 1, 9, 'Conserto pneu aro 14', true, true, NULL),
    (768, 1, 9, 'Desmontagem/montagem pneu aro 14', true, true, NULL),
    (769, 1, 9, 'Conserto pneu aro 15', true, true, NULL),
    (770, 1, 9, 'Desmontagem/montagem pneu aro 15', true, true, NULL),
    (773, 1, 9, 'Substituicao bomba oleo lubrificante', true, true, NULL),
    (774, 1, 9, 'Conserto turbina ar', true, true, NULL),
    (775, 1, 9, 'Substituicao junta homocinetica', true, true, NULL),
    (776, 1, 9, 'Substituicao barra estabilizadora (sist.direcao)', true, true, NULL),
    (777, 1, 9, 'Substituicao barra (sist.direcao)', true, true, NULL),
    (778, 1, 9, 'Substituicao tampa tq combustivel', true, true, NULL),
    (779, 1, 9, 'Desmontagem/montagem pneu aro 24', true, true, NULL),
    (780, 1, 9, 'Desmontagem/montagem pneu aro 17,5', true, true, NULL),
    (781, 1, 9, 'Conserto pneu aro 24', true, true, NULL),
    (788, 1, 9, 'Conserto ar condicionado', true, true, NULL),
    (791, 1, 9, 'Substituicao sensor (sist.arrefecim)', true, true, NULL),
    (792, 1, 9, 'Substituicao camisa/cilindro/pistao', true, true, NULL),
    (793, 1, 9, 'Substituicao capo', true, true, NULL),
    (794, 1, 9, 'Substituicao para-lama', true, true, NULL),
    (795, 1, 9, 'Substituicao grade', true, true, NULL),
    (796, 1, 9, 'Substituicao braco axial', true, true, NULL),
    (797, 1, 9, 'Substituicao valvula estacionario (sist.freios)', true, true, NULL),
    (798, 1, 9, 'Regulagem bomba injetora', true, true, NULL),
    (799, 1, 9, 'Conserto carburador', true, true, NULL),
    (800, 1, 9, 'Regulagem carburador', true, true, NULL),
    (801, 1, 9, 'Conserto ponta eixo', true, true, NULL),
    (802, 1, 9, 'Conserto pneu aro 22,5', true, true, NULL),
    (803, 1, 9, 'Regulagem embreagem', true, true, NULL),
    (804, 1, 9, 'Substituicao tanque combustivel', true, true, NULL),
    (805, 1, 9, 'Conserto embreagem', true, true, NULL),
    (806, 1, 9, 'Conserto radiador', true, true, NULL),
    (807, 1, 9, 'Substituicao escapamento', true, true, NULL),
    (808, 1, 9, 'Conserto indic.nivel combustivel', true, true, NULL),
    (809, 1, 9, 'Substituicao indic.nivel combustivel', true, true, NULL),
    (810, 1, 9, 'Conserto aro (pneu)', true, true, NULL),
    (811, 1, 9, 'Substituicao aro (pneu)', true, true, NULL),
    (812, 1, 9, 'Revisao bomba injetora', true, true, NULL),
    (813, 1, 9, 'Conserto bomba injetora', true, true, NULL),
    (814, 1, 9, 'Substituicao bomba injetora', true, true, NULL),
    (815, 1, 9, 'Revisao motor partida', true, true, NULL),
    (816, 1, 9, 'Conserto freio motor', true, true, NULL),
    (817, 1, 9, 'Substituicao vela pre-aquecimento', true, true, NULL),
    (818, 1, 9, 'Revisao cx.mudancas', true, true, NULL),
    (819, 1, 9, 'Completado oleo lubrificante (diferencial)', true, true, NULL),
    (820, 1, 9, 'Instalacao alarme sonoro', true, true, NULL),
    (821, 1, 9, 'Instalacao sinalizacao rotativa', true, true, NULL),
    (822, 1, 9, 'Instalacao pistola ar', true, true, NULL),
    (823, 1, 9, 'Substituicao coxim (cabine)', true, true, NULL),
    (824, 1, 9, 'Instalacao calota (roda)', true, true, NULL),
    (825, 1, 9, 'Substituicao vedacao (sist.descarga)', true, true, NULL),
    (826, 1, 9, 'Substituicao setor direcao', true, true, NULL),
    (827, 1, 9, 'Reaperto filtro oleo hidraulico', true, true, NULL),
    (828, 1, 9, 'Substituicao volante direcao', true, true, NULL),
    (829, 1, 9, 'Conserto cx.mudancas', true, true, NULL),
    (830, 1, 9, 'Substituicao cx.mudancas', true, true, NULL),
    (831, 1, 9, 'Conserto direcao', true, true, NULL),
    (832, 1, 9, 'Conserto sist.freios', true, true, NULL),
    (833, 1, 9, 'Substituicao reserv.limp.para-brisas', true, true, NULL),
    (834, 1, 9, 'Substituicao grampo/mola (sist.susp.)', true, true, NULL),
    (835, 1, 9, 'Substituicao alavanca acion.direcao', true, true, NULL),
    (836, 1, 9, 'Desmontagem equipamento', true, true, NULL),
    (837, 1, 9, 'Substituicao valvula pedal (sist.freios)', true, true, NULL),
    (838, 1, 9, 'Revisao alinhamento 3i��.eixo', true, true, NULL),
    (839, 1, 9, 'Substituicao bomba limp.para-brisa', true, true, NULL),
    (840, 1, 9, 'Substituicao tambor (sist.freios)', true, true, NULL),
    (841, 1, 9, 'Conserto velocimetro', true, true, NULL),
    (842, 1, 9, 'Conserto odometro', true, true, NULL),
    (843, 1, 9, 'Limpeza motor externa', false, true, NULL),
    (844, 1, 9, 'Limpeza motor interna', false, true, NULL),
    (845, 1, 9, 'Conserto cabo velocimetro', true, true, NULL),
    (846, 1, 9, 'Substituicao cabo velocimetro', true, true, NULL),
    (847, 1, 9, 'Limpeza cabo/terminal bateria', true, true, NULL),
    (848, 1, 9, 'Substituicao carregador voltagem', true, true, NULL),
    (849, 1, 9, 'Conserto carregador voltagem', true, true, NULL),
    (850, 1, 9, 'Conserto pedal acelerador', true, true, NULL),
    (851, 1, 9, 'Conserto cabo acelerador', true, true, NULL),
    (852, 1, 9, 'Substituicao cabo acelerador', false, true, NULL),
    (853, 1, 9, 'Reforma estofamento', true, true, NULL),
    (854, 1, 9, 'Substituicao freio-motor', true, true, NULL),
    (855, 1, 9, 'Conserto amortecedor', true, true, NULL),
    (856, 1, 9, 'Conserto concha/pa carregadeira', true, true, NULL),
    (857, 1, 9, 'Informacoes diversas', false, true, NULL),
    (858, 1, 9, 'Substituicao estribo', true, true, NULL),
    (859, 1, 9, 'Conserto cabine', true, true, NULL),
    (860, 1, 9, 'Conserto bomba dagua', true, true, NULL),
    (861, 1, 9, 'Substituicao motor', false, true, NULL),
    (862, 1, 9, 'Substituicao cabecote motor', true, true, NULL),
    (863, 1, 9, 'Substituicao bicos injecao', true, true, NULL),
    (864, 1, 9, 'Substituicao cabo freio estacionario', true, true, NULL),
    (865, 1, 9, 'Substituicao coifa/homocinetica', true, true, NULL),
    (866, 1, 9, 'Substituicao interr luz re', true, true, NULL),
    (867, 1, 9, 'Substituicao manopla', true, true, NULL),
    (868, 1, 9, 'Desmontagem/montagem pneu aro 18', true, true, NULL),
    (869, 1, 9, 'Desmontagem/montagem pneu aro 21', true, true, NULL),
    (871, 1, 9, 'Preventiva mensal', true, true, NULL),
    (872, 1, 9, 'Preventiva semestral', true, true, NULL),
    (873, 1, 9, 'Preventiva anual', true, true, NULL),
    (874, 1, 9, 'Preventiva mensal', false, true, NULL),
    (875, 1, 9, 'Preventiva semestral', false, true, NULL),
    (876, 1, 9, 'Preventiva anual', true, true, NULL),
    (877, 1, 9, 'Confeccao componentes', true, true, NULL),
    (878, 1, 9, 'Instalacao manometro', true, true, NULL),
    (879, 1, 9, 'Instalacao registro', true, true, NULL),
    (880, 1, 9, 'Rearme reli�� sobrecorrente', true, true, NULL),
    (881, 1, 9, 'Conserto engate reboque', true, true, NULL),
    (882, 1, 9, 'Substituicao coletor surdina', true, true, NULL),
    (883, 1, 9, 'Remocao componente p/reserva', true, true, NULL),
    (884, 1, 9, 'Conserto surdina', true, true, NULL),
    (885, 1, 9, 'Sangria bicos injecao', true, true, NULL),
    (886, 1, 9, 'Desmontagem/montagem pneu aro 17', true, true, NULL),
    (887, 1, 9, 'Desmontagem/montagem pneu aro 19', true, true, NULL),
    (888, 1, 9, 'Conserto pneu aro 17', true, true, NULL),
    (889, 1, 9, 'Conserto pneu aro 19', true, true, NULL),
    (890, 1, 9, 'Conserto pneu aro 17,5', true, true, NULL),
    (891, 1, 9, 'Substituicao protetor termico', true, true, NULL),
    (892, 1, 9, 'Informacoes diversas', false, true, NULL),
    (893, 1, 9, 'Desmontagem/montagem pneu aro 08', true, true, NULL),
    (894, 1, 9, 'Substituicao gaxetas', false, true, NULL),
    (895, 1, 9, 'Substituicao rolamento', false, true, NULL),
    (896, 1, 9, 'Substituicao selo mecanico', false, true, NULL),
    (897, 1, 9, 'Substituicao rotor', false, true, NULL),
    (898, 1, 9, 'SUBSTITUICAO ACOPLAMENTO', true, false, NULL),
    (899, 1, 9, 'Substituicao lubrificante', false, true, NULL),
    (900, 1, 9, 'Substituicao estator', false, true, NULL),
    (901, 1, 9, 'Substituicao eixo', false, true, NULL),
    (902, 1, 9, 'Substituicao membrana', false, true, NULL),
    (903, 1, 9, 'Substituicao anel oring', false, true, NULL),
    (904, 1, 9, 'Substituicao componentes diversos', false, true, NULL),
    (905, 1, 9, 'Substituicao ventoinha', false, true, NULL),
    (906, 1, 9, 'Substituicao pino elastico', false, true, NULL),
    (907, 1, 9, 'Substituicao retentor', false, true, NULL),
    (908, 1, 9, 'Retirado equipamento', true, true, NULL),
    (909, 1, 9, 'Transporte equipamento p/terceiros', true, true, NULL),
    (910, 1, 9, 'INSTALACAO (CONCLUIDA)', true, false, NULL),
    (911, 1, 9, 'Transporte equipamento', false, true, NULL),
    (912, 1, 9, 'Montagem equipamento', false, true, NULL),
    (913, 1, 9, 'Inspecao', false, true, NULL),
    (914, 1, 9, 'Desmontagem equipamento', false, true, NULL),
    (916, 1, 9, 'Preventiva mensal', false, true, NULL),
    (917, 1, 9, 'Preventiva semestral', false, true, NULL),
    (918, 1, 9, 'Preventiva anual', false, true, NULL),
    (919, 1, 9, 'Confeccao componentes', false, true, NULL),
    (920, 1, 9, 'Instalacao manometro', false, true, NULL),
    (921, 1, 9, 'Instalacao registro', false, true, NULL),
    (922, 1, 9, 'Escorvado', false, true, NULL),
    (923, 1, 9, 'Alinhado', false, true, NULL),
    (924, 1, 9, 'Limpeza interna', false, true, NULL),
    (925, 1, 9, 'Reaperto conexao', false, true, NULL),
    (926, 1, 9, 'Ajuste de fixacao', false, true, NULL),
    (927, 1, 9, 'Limpeza do rotametro', false, true, NULL),
    (928, 1, 9, 'Regulagem modulo de desvio', false, true, NULL),
    (929, 1, 9, 'Alteracao linha produto/ponto aplicacao', false, true, NULL),
    (930, 1, 9, 'Substituicao conexao/tubulacao', false, true, NULL),
    (931, 1, 9, 'Desobstrucao linha produto', false, true, NULL),
    (932, 1, 9, 'Melhoria no equipamento', false, true, NULL),
    (933, 1, 9, 'Regulagens diversas', true, true, NULL),
    (934, 1, 9, 'Checagem dados operacionais', false, true, NULL),
    (935, 1, 9, 'Limpeza externa', false, true, NULL),
    (936, 1, 9, 'Ajuste de gaxetas', false, true, NULL),
    (937, 1, 9, 'Complementado lubrificante', false, true, NULL),
    (938, 1, 9, 'Conserto limp.para-brisa', true, true, NULL),
    (939, 1, 9, 'Substituicao evaporador', true, true, NULL),
    (940, 1, 9, 'Substituicao bandeija', true, true, NULL),
    (941, 1, 9, 'Conserto ventilador', true, true, NULL),
    (942, 1, 9, 'Substituicao equipamento', true, true, NULL),
    (943, 1, 9, 'Desmontagem/montagem pneu aro 10', true, true, NULL),
    (944, 1, 9, 'Desmontagem/montagem pneu aro 25', true, true, NULL),
    (945, 1, 9, 'Verificacao aquecim/mancais/ruidos', true, true, NULL),
    (946, 1, 9, 'Verificacao base/acopl/vazam', true, true, NULL),
    (947, 1, 9, 'Verificacao desg.rotor/corpo/eixo', true, true, NULL),
    (948, 1, 9, 'PINTURA', true, false, NULL),
    (949, 1, 9, 'Verificacao correia/filtro/lubrif.', true, true, NULL),
    (950, 1, 9, 'Substituicao correia/filtro/lubrif.', true, true, NULL),
    (951, 1, 9, 'Verificacao polia/pressost/purga', true, true, NULL),
    (952, 1, 9, 'Verificacao aquecim/cx.lig/rotacao', true, true, NULL),
    (953, 1, 9, 'Verificacao cabos/isolacao/protecoes', true, true, NULL),
    (954, 1, 9, 'Limpeza interna/externa', true, true, NULL),
    (955, 1, 9, 'Verificacao aquecim/conex/protecoes', true, true, NULL),
    (956, 1, 9, 'Copiar programa/parametros', true, true, NULL),
    (957, 1, 9, 'Verificacao corrente/protecoes/rotacao', true, true, NULL),
    (958, 1, 9, 'Verificacao poste/travessa/acessorios', true, true, NULL),
    (959, 1, 9, 'Verificacao nivel oleo/vazamentos', true, true, NULL),
    (960, 1, 9, 'Verificacao alinham/acoplamento', true, true, NULL),
    (961, 1, 9, 'Verificacao rolamento/elem.girantes', true, true, NULL),
    (962, 1, 9, 'Verificacao cabos/correntes/coroa', true, true, NULL),
    (963, 1, 9, 'Verificacao guias/perfis/lubrif', true, true, NULL),
    (964, 1, 9, 'Verificacao reg.vacuo/valvulas', true, true, NULL),
    (965, 1, 9, 'Verificacao filtros/mod.desvio', true, true, NULL),
    (966, 1, 9, 'Verificacao dosadores/ejetores', true, true, NULL),
    (967, 1, 9, 'Substituicao filtros/valvulas', true, true, NULL),
    (968, 1, 9, 'Verificacao ejetores/vacuo', true, true, NULL),
    (969, 1, 9, 'Verificacao mod.desvio/reg.vacuo', true, true, NULL),
    (970, 1, 9, 'Verificacao correias/mancais/lubrif.', true, true, NULL),
    (971, 1, 9, 'Limpeza tubulacao', true, true, NULL),
    (972, 1, 9, 'Verificacao acessos/avisos', true, true, NULL),
    (973, 1, 9, 'Verificacao cabos/correntes/vazamentos', true, true, NULL),
    (974, 1, 9, 'Verificacao isolacao oleo/gas', true, true, NULL),
    (975, 1, 9, 'Conserto pneu aro 12', true, true, NULL),
    (976, 1, 9, 'Verificacao mangote/vazamentos', true, true, NULL),
    (977, 1, 9, 'Identificacao poste cmdo desativado', true, true, NULL),
    (978, 1, 9, 'Processamento fichas trabalho', false, true, NULL),
    (979, 1, 9, 'Processamento fichas trabalho', true, true, NULL),
    (980, 1, 9, 'Verificacao ch.fim-de-curso', true, true, NULL),
    (981, 1, 9, 'Revisao carroceria (diversos)', true, true, NULL),
    (982, 1, 9, 'Conserto sist.eletrico (outros)', true, true, NULL),
    (983, 1, 9, 'Verificacao diagrama eletrico', true, true, NULL),
    (984, 1, 9, 'Verificacao nivel oleo/vazamentos', true, true, NULL),
    (985, 1, 9, 'Conserto coroa/paraf.sem-fim', true, true, NULL),
    (986, 1, 9, 'Confeccao coroa/paraf.sem-fim', true, true, NULL),
    (987, 1, 9, 'Vistoria tecnica', true, true, NULL),
    (988, 1, 9, 'Limpeza externa', false, true, NULL),
    (989, 1, 9, 'Substituicao oleo hidraulico', false, true, NULL),
    (990, 1, 9, 'Verificacao nivel liq.arrefecimento', true, true, NULL),
    (991, 1, 9, 'Afericao geometria', true, true, NULL),
    (992, 1, 9, 'Fornecimento material', false, true, NULL),
    (993, 1, 9, 'Fornecimento material', false, true, NULL),
    (994, 1, 9, 'Fornecimento material', false, true, NULL),
    (995, 1, 9, 'Verificacao conexoes', true, true, NULL),
    (996, 1, 9, 'Conserto pneu aro 18', true, true, NULL),
    (997, 1, 9, 'Conserto pneu aro 21', true, true, NULL),
    (998, 1, 9, 'Lubrificacao valvs/afericao manometros', true, true, NULL),
    (999, 1, 9, 'Inspecao visual int/ext', true, true, NULL),
    (1000, 1, 9, 'Verificacao esp.chapas/juntas vedacao', true, true, NULL),
    (1001, 1, 9, 'Inspecao visual interna', true, true, NULL),
    (1002, 1, 9, 'Teste hidrostatico', true, true, NULL),
    (1003, 1, 9, 'Substituicao rolamento', false, true, NULL),
    (1004, 1, 9, 'Substituicao selo mecanico', false, true, NULL),
    (1005, 1, 9, 'Substituicao retentor', false, true, NULL),
    (1006, 1, 9, 'Substituicao anel vedacao', true, true, NULL),
    (1007, 1, 9, 'Rebobinagem', false, true, NULL),
    (1008, 1, 9, 'Limpeza externa', false, true, NULL),
    (1009, 1, 9, 'Limpeza interna', false, true, NULL),
    (1011, 1, 9, 'Substituicao luva desgaste', true, true, NULL),
    (1012, 1, 9, 'Substituicao crivo/filtro', true, true, NULL),
    (1013, 1, 9, 'Informacoes diversas', false, true, NULL),
    (1014, 1, 9, 'Vistoria tecnica', false, true, NULL),
    (1015, 1, 9, 'Vistoria tecnica', true, true, NULL),
    (1016, 1, 9, 'Substituicao anel desgaste', true, true, NULL),
    (1017, 1, 9, 'Fornecimento material', false, true, NULL),
    (1018, 1, 9, 'Verificacao cabos/polias/roldanas', true, true, NULL),
    (1019, 1, 9, 'Informacoes diversas', false, true, NULL),
    (1020, 1, 9, 'Remocao equipamento', false, true, NULL),
    (1021, 1, 9, 'Rebobinagem', false, true, NULL),
    (1022, 1, 9, 'Manutencao preventiva', false, true, NULL),
    (1023, 1, 9, 'Montagem e desmontagem', true, true, NULL),
    (1024, 1, 9, 'Substituicao botao emergencia', true, true, NULL),
    (1025, 1, 9, 'Substituicao luva protetora', true, true, NULL),
    (1026, 1, 9, 'Substituicao correia', true, true, NULL),
    (1027, 1, 9, 'Manuteni��i��o preventiva', true, true, NULL),
    (1028, 1, 9, 'Usinagem', true, true, NULL),
    (1029, 1, 9, 'ALINHAMENTO', true, false, NULL),
    (1030, 1, 9, 'ATUALIZACAO PATRIMONIAL', true, false, NULL),
    (1031, 1, 9, 'SUBSTITUICAO IHM', true, false, NULL),
    (1032, 1, 9, 'DISPONIBILIDADE DE PESSOAL', true, false, NULL),
    (1033, 1, 9, 'TESTE ISOLAÇÂO (CARCAÇA): BAIXA', true, false, NULL),
    (1034, 1, 9, 'TESTE ISOLAÇÃO (FASES): BAIXA', true, false, NULL),
    (1037, 1, 9, 'DESERNERGIZADO', true, false, NULL),
    (1038, 1, 9, 'ENERGIZADO', true, false, NULL),
    (1039, 1, 9, 'TESTE ISOLAÇÃO OK', true, false, NULL),
    (1040, 1, 9, 'TESTE FUNCIONAMENTO', true, false, NULL),
    (1041, 1, 9, 'DISJUNTOR REARMADO ', true, false, NULL),
    (1042, 1, 9, 'SUBSTITUICAO DISJUNTOR', true, false, NULL),
    (1043, 1, 9, 'FORNECIMENTO ENERGIA ELETRICA', true, false, NULL),
    (1044, 1, 9, 'EXAUSTOR: SUBSTITUICAO FILTRO', true, false, NULL),
    (1045, 1, 9, 'REMOCAO EQUIPAMENTO', true, false, NULL),
    (1046, 1, 9, 'INSTALACAO (INICIO)', true, false, NULL),
    (1047, 1, 9, 'AJUSTES CHAVE SELETORA', true, false, NULL),
    (1048, 1, 9, 'PRESTAÇÃO SERVICOS CONFORME CONTRATO', true, false, '1048'),
    (1049, 1, 9, 'DESMONTAGEM EQUIPTO (INICIO)', true, false, NULL),
    (1050, 1, 9, 'DESMONTAGEM EQUIPTO (ANDAMENTO)', true, false, NULL),
    (1051, 1, 9, 'DESMONTAGEM EQUIPTO (CONCLUIDA)', true, false, NULL),
    (1052, 1, 9, 'MONTAGEM EQUIPTO (INICIO)', true, false, NULL),
    (1053, 1, 9, 'MONTAGEM EQUIPTO (ANDAMENTO)', true, false, NULL),
    (1054, 1, 9, 'MONTAGEM EQUIPTO (CONCLUIDA)', true, false, NULL),
    (1055, 1, 9, 'TESTE COMUNICACAO OK', true, false, NULL),
    (1056, 1, 9, 'TESTE COMUNICACAO (FALHA)', true, false, NULL),
    (1057, 1, 9, 'AJUSTES ESQUEMA ELETRICO', true, false, NULL),
    (1058, 1, 9, 'TRANSPORTE EQUIPAMENTO', true, false, NULL),
    (1059, 1, 9, 'USINAGEM', true, false, NULL),
    (1060, 1, 9, 'SOLDAGEM/SERRALHERIA', true, false, NULL),
    (1061, 1, 9, 'LIGAÇÃO ELÉTRICA EQUIPAMENTO', true, false, NULL),
    (1062, 1, 9, 'REMOCAO COMPONENTE', true, false, NULL),
    (1063, 1, 9, 'TRANSPORTE MATERIAIS', true, false, NULL),
    (1064, 1, 9, '(NAO REALIZADO)', true, false, NULL),
    (1065, 1, 9, 'APROPRIACAO CUSTOS MENSAIS', true, false, NULL),
    (1066, 1, 9, 'IDENTIFICACAO RISCO CHOQUE ELETRICO', true, false, NULL),
    (1067, 1, 9, 'INSTALACAO DISJUNTOR', true, false, NULL)
ON CONFLICT (id) DO NOTHING;

