-- =============================================================================
-- Table: contracts
-- Exported: 2026-03-05T17:29:30.537Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.contracts CASCADE;

CREATE TABLE IF NOT EXISTS public.contracts (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_company_id integer,
    client_department_id integer,
    provider_company_id integer,
    provider_department_id integer,
    description character varying(255),
    is_available boolean DEFAULT false,
    is_deleted boolean DEFAULT false,
    code character varying(255),
    status_id integer,
    created_user_id integer,
    created_date timestamp without time zone DEFAULT now(),
    updated_user_id text,
    updated_date text,
    deleted_user_id text,
    deleted_date text,
    is_dev boolean DEFAULT false,
    version character varying(255),
    default_ov_asset_id integer,
    default_activity_id integer,
    date_start text,
    date_end text,
    total_value text,
    client_id integer,
    PRIMARY KEY (id)
);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_contracts_created_at ON public.contracts(created_at);
-- CREATE INDEX idx_contracts_user_id ON public.contracts(user_id);

