-- =============================================================================
-- Table: extensions
-- Exported: 2026-03-05T17:29:31.444Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.extensions CASCADE;

CREATE TABLE IF NOT EXISTS public.extensions (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type character varying(255),
    settings jsonb,
    tenant_external_id character varying(255),
    inserted_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    PRIMARY KEY (id)
);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_extensions_created_at ON public.extensions(created_at);
-- CREATE INDEX idx_extensions_user_id ON public.extensions(user_id);

