-- =============================================================================
-- Table: cfg_units_statuses
-- Exported: 2026-03-05T17:29:28.833Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.cfg_units_statuses CASCADE;

CREATE TABLE IF NOT EXISTS public.cfg_units_statuses (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code character varying(255),
    description character varying(255),
    color text,
    PRIMARY KEY (id)
);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_cfg_units_statuses_created_at ON public.cfg_units_statuses(created_at);
-- CREATE INDEX idx_cfg_units_statuses_user_id ON public.cfg_units_statuses(user_id);

