-- =============================================================================
-- Table: clients
-- Exported: 2026-03-05T17:29:29.938Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.clients CASCADE;

CREATE TABLE IF NOT EXISTS public.clients (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255),
    code character varying(255),
    email text,
    mobile text,
    address text,
    img_file_path text,
    img_file_name text,
    is_available boolean DEFAULT false,
    created_user_id text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at text,
    updated_user_id text,
    deleted_at text,
    deleted_user_id text,
    is_deleted boolean DEFAULT false,
    company_id text,
    PRIMARY KEY (id)
);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_clients_created_at ON public.clients(created_at);
-- CREATE INDEX idx_clients_user_id ON public.clients(user_id);

