-- =============================================================================
-- Table: units
-- Exported: 2026-03-05T17:29:32.473Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.units CASCADE;

CREATE TABLE IF NOT EXISTS public.units (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp DEFAULT now()

);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_units_created_at ON public.units(created_at);
-- CREATE INDEX idx_units_user_id ON public.units(user_id);

