-- =============================================================================
-- Table: users
-- Exported: 2026-03-05T17:29:33.090Z
-- Method: REST API Enhanced Extraction
-- =============================================================================

DROP TABLE IF EXISTS public.users CASCADE;

CREATE TABLE IF NOT EXISTS public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email character varying(255),
    name_full character varying(255),
    name_short character varying(255),
    mobile character varying(255),
    phone text,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    updated_user_id text,
    team_id integer,
    is_team_leader boolean DEFAULT false,
    img_file_path character varying(255),
    company_id text,
    department_id text,
    token_fcm text,
    uuid uuid DEFAULT gen_random_uuid(),
    status_id integer,
    is_admin boolean DEFAULT false,
    is_admin_super boolean DEFAULT false,
    code text,
    version_app text,
    img_file_name character varying(255),
    team_id_previous integer,
    ov_in_progress_leader_id integer,
    profile_id integer,
    vehicle_id text,
    is_available boolean DEFAULT false,
    is_ov_in_progress boolean DEFAULT false,
    team_amount integer,
    version_offline_user text,
    version_offline_app text,
    o_contract_id_in_progress integer,
    o_type_id_in_progress integer,
    o_type_sub_id_in_progress integer,
    o_plan_id_in_progress integer,
    o_asset_tag_id_in_progress integer,
    o_unit_id_in_progress integer,
    o_system_id_in_progress integer,
    o_system_parent_id_in_progress integer,
    o_unit_type_id_in_progress integer,
    o_unit_type_parent_id_in_progress integer,
    o_object_id_in_progress integer,
    ov_id_in_progress integer,
    o_id_in_progress integer,
    op_id_in_progress integer,
    notifications_amount integer,
    mobile_full character varying(255),
    mobile_mask character varying(255),
    mobile_whatsapp character varying(255),
    migrated_at timestamp without time zone DEFAULT now(),
    latitude numeric,
    longitude numeric,
    tracker_at timestamp without time zone DEFAULT now(),
    ov_id_in_progress_mask text,
    PRIMARY KEY (id)
);

-- Indexes (add based on your query patterns):
-- CREATE INDEX idx_users_created_at ON public.users(created_at);
-- CREATE INDEX idx_users_user_id ON public.users(user_id);

